from enum import Enum
from typing import Literal


class IngestionSourceType(Enum):
    MYSQL = "MYSQL"
    POSTGRESQL = "POSTGRESQL"
    REDSHIFT = "REDSHIFT"
    SQLDW = "SQLDW"
    SQLSERVER = "SQLSERVER"
    SALESFORCE = "SALESFORCE"
    BIGQUERY = "BIGQUERY"
    NETSUITE = "NETSUITE"
    WORKDAY_RAAS = "WORKDAY_RAAS"
    GA4_RAW_DATA = "GA4_RAW_DATA"
    SERVICENOW = "SERVICENOW"
    MANAGED_POSTGRESQL = "MANAGED_POSTGRESQL"
    ORACLE = "ORACLE"
    TERADATA = "TERADATA"
    SHAREPOINT = "SHAREPOINT"
    DYNAMICS365 = "DYNAMICS365"
    CONFLUENCE = "CONFLUENCE"
    META_MARKETING = "META_MARKETING"
    GOOGLE_ADS = "GOOGLE_ADS"
    TIKTOK_ADS = "TIKTOK_ADS"
    SALESFORCE_MARKETING_CLOUD = "SALESFORCE_MARKETING_CLOUD"
    HUBSPOT = "HUBSPOT"
    WORKDAY_HCM = "WORKDAY_HCM"
    GUIDEWIRE = "GUIDEWIRE"
    ZENDESK = "ZENDESK"
    FOREIGN_CATALOG = "FOREIGN_CATALOG"


IngestionSourceTypeParam = (
    Literal[
        "MYSQL",
        "POSTGRESQL",
        "REDSHIFT",
        "SQLDW",
        "SQLSERVER",
        "SALESFORCE",
        "BIGQUERY",
        "NETSUITE",
        "WORKDAY_RAAS",
        "GA4_RAW_DATA",
        "SERVICENOW",
        "MANAGED_POSTGRESQL",
        "ORACLE",
        "TERADATA",
        "SHAREPOINT",
        "DYNAMICS365",
        "CONFLUENCE",
        "META_MARKETING",
        "GOOGLE_ADS",
        "TIKTOK_ADS",
        "SALESFORCE_MARKETING_CLOUD",
        "HUBSPOT",
        "WORKDAY_HCM",
        "GUIDEWIRE",
        "ZENDESK",
        "FOREIGN_CATALOG",
    ]
    | IngestionSourceType
)
