Local = true
Cloud = false

[Env]
  CONTENT1 = ""
  CONTENT2 = "permissions: []"
  PYTHONDONTWRITEBYTECODE = "1"
  PYTHONUNBUFFERED = "1"
  PYTHONUTF8 = "1"
  UV_PYTHON = "3.10"

[EnvMatrix]
  DATABRICKS_BUNDLE_ENGINE = ["terraform", "direct"]
