# Code generated by pydabs-codegen. DO NOT EDIT.

from dataclasses import dataclass
from typing import TYPE_CHECKING, TypedDict

from databricks.bundles.core._transform import _transform
from databricks.bundles.core._transform_to_json import _transform_to_json_value
from databricks.bundles.core._variable import VariableOr, VariableOrOptional

if TYPE_CHECKING:
    from typing_extensions import Self


@dataclass(kw_only=True)
class ApproxCountDistinctFunction:
    """
    :meta private: [EXPERIMENTAL]

    Computes the approximate count of distinct values.
    """

    input: VariableOr[str]
    """
    :meta private: [EXPERIMENTAL]
    
    [Private Preview] The input column from which the approximate count of distinct values is computed.
    """

    relative_sd: VariableOrOptional[float] = None
    """
    :meta private: [EXPERIMENTAL]
    
    [Private Preview] The maximum relative standard deviation allowed (default defined by Spark).
    """

    @classmethod
    def from_dict(cls, value: "ApproxCountDistinctFunctionDict") -> "Self":
        return _transform(cls, value)

    def as_dict(self) -> "ApproxCountDistinctFunctionDict":
        return _transform_to_json_value(self)  # type:ignore


class ApproxCountDistinctFunctionDict(TypedDict, total=False):
    """"""

    input: VariableOr[str]
    """
    :meta private: [EXPERIMENTAL]
    
    [Private Preview] The input column from which the approximate count of distinct values is computed.
    """

    relative_sd: VariableOrOptional[float]
    """
    :meta private: [EXPERIMENTAL]
    
    [Private Preview] The maximum relative standard deviation allowed (default defined by Spark).
    """


ApproxCountDistinctFunctionParam = (
    ApproxCountDistinctFunctionDict | ApproxCountDistinctFunction
)
