# Code generated by pydabs-codegen. DO NOT EDIT.

from dataclasses import dataclass
from typing import TYPE_CHECKING, TypedDict

from databricks.bundles.core._transform import _transform
from databricks.bundles.core._transform_to_json import _transform_to_json_value
from databricks.bundles.core._variable import VariableOr

if TYPE_CHECKING:
    from typing_extensions import Self


@dataclass(kw_only=True)
class CountFunction:
    """
    :meta private: [EXPERIMENTAL]

    Computes the count of values.
    """

    input: VariableOr[str]
    """
    :meta private: [EXPERIMENTAL]
    
    [Private Preview] The input column from which the count is computed. For Kafka sources, use dot-prefixed path
    notation (e.g., "value.amount"). For nested fields, the leaf node name is used.
    Colon-prefixed notation (e.g., "value:amount") is supported for backwards
    compatibility but is deprecated; migrate to dot notation.
    """

    @classmethod
    def from_dict(cls, value: "CountFunctionDict") -> "Self":
        return _transform(cls, value)

    def as_dict(self) -> "CountFunctionDict":
        return _transform_to_json_value(self)  # type:ignore


class CountFunctionDict(TypedDict, total=False):
    """"""

    input: VariableOr[str]
    """
    :meta private: [EXPERIMENTAL]
    
    [Private Preview] The input column from which the count is computed. For Kafka sources, use dot-prefixed path
    notation (e.g., "value.amount"). For nested fields, the leaf node name is used.
    Colon-prefixed notation (e.g., "value:amount") is supported for backwards
    compatibility but is deprecated; migrate to dot notation.
    """


CountFunctionParam = CountFunctionDict | CountFunction
