# Code generated by pydabs-codegen. DO NOT EDIT.

from dataclasses import dataclass, field
from typing import TYPE_CHECKING, TypedDict

from databricks.bundles.core._transform import _transform
from databricks.bundles.core._transform_to_json import _transform_to_json_value
from databricks.bundles.core._variable import VariableOr, VariableOrList
from databricks.bundles.features._models.input_binding import (
    InputBinding,
    InputBindingParam,
)

if TYPE_CHECKING:
    from typing_extensions import Self


@dataclass(kw_only=True)
class CustomUdf:
    """
    :meta private: [EXPERIMENTAL]

    A CustomUdf function applies a registered Unity Catalog function row-wise to
    source columns, producing a single output column per row.
    """

    function_path: VariableOr[str]
    """
    :meta private: [EXPERIMENTAL]
    
    [Private Preview] Fully qualified 3-part Unity Catalog path of the function to apply.
    """

    input_bindings: VariableOrList[InputBinding] = field(default_factory=list)
    """
    :meta private: [EXPERIMENTAL]
    
    [Private Preview] Binds each UC function parameter to a source column.
    May be empty for zero-argument functions (e.g. a timestamp generator).
    """

    @classmethod
    def from_dict(cls, value: "CustomUdfDict") -> "Self":
        return _transform(cls, value)

    def as_dict(self) -> "CustomUdfDict":
        return _transform_to_json_value(self)  # type:ignore


class CustomUdfDict(TypedDict, total=False):
    """"""

    function_path: VariableOr[str]
    """
    :meta private: [EXPERIMENTAL]
    
    [Private Preview] Fully qualified 3-part Unity Catalog path of the function to apply.
    """

    input_bindings: VariableOrList[InputBindingParam]
    """
    :meta private: [EXPERIMENTAL]
    
    [Private Preview] Binds each UC function parameter to a source column.
    May be empty for zero-argument functions (e.g. a timestamp generator).
    """


CustomUdfParam = CustomUdfDict | CustomUdf
