# Code generated by pydabs-codegen. DO NOT EDIT.

from dataclasses import dataclass
from typing import TYPE_CHECKING, TypedDict

from databricks.bundles.core._transform import _transform
from databricks.bundles.core._transform_to_json import _transform_to_json_value
from databricks.bundles.core._variable import VariableOr

if TYPE_CHECKING:
    from typing_extensions import Self


@dataclass(kw_only=True)
class FeatureReference:
    """
    :meta private: [EXPERIMENTAL]

    A reference to one registered upstream Feature. A message rather than a bare name so an
    upstream can later be pinned more precisely (e.g. by version) without a breaking type change.
    """

    feature: VariableOr[str]
    """
    :meta private: [EXPERIMENTAL]
    
    [Private Preview] The three-part full name of the upstream Feature.
    """

    @classmethod
    def from_dict(cls, value: "FeatureReferenceDict") -> "Self":
        return _transform(cls, value)

    def as_dict(self) -> "FeatureReferenceDict":
        return _transform_to_json_value(self)  # type:ignore


class FeatureReferenceDict(TypedDict, total=False):
    """"""

    feature: VariableOr[str]
    """
    :meta private: [EXPERIMENTAL]
    
    [Private Preview] The three-part full name of the upstream Feature.
    """


FeatureReferenceParam = FeatureReferenceDict | FeatureReference
