# Code generated by pydabs-codegen. DO NOT EDIT.

from dataclasses import dataclass
from typing import TYPE_CHECKING, TypedDict

from databricks.bundles.core._transform import _transform
from databricks.bundles.core._transform_to_json import _transform_to_json_value
from databricks.bundles.core._variable import VariableOr

if TYPE_CHECKING:
    from typing_extensions import Self


@dataclass(kw_only=True)
class LastFunction:
    """
    :meta private: [EXPERIMENTAL]

    Returns the last value.
    """

    input: VariableOr[str]
    """
    :meta private: [EXPERIMENTAL]
    
    [Private Preview] The input column from which the last value is returned.
    """

    @classmethod
    def from_dict(cls, value: "LastFunctionDict") -> "Self":
        return _transform(cls, value)

    def as_dict(self) -> "LastFunctionDict":
        return _transform_to_json_value(self)  # type:ignore


class LastFunctionDict(TypedDict, total=False):
    """"""

    input: VariableOr[str]
    """
    :meta private: [EXPERIMENTAL]
    
    [Private Preview] The input column from which the last value is returned.
    """


LastFunctionParam = LastFunctionDict | LastFunction
