# Code generated by pydabs-codegen. DO NOT EDIT.

from dataclasses import dataclass
from typing import TYPE_CHECKING, TypedDict

from databricks.bundles.core._transform import _transform
from databricks.bundles.core._transform_to_json import _transform_to_json_value
from databricks.bundles.core._variable import VariableOr

if TYPE_CHECKING:
    from typing_extensions import Self


@dataclass(kw_only=True)
class LastNFunction:
    """
    :meta private: [EXPERIMENTAL]

    Returns the last N values, ordered by the feature's timeseries column.
    """

    input: VariableOr[str]
    """
    :meta private: [EXPERIMENTAL]
    
    [Private Preview] The input column from which the last N values are returned.
    """

    n: VariableOr[int]
    """
    :meta private: [EXPERIMENTAL]
    
    [Private Preview] The number of values to return.
    """

    @classmethod
    def from_dict(cls, value: "LastNFunctionDict") -> "Self":
        return _transform(cls, value)

    def as_dict(self) -> "LastNFunctionDict":
        return _transform_to_json_value(self)  # type:ignore


class LastNFunctionDict(TypedDict, total=False):
    """"""

    input: VariableOr[str]
    """
    :meta private: [EXPERIMENTAL]
    
    [Private Preview] The input column from which the last N values are returned.
    """

    n: VariableOr[int]
    """
    :meta private: [EXPERIMENTAL]
    
    [Private Preview] The number of values to return.
    """


LastNFunctionParam = LastNFunctionDict | LastNFunction
