# Code generated by pydabs-codegen. DO NOT EDIT.

from dataclasses import dataclass
from typing import TYPE_CHECKING, TypedDict

from databricks.bundles.core._transform import _transform
from databricks.bundles.core._transform_to_json import _transform_to_json_value
from databricks.bundles.core._variable import VariableOrOptional
from databricks.bundles.features._models.flat_schema import FlatSchema, FlatSchemaParam

if TYPE_CHECKING:
    from typing_extensions import Self


@dataclass(kw_only=True)
class RequestSource:
    """
    :meta private: [EXPERIMENTAL]

    A request-time data source whose value is provided at inference time: offline batch scoring or online serving endpoint
    """

    dataframe_schema: VariableOrOptional[str] = None
    """
    :meta private: [EXPERIMENTAL]
    
    [Private Preview] A schema containing scalar or nested fields, in Spark StructType JSON format
    (from df.schema.json()). This preserves field, array-element, and map-value nullability.
    """

    flat_schema: VariableOrOptional[FlatSchema] = None
    """
    :meta private: [EXPERIMENTAL]
    
    [Private Preview] A flat schema with scalar-typed fields only.
    """

    @classmethod
    def from_dict(cls, value: "RequestSourceDict") -> "Self":
        return _transform(cls, value)

    def as_dict(self) -> "RequestSourceDict":
        return _transform_to_json_value(self)  # type:ignore


class RequestSourceDict(TypedDict, total=False):
    """"""

    dataframe_schema: VariableOrOptional[str]
    """
    :meta private: [EXPERIMENTAL]
    
    [Private Preview] A schema containing scalar or nested fields, in Spark StructType JSON format
    (from df.schema.json()). This preserves field, array-element, and map-value nullability.
    """

    flat_schema: VariableOrOptional[FlatSchemaParam]
    """
    :meta private: [EXPERIMENTAL]
    
    [Private Preview] A flat schema with scalar-typed fields only.
    """


RequestSourceParam = RequestSourceDict | RequestSource
