# Code generated by pydabs-codegen. DO NOT EDIT.

from dataclasses import dataclass
from typing import TYPE_CHECKING, TypedDict

from databricks.bundles.core._transform import _transform
from databricks.bundles.core._transform_to_json import _transform_to_json_value
from databricks.bundles.core._variable import VariableOrOptional

if TYPE_CHECKING:
    from typing_extensions import Self


@dataclass(kw_only=True)
class SawtoothWindow:
    """
    :meta private: [EXPERIMENTAL]

    A sawtooth window served via the hybrid batch + streaming path. The batch pipeline maintains
    daily partial aggregates for the bulk of the window while the streaming pipeline maintains the
    most recent day(s), and serving merges them on read. Same field shape as RollingWindow, but a
    distinct type so the control plane can explicitly identify hybrid (sawtooth) features rather
    than inferring hybrid behavior from window_duration.
    """

    delay: VariableOrOptional[str] = None
    """
    :meta private: [EXPERIMENTAL]
    
    [Private Preview] Delay is not currently supported for Sawtooth windows.
    """

    window_duration: VariableOrOptional[str] = None
    """
    :meta private: [EXPERIMENTAL]
    
    [Private Preview] The duration of the window. Must be positive and span more than two days when set, so that both
    the batch (N-1 day) and stale-path (N-2 day) partial aggregates are well defined. The duration
    need not be a whole number of days (e.g. 3 days 15 minutes is allowed). Absent means lifetime
    (aggregate over the entity's entire history).
    """

    @classmethod
    def from_dict(cls, value: "SawtoothWindowDict") -> "Self":
        return _transform(cls, value)

    def as_dict(self) -> "SawtoothWindowDict":
        return _transform_to_json_value(self)  # type:ignore


class SawtoothWindowDict(TypedDict, total=False):
    """"""

    delay: VariableOrOptional[str]
    """
    :meta private: [EXPERIMENTAL]
    
    [Private Preview] Delay is not currently supported for Sawtooth windows.
    """

    window_duration: VariableOrOptional[str]
    """
    :meta private: [EXPERIMENTAL]
    
    [Private Preview] The duration of the window. Must be positive and span more than two days when set, so that both
    the batch (N-1 day) and stale-path (N-2 day) partial aggregates are well defined. The duration
    need not be a whole number of days (e.g. 3 days 15 minutes is allowed). Absent means lifetime
    (aggregate over the entity's entire history).
    """


SawtoothWindowParam = SawtoothWindowDict | SawtoothWindow
