# Code generated by pydabs-codegen. DO NOT EDIT.

from dataclasses import dataclass
from typing import TYPE_CHECKING, TypedDict

from databricks.bundles.core._transform import _transform
from databricks.bundles.core._transform_to_json import _transform_to_json_value
from databricks.bundles.core._variable import VariableOr, VariableOrOptional

if TYPE_CHECKING:
    from typing_extensions import Self


@dataclass(kw_only=True)
class SlidingWindow:
    """
    :meta private: [EXPERIMENTAL]
    """

    slide_duration: VariableOr[str]
    """
    :meta private: [EXPERIMENTAL]
    
    [Private Preview] The slide duration (interval by which windows advance, must be positive and less than duration).
    """

    delay: VariableOrOptional[str] = None
    """
    :meta private: [EXPERIMENTAL]
    
    [Private Preview] Non-negative analytic lag that evaluates the window this far in the past. Use this for timing
    variations unrelated to source lateness, such as a 30-day count as of one week ago. If unset,
    the analytic lag is zero. It composes with source.lateness when both are set.
    """

    offset: VariableOrOptional[str] = None
    """
    :meta private: [EXPERIMENTAL]
    
    [Private Preview] Non-negative phase shift from the default midnight UTC alignment. For example, offset=22h on
    a 24h slide produces boundaries at 22:00 UTC (17:00 New York in standard time) instead of
    midnight UTC. If unset, the offset is zero. Must be shorter than slide_duration (and therefore
    window_duration).
    """

    window_duration: VariableOrOptional[str] = None
    """
    :meta private: [EXPERIMENTAL]
    
    [Private Preview] The duration of the sliding window. Must be positive when set; absent means lifetime
    (aggregate over the entity's entire history).
    """

    @classmethod
    def from_dict(cls, value: "SlidingWindowDict") -> "Self":
        return _transform(cls, value)

    def as_dict(self) -> "SlidingWindowDict":
        return _transform_to_json_value(self)  # type:ignore


class SlidingWindowDict(TypedDict, total=False):
    """"""

    slide_duration: VariableOr[str]
    """
    :meta private: [EXPERIMENTAL]
    
    [Private Preview] The slide duration (interval by which windows advance, must be positive and less than duration).
    """

    delay: VariableOrOptional[str]
    """
    :meta private: [EXPERIMENTAL]
    
    [Private Preview] Non-negative analytic lag that evaluates the window this far in the past. Use this for timing
    variations unrelated to source lateness, such as a 30-day count as of one week ago. If unset,
    the analytic lag is zero. It composes with source.lateness when both are set.
    """

    offset: VariableOrOptional[str]
    """
    :meta private: [EXPERIMENTAL]
    
    [Private Preview] Non-negative phase shift from the default midnight UTC alignment. For example, offset=22h on
    a 24h slide produces boundaries at 22:00 UTC (17:00 New York in standard time) instead of
    midnight UTC. If unset, the offset is zero. Must be shorter than slide_duration (and therefore
    window_duration).
    """

    window_duration: VariableOrOptional[str]
    """
    :meta private: [EXPERIMENTAL]
    
    [Private Preview] The duration of the sliding window. Must be positive when set; absent means lifetime
    (aggregate over the entity's entire history).
    """


SlidingWindowParam = SlidingWindowDict | SlidingWindow
