# Code generated by pydabs-codegen. DO NOT EDIT.

from dataclasses import dataclass
from typing import TYPE_CHECKING, TypedDict

from databricks.bundles.core._transform import _transform
from databricks.bundles.core._transform_to_json import _transform_to_json_value
from databricks.bundles.core._variable import VariableOr, VariableOrOptional

if TYPE_CHECKING:
    from typing_extensions import Self


@dataclass(kw_only=True)
class StreamSource:
    """
    :meta private: [EXPERIMENTAL]

    A Stream entity used as a data source for a feature.
    """

    full_name: VariableOr[str]
    """
    :meta private: [EXPERIMENTAL]
    
    [Private Preview] Three-part full name of the Stream (catalog.schema.stream).
    """

    dataframe_schema: VariableOrOptional[str] = None
    """
    :meta private: [EXPERIMENTAL]
    
    [Private Preview] Schema of the resulting dataframe after transformations, in Spark StructType
    JSON format (from df.schema.json()).
    Any subsequent functions operate against this dataframe.
    """

    filter_condition: VariableOrOptional[str] = None
    """
    :meta private: [EXPERIMENTAL]
    
    [Private Preview] The filter condition applied to the source data before aggregation.
    """

    transformation_sql: VariableOrOptional[str] = None
    """
    :meta private: [EXPERIMENTAL]
    
    [Private Preview] The pipeline runs these SQL statements immediately after conversion into
    the schema specified on the Stream object.
    """

    @classmethod
    def from_dict(cls, value: "StreamSourceDict") -> "Self":
        return _transform(cls, value)

    def as_dict(self) -> "StreamSourceDict":
        return _transform_to_json_value(self)  # type:ignore


class StreamSourceDict(TypedDict, total=False):
    """"""

    full_name: VariableOr[str]
    """
    :meta private: [EXPERIMENTAL]
    
    [Private Preview] Three-part full name of the Stream (catalog.schema.stream).
    """

    dataframe_schema: VariableOrOptional[str]
    """
    :meta private: [EXPERIMENTAL]
    
    [Private Preview] Schema of the resulting dataframe after transformations, in Spark StructType
    JSON format (from df.schema.json()).
    Any subsequent functions operate against this dataframe.
    """

    filter_condition: VariableOrOptional[str]
    """
    :meta private: [EXPERIMENTAL]
    
    [Private Preview] The filter condition applied to the source data before aggregation.
    """

    transformation_sql: VariableOrOptional[str]
    """
    :meta private: [EXPERIMENTAL]
    
    [Private Preview] The pipeline runs these SQL statements immediately after conversion into
    the schema specified on the Stream object.
    """


StreamSourceParam = StreamSourceDict | StreamSource
