# Code generated by pydabs-codegen. DO NOT EDIT.

from dataclasses import dataclass
from typing import TYPE_CHECKING, TypedDict

from databricks.bundles.core._transform import _transform
from databricks.bundles.core._transform_to_json import _transform_to_json_value
from databricks.bundles.core._variable import VariableOr

if TYPE_CHECKING:
    from typing_extensions import Self


@dataclass(kw_only=True)
class TimeseriesColumn:
    """
    :meta private: [EXPERIMENTAL]
    """

    name: VariableOr[str]
    """
    :meta private: [EXPERIMENTAL]
    
    [Private Preview] The name of the timeseries column. For Kafka sources, use dot-prefixed path notation to
    reference fields within the key or value schema (e.g., "value.event_timestamp"). For nested
    fields, the leaf node name (e.g., "event_timestamp" from "value.event_details.event_timestamp")
    is what will be present in materialized tables and expected to match at query time.
    Colon-prefixed notation (e.g., "value:event_timestamp") is supported for
    backwards compatibility but is deprecated; migrate to dot notation.
    """

    @classmethod
    def from_dict(cls, value: "TimeseriesColumnDict") -> "Self":
        return _transform(cls, value)

    def as_dict(self) -> "TimeseriesColumnDict":
        return _transform_to_json_value(self)  # type:ignore


class TimeseriesColumnDict(TypedDict, total=False):
    """"""

    name: VariableOr[str]
    """
    :meta private: [EXPERIMENTAL]
    
    [Private Preview] The name of the timeseries column. For Kafka sources, use dot-prefixed path notation to
    reference fields within the key or value schema (e.g., "value.event_timestamp"). For nested
    fields, the leaf node name (e.g., "event_timestamp" from "value.event_details.event_timestamp")
    is what will be present in materialized tables and expected to match at query time.
    Colon-prefixed notation (e.g., "value:event_timestamp") is supported for
    backwards compatibility but is deprecated; migrate to dot notation.
    """


TimeseriesColumnParam = TimeseriesColumnDict | TimeseriesColumn
