# Code generated by pydabs-codegen. DO NOT EDIT.

from dataclasses import dataclass
from typing import TYPE_CHECKING, TypedDict

from databricks.bundles.core._transform import _transform
from databricks.bundles.core._transform_to_json import _transform_to_json_value
from databricks.bundles.core._variable import VariableOr

if TYPE_CHECKING:
    from typing_extensions import Self


@dataclass(kw_only=True)
class VarPopFunction:
    """
    :meta private: [EXPERIMENTAL]

    Computes the population variance.
    """

    input: VariableOr[str]
    """
    :meta private: [EXPERIMENTAL]
    
    [Private Preview] The input column from which the population variance is computed.
    """

    @classmethod
    def from_dict(cls, value: "VarPopFunctionDict") -> "Self":
        return _transform(cls, value)

    def as_dict(self) -> "VarPopFunctionDict":
        return _transform_to_json_value(self)  # type:ignore


class VarPopFunctionDict(TypedDict, total=False):
    """"""

    input: VariableOr[str]
    """
    :meta private: [EXPERIMENTAL]
    
    [Private Preview] The input column from which the population variance is computed.
    """


VarPopFunctionParam = VarPopFunctionDict | VarPopFunction
