#!/bin/bash

touch dummy.whl
$CLI bundle deploy
pipeline_id="$(read_id.py my_pipeline)"


title "Add and modify pipeline configuration"
edit_resource.py pipelines $pipeline_id <<EOF
r["configuration"]["key1"] = "new_value"
r["configuration"]["key2"] = "value2"
EOF

title "Detect and save changes"
$CLI bundle config-remote-sync --save

title "Updated configuration"
echo
cat databricks.yml
