Local = true
Cloud = false
EnvMatrix.DATABRICKS_BUNDLE_ENGINE = ["terraform", "direct"]
EnvMatrix.INCLUDE_JOB = ["yes", "no"]
EnvMatrix.INCLUDE_PIPELINE = ["yes", "no"]
EnvMatrix.INCLUDE_PYTHON = ["yes", "no"]
EnvMatrix.SERVERLESS = ["yes", "no"]
