# Code generated by pydabs-codegen. DO NOT EDIT.

from dataclasses import dataclass
from typing import TYPE_CHECKING, TypedDict

from databricks.bundles.core._transform import _transform
from databricks.bundles.core._transform_to_json import _transform_to_json_value
from databricks.bundles.core._variable import VariableOr, VariableOrOptional

if TYPE_CHECKING:
    from typing_extensions import Self


@dataclass(kw_only=True)
class AppEnvVar:
    """"""

    name: VariableOr[str]

    value: VariableOrOptional[str] = None

    value_from: VariableOrOptional[str] = None

    @classmethod
    def from_dict(cls, value: "AppEnvVarDict") -> "Self":
        return _transform(cls, value)

    def as_dict(self) -> "AppEnvVarDict":
        return _transform_to_json_value(self)  # type:ignore


class AppEnvVarDict(TypedDict, total=False):
    """"""

    name: VariableOr[str]

    value: VariableOrOptional[str]

    value_from: VariableOrOptional[str]


AppEnvVarParam = AppEnvVarDict | AppEnvVar
