# Code generated by pydabs-codegen. DO NOT EDIT.

from dataclasses import dataclass
from typing import TYPE_CHECKING, TypedDict

from databricks.bundles.apps._models.app_resource_job_job_permission import (
    AppResourceJobJobPermission,
    AppResourceJobJobPermissionParam,
)
from databricks.bundles.core._transform import _transform
from databricks.bundles.core._transform_to_json import _transform_to_json_value
from databricks.bundles.core._variable import VariableOr

if TYPE_CHECKING:
    from typing_extensions import Self


@dataclass(kw_only=True)
class AppResourceJob:
    """"""

    id: VariableOr[str]
    """
    Id of the job to grant permission on.
    """

    permission: VariableOr[AppResourceJobJobPermission]
    """
    Permissions to grant on the Job. Supported permissions are: "CAN_MANAGE", "IS_OWNER", "CAN_MANAGE_RUN", "CAN_VIEW".
    """

    @classmethod
    def from_dict(cls, value: "AppResourceJobDict") -> "Self":
        return _transform(cls, value)

    def as_dict(self) -> "AppResourceJobDict":
        return _transform_to_json_value(self)  # type:ignore


class AppResourceJobDict(TypedDict, total=False):
    """"""

    id: VariableOr[str]
    """
    Id of the job to grant permission on.
    """

    permission: VariableOr[AppResourceJobJobPermissionParam]
    """
    Permissions to grant on the Job. Supported permissions are: "CAN_MANAGE", "IS_OWNER", "CAN_MANAGE_RUN", "CAN_VIEW".
    """


AppResourceJobParam = AppResourceJobDict | AppResourceJob
