# Code generated by pydabs-codegen. DO NOT EDIT.

from dataclasses import dataclass
from typing import TYPE_CHECKING, TypedDict

from databricks.bundles.apps._models.app_resource_app_app_permission import (
    AppResourceAppAppPermission,
    AppResourceAppAppPermissionParam,
)
from databricks.bundles.core._transform import _transform
from databricks.bundles.core._transform_to_json import _transform_to_json_value
from databricks.bundles.core._variable import VariableOrOptional

if TYPE_CHECKING:
    from typing_extensions import Self


@dataclass(kw_only=True)
class AppResourceApp:
    """"""

    name: VariableOrOptional[str] = None

    permission: VariableOrOptional[AppResourceAppAppPermission] = None

    @classmethod
    def from_dict(cls, value: "AppResourceAppDict") -> "Self":
        return _transform(cls, value)

    def as_dict(self) -> "AppResourceAppDict":
        return _transform_to_json_value(self)  # type:ignore


class AppResourceAppDict(TypedDict, total=False):
    """"""

    name: VariableOrOptional[str]

    permission: VariableOrOptional[AppResourceAppAppPermissionParam]


AppResourceAppParam = AppResourceAppDict | AppResourceApp
