# Code generated by pydabs-codegen. DO NOT EDIT.

from dataclasses import dataclass
from typing import TYPE_CHECKING, TypedDict

from databricks.bundles.core._transform import _transform
from databricks.bundles.core._transform_to_json import _transform_to_json_value
from databricks.bundles.core._variable import VariableOr, VariableOrOptional

if TYPE_CHECKING:
    from typing_extensions import Self


@dataclass(kw_only=True)
class GitRepository:
    """
    Git repository configuration specifying the location of the repository.
    """

    provider: VariableOr[str]
    """
    Git provider. Case insensitive. Supported values: gitHub, gitHubEnterprise, bitbucketCloud,
    bitbucketServer, azureDevOpsServices, gitLab, gitLabEnterpriseEdition, awsCodeCommit.
    """

    url: VariableOr[str]
    """
    URL of the Git repository.
    """

    auto_deploy: VariableOrOptional[bool] = None
    """
    :meta private: [EXPERIMENTAL]
    
    [Beta] When true, automatically deploys the app on push events to the branch configured in
    the app's deployment_source.git_source.
    """

    caller_credential_id: VariableOrOptional[int] = None
    """
    :meta private: [EXPERIMENTAL]
    
    [Beta] ID of a personal access token Git credential owned by the caller, used to
    grant the app's service principal access to this repository.
    """

    @classmethod
    def from_dict(cls, value: "GitRepositoryDict") -> "Self":
        return _transform(cls, value)

    def as_dict(self) -> "GitRepositoryDict":
        return _transform_to_json_value(self)  # type:ignore


class GitRepositoryDict(TypedDict, total=False):
    """"""

    provider: VariableOr[str]
    """
    Git provider. Case insensitive. Supported values: gitHub, gitHubEnterprise, bitbucketCloud,
    bitbucketServer, azureDevOpsServices, gitLab, gitLabEnterpriseEdition, awsCodeCommit.
    """

    url: VariableOr[str]
    """
    URL of the Git repository.
    """

    auto_deploy: VariableOrOptional[bool]
    """
    :meta private: [EXPERIMENTAL]
    
    [Beta] When true, automatically deploys the app on push events to the branch configured in
    the app's deployment_source.git_source.
    """

    caller_credential_id: VariableOrOptional[int]
    """
    :meta private: [EXPERIMENTAL]
    
    [Beta] ID of a personal access token Git credential owned by the caller, used to
    grant the app's service principal access to this repository.
    """


GitRepositoryParam = GitRepositoryDict | GitRepository
