#!/bin/bash

touch dummy.whl
$CLI bundle deploy
pipeline_id="$(read_id.py my_pipeline)"

title "Modify pipeline catalog from main to staging"
edit_resource.py pipelines $pipeline_id <<EOF
r["catalog"] = "staging"
r["schema"] = "new_schema"
EOF

title "Detect and save changes"
echo
cp databricks.yml databricks.yml.backup
$CLI bundle config-remote-sync --save

title "Configuration changes"
echo
diff -u databricks.yml.backup databricks.yml || true
