#!/bin/bash

touch dummy.whl
$CLI bundle deploy
pipeline_id="$(read_id.py my_pipeline)"

title "Modify pipeline catalog from main to staging"
edit_resource.py pipelines $pipeline_id <<EOF
r["catalog"] = "staging"
r["schema"] = "new_schema"
EOF

title "Detect and save changes"
$CLI bundle config-remote-sync --save

title "Updated configuration"
echo
cat databricks.yml
