#!/bin/bash

touch dummy.whl
$CLI bundle deploy
pipeline_id="$(read_id.py my_pipeline)"


title "Add failure notification"
edit_resource.py pipelines $pipeline_id <<EOF
r["notifications"][0]["email_recipients"].append("failure@example.com")
r["notifications"][0]["alerts"].append("on-update-failure")
EOF

title "Detect and save changes"
echo
cp databricks.yml databricks.yml.backup
$CLI bundle config-remote-sync --save

title "Configuration changes"
echo
diff -u databricks.yml.backup databricks.yml || true
rm databricks.yml.backup
