# Code generated by pydabs-codegen. DO NOT EDIT.

from databricks_tests.core._generated import (
    alerts,
    catalogs,
    jobs,
    pipelines,
    schemas,
    volumes,
)

__all__ = ["test_cases"]

test_cases = [
    alerts._test_case(),
    catalogs._test_case(),
    jobs._test_case(),
    pipelines._test_case(),
    schemas._test_case(),
    volumes._test_case(),
]
