# Code generated by pydabs-codegen. DO NOT EDIT.

from databricks.bundles.core import Resources, dashboard_mutator
from databricks.bundles.core._generated.dashboards import _resource_type
from databricks.bundles.dashboards._models.dashboard import Dashboard
from databricks.bundles.dashboards._models.lifecycle import Lifecycle
from databricks.bundles.dashboards._models.lifecycle_state import LifecycleState
from databricks.bundles.dashboards._models.permission import Permission
from databricks.bundles.dashboards._models.permission_level import PermissionLevel
from databricks_tests.core._resource_test_case import ResourceTestCase


def _test_case():
    return (
        ResourceTestCase(
            add_resource=Resources.add_dashboard,
            dict_example={
                "lifecycle": {},
                "lifecycle_state": "ACTIVE",
                "permissions": [{"level": "CAN_MANAGE"}],
            },
            dataclass_example=Dashboard(
                lifecycle=Lifecycle(),
                lifecycle_state=LifecycleState.ACTIVE,
                permissions=[Permission(level=PermissionLevel.CAN_MANAGE)],
            ),
            mutator=dashboard_mutator,
        ),
        _resource_type(),
    )
