# Code generated by pydabs-codegen. DO NOT EDIT.

from databricks.bundles.core import Resources, database_catalog_mutator
from databricks.bundles.core._generated.database_catalogs import _resource_type
from databricks.bundles.database_catalogs._models.database_catalog import (
    DatabaseCatalog,
)
from databricks.bundles.database_catalogs._models.lifecycle import Lifecycle
from databricks_tests.core._resource_test_case import TestCase


def _test_case():
    return (
        TestCase(
            add_resource=Resources.add_database_catalog,
            dict_example={
                "database_instance_name": "database_instance_name",
                "database_name": "database_name",
                "lifecycle": {},
                "name": "name",
            },
            dataclass_example=DatabaseCatalog(
                database_instance_name="database_instance_name",
                database_name="database_name",
                lifecycle=Lifecycle(),
                name="name",
            ),
            mutator=database_catalog_mutator,
        ),
        _resource_type(),
    )
