# Code generated by pydabs-codegen. DO NOT EDIT.

from databricks.bundles.core import Resources, instance_pool_mutator
from databricks.bundles.core._generated.instance_pools import _resource_type
from databricks.bundles.instance_pools._models.disk_spec import DiskSpec
from databricks.bundles.instance_pools._models.docker_image import DockerImage
from databricks.bundles.instance_pools._models.instance_pool import InstancePool
from databricks.bundles.instance_pools._models.instance_pool_aws_attributes import (
    InstancePoolAwsAttributes,
)
from databricks.bundles.instance_pools._models.instance_pool_azure_attributes import (
    InstancePoolAzureAttributes,
)
from databricks.bundles.instance_pools._models.instance_pool_gcp_attributes import (
    InstancePoolGcpAttributes,
)
from databricks.bundles.instance_pools._models.instance_pool_permission import (
    InstancePoolPermission,
)
from databricks.bundles.instance_pools._models.instance_pool_permission_level import (
    InstancePoolPermissionLevel,
)
from databricks.bundles.instance_pools._models.lifecycle import Lifecycle
from databricks.bundles.instance_pools._models.node_type_flexibility import (
    NodeTypeFlexibility,
)
from databricks_tests.core._resource_test_case import TestCase


def _test_case():
    return (
        TestCase(
            add_resource=Resources.add_instance_pool,
            dict_example={
                "aws_attributes": {},
                "azure_attributes": {},
                "custom_tags": {"key": "value"},
                "disk_spec": {},
                "gcp_attributes": {},
                "instance_pool_name": "instance_pool_name",
                "lifecycle": {},
                "node_type_flexibility": {},
                "node_type_id": "node_type_id",
                "permissions": [{"level": "CAN_MANAGE"}],
                "preloaded_docker_images": [{}],
                "preloaded_spark_versions": ["preloaded_spark_versions"],
            },
            dataclass_example=InstancePool(
                aws_attributes=InstancePoolAwsAttributes(),
                azure_attributes=InstancePoolAzureAttributes(),
                custom_tags={"key": "value"},
                disk_spec=DiskSpec(),
                gcp_attributes=InstancePoolGcpAttributes(),
                instance_pool_name="instance_pool_name",
                lifecycle=Lifecycle(),
                node_type_flexibility=NodeTypeFlexibility(),
                node_type_id="node_type_id",
                permissions=[
                    InstancePoolPermission(level=InstancePoolPermissionLevel.CAN_MANAGE)
                ],
                preloaded_docker_images=[DockerImage()],
                preloaded_spark_versions=["preloaded_spark_versions"],
            ),
            mutator=instance_pool_mutator,
        ),
        _resource_type(),
    )
