# Code generated by pydabs-codegen. DO NOT EDIT.

from databricks.bundles.core import Resources, model_serving_endpoint_mutator
from databricks.bundles.core._generated.model_serving_endpoints import _resource_type
from databricks.bundles.model_serving_endpoints._models.ai_gateway_config import (
    AiGatewayConfig,
)
from databricks.bundles.model_serving_endpoints._models.email_notifications import (
    EmailNotifications,
)
from databricks.bundles.model_serving_endpoints._models.endpoint_core_config_input import (
    EndpointCoreConfigInput,
)
from databricks.bundles.model_serving_endpoints._models.endpoint_tag import EndpointTag
from databricks.bundles.model_serving_endpoints._models.lifecycle import Lifecycle
from databricks.bundles.model_serving_endpoints._models.model_serving_endpoint import (
    ModelServingEndpoint,
)
from databricks.bundles.model_serving_endpoints._models.model_serving_endpoint_permission import (
    ModelServingEndpointPermission,
)
from databricks.bundles.model_serving_endpoints._models.serving_endpoint_permission_level import (
    ServingEndpointPermissionLevel,
)
from databricks.bundles.model_serving_endpoints._models.telemetry_config import (
    TelemetryConfig,
)
from databricks_tests.core._resource_test_case import TestCase


def _test_case():
    return (
        TestCase(
            add_resource=Resources.add_model_serving_endpoint,
            dict_example={
                "ai_gateway": {},
                "config": {},
                "email_notifications": {},
                "lifecycle": {},
                "name": "name",
                "permissions": [{"level": "CAN_MANAGE"}],
                "tags": [{"key": "key"}],
                "telemetry_config": {},
            },
            dataclass_example=ModelServingEndpoint(
                ai_gateway=AiGatewayConfig(),
                config=EndpointCoreConfigInput(),
                email_notifications=EmailNotifications(),
                lifecycle=Lifecycle(),
                name="name",
                permissions=[
                    ModelServingEndpointPermission(
                        level=ServingEndpointPermissionLevel.CAN_MANAGE
                    )
                ],
                tags=[EndpointTag(key="key")],
                telemetry_config=TelemetryConfig(),
            ),
            mutator=model_serving_endpoint_mutator,
        ),
        _resource_type(),
    )
