# Code generated by pydabs-codegen. DO NOT EDIT.

from databricks.bundles.core import Resources, pipeline_mutator
from databricks.bundles.core._generated.pipelines import _resource_type
from databricks.bundles.pipelines._models.event_log_spec import EventLogSpec
from databricks.bundles.pipelines._models.filters import Filters
from databricks.bundles.pipelines._models.ingestion_pipeline_definition import (
    IngestionPipelineDefinition,
)
from databricks.bundles.pipelines._models.lifecycle import Lifecycle
from databricks.bundles.pipelines._models.notifications import Notifications
from databricks.bundles.pipelines._models.pipeline import Pipeline
from databricks.bundles.pipelines._models.pipeline_cluster import PipelineCluster
from databricks.bundles.pipelines._models.pipeline_library import PipelineLibrary
from databricks.bundles.pipelines._models.pipeline_permission import PipelinePermission
from databricks.bundles.pipelines._models.pipeline_permission_level import (
    PipelinePermissionLevel,
)
from databricks.bundles.pipelines._models.pipelines_environment import (
    PipelinesEnvironment,
)
from databricks.bundles.pipelines._models.run_as import RunAs
from databricks_tests.core._resource_test_case import TestCase


def _test_case():
    return (
        TestCase(
            add_resource=Resources.add_pipeline,
            dict_example={
                "clusters": [{}],
                "configuration": {"key": "value"},
                "environment": {},
                "event_log": {},
                "filters": {},
                "ingestion_definition": {},
                "libraries": [{}],
                "lifecycle": {},
                "notifications": [{}],
                "parameters": {"key": "value"},
                "permissions": [{"level": "CAN_MANAGE"}],
                "run_as": {},
                "tags": {"key": "value"},
            },
            dataclass_example=Pipeline(
                clusters=[PipelineCluster()],
                configuration={"key": "value"},
                environment=PipelinesEnvironment(),
                event_log=EventLogSpec(),
                filters=Filters(),
                ingestion_definition=IngestionPipelineDefinition(),
                libraries=[PipelineLibrary()],
                lifecycle=Lifecycle(),
                notifications=[Notifications()],
                parameters={"key": "value"},
                permissions=[
                    PipelinePermission(level=PipelinePermissionLevel.CAN_MANAGE)
                ],
                run_as=RunAs(),
                tags={"key": "value"},
            ),
            mutator=pipeline_mutator,
        ),
        _resource_type(),
    )
