# Code generated by pydabs-codegen. DO NOT EDIT.

from databricks.bundles.core import Resources, postgres_snapshot_schedule_mutator
from databricks.bundles.core._generated.postgres_snapshot_schedules import (
    _resource_type,
)
from databricks.bundles.postgres_snapshot_schedules._models.lifecycle import Lifecycle
from databricks.bundles.postgres_snapshot_schedules._models.postgres_snapshot_schedule import (
    PostgresSnapshotSchedule,
)
from databricks.bundles.postgres_snapshot_schedules._models.schedule_cadence import (
    ScheduleCadence,
)
from databricks_tests.core._resource_test_case import TestCase


def _test_case():
    return (
        TestCase(
            add_resource=Resources.add_postgres_snapshot_schedule,
            dict_example={
                "branch": "branch",
                "lifecycle": {},
                "schedule": [{"retention": "3600s"}],
            },
            dataclass_example=PostgresSnapshotSchedule(
                branch="branch",
                lifecycle=Lifecycle(),
                schedule=[ScheduleCadence(retention="3600s")],
            ),
            mutator=postgres_snapshot_schedule_mutator,
        ),
        _resource_type(),
    )
