# Code generated by pydabs-codegen. DO NOT EDIT.

from databricks.bundles.core import Resources, quality_monitor_mutator
from databricks.bundles.core._generated.quality_monitors import _resource_type
from databricks.bundles.quality_monitors._models.lifecycle import Lifecycle
from databricks.bundles.quality_monitors._models.monitor_cron_schedule import (
    MonitorCronSchedule,
)
from databricks.bundles.quality_monitors._models.monitor_inference_log import (
    MonitorInferenceLog,
)
from databricks.bundles.quality_monitors._models.monitor_inference_log_problem_type import (
    MonitorInferenceLogProblemType,
)
from databricks.bundles.quality_monitors._models.monitor_metric import MonitorMetric
from databricks.bundles.quality_monitors._models.monitor_metric_type import (
    MonitorMetricType,
)
from databricks.bundles.quality_monitors._models.monitor_notifications import (
    MonitorNotifications,
)
from databricks.bundles.quality_monitors._models.monitor_snapshot import MonitorSnapshot
from databricks.bundles.quality_monitors._models.monitor_time_series import (
    MonitorTimeSeries,
)
from databricks.bundles.quality_monitors._models.quality_monitor import QualityMonitor
from databricks_tests.core._resource_test_case import TestCase


def _test_case():
    return (
        TestCase(
            add_resource=Resources.add_quality_monitor,
            dict_example={
                "assets_dir": "assets_dir",
                "custom_metrics": [
                    {
                        "definition": "definition",
                        "input_columns": ["input_columns"],
                        "name": "name",
                        "output_data_type": "output_data_type",
                        "type": "CUSTOM_METRIC_TYPE_AGGREGATE",
                    }
                ],
                "inference_log": {
                    "granularities": ["granularities"],
                    "model_id_col": "model_id_col",
                    "prediction_col": "prediction_col",
                    "problem_type": "PROBLEM_TYPE_CLASSIFICATION",
                    "timestamp_col": "timestamp_col",
                },
                "lifecycle": {},
                "notifications": {},
                "output_schema_name": "output_schema_name",
                "schedule": {
                    "quartz_cron_expression": "quartz_cron_expression",
                    "timezone_id": "timezone_id",
                },
                "slicing_exprs": ["slicing_exprs"],
                "snapshot": {},
                "table_name": "table_name",
                "time_series": {
                    "granularities": ["granularities"],
                    "timestamp_col": "timestamp_col",
                },
            },
            dataclass_example=QualityMonitor(
                assets_dir="assets_dir",
                custom_metrics=[
                    MonitorMetric(
                        definition="definition",
                        input_columns=["input_columns"],
                        name="name",
                        output_data_type="output_data_type",
                        type=MonitorMetricType.CUSTOM_METRIC_TYPE_AGGREGATE,
                    )
                ],
                inference_log=MonitorInferenceLog(
                    granularities=["granularities"],
                    model_id_col="model_id_col",
                    prediction_col="prediction_col",
                    problem_type=MonitorInferenceLogProblemType.PROBLEM_TYPE_CLASSIFICATION,
                    timestamp_col="timestamp_col",
                ),
                lifecycle=Lifecycle(),
                notifications=MonitorNotifications(),
                output_schema_name="output_schema_name",
                schedule=MonitorCronSchedule(
                    quartz_cron_expression="quartz_cron_expression",
                    timezone_id="timezone_id",
                ),
                slicing_exprs=["slicing_exprs"],
                snapshot=MonitorSnapshot(),
                table_name="table_name",
                time_series=MonitorTimeSeries(
                    granularities=["granularities"], timestamp_col="timestamp_col"
                ),
            ),
            mutator=quality_monitor_mutator,
        ),
        _resource_type(),
    )
