# Code generated by pydabs-codegen. DO NOT EDIT.

from databricks.bundles.core import Resources, secret_scope_mutator
from databricks.bundles.core._generated.secret_scopes import _resource_type
from databricks.bundles.secret_scopes._models.azure_key_vault_secret_scope_metadata import (
    AzureKeyVaultSecretScopeMetadata,
)
from databricks.bundles.secret_scopes._models.lifecycle import Lifecycle
from databricks.bundles.secret_scopes._models.scope_backend_type import ScopeBackendType
from databricks.bundles.secret_scopes._models.secret_scope import SecretScope
from databricks.bundles.secret_scopes._models.secret_scope_permission import (
    SecretScopePermission,
)
from databricks.bundles.secret_scopes._models.secret_scope_permission_level import (
    SecretScopePermissionLevel,
)
from databricks_tests.core._resource_test_case import TestCase


def _test_case():
    return (
        TestCase(
            add_resource=Resources.add_secret_scope,
            dict_example={
                "backend_type": "DATABRICKS",
                "keyvault_metadata": {
                    "dns_name": "dns_name",
                    "resource_id": "resource_id",
                },
                "lifecycle": {},
                "name": "name",
                "permissions": [{"level": "READ"}],
            },
            dataclass_example=SecretScope(
                backend_type=ScopeBackendType.DATABRICKS,
                keyvault_metadata=AzureKeyVaultSecretScopeMetadata(
                    dns_name="dns_name", resource_id="resource_id"
                ),
                lifecycle=Lifecycle(),
                name="name",
                permissions=[
                    SecretScopePermission(level=SecretScopePermissionLevel.READ)
                ],
            ),
            mutator=secret_scope_mutator,
        ),
        _resource_type(),
    )
