# Code generated by pydabs-codegen. DO NOT EDIT.

from databricks.bundles.core import Resources, sql_warehouse_mutator
from databricks.bundles.core._generated.sql_warehouses import _resource_type
from databricks.bundles.sql_warehouses._models.channel import Channel
from databricks.bundles.sql_warehouses._models.create_warehouse_request_warehouse_type import (
    CreateWarehouseRequestWarehouseType,
)
from databricks.bundles.sql_warehouses._models.endpoint_tags import EndpointTags
from databricks.bundles.sql_warehouses._models.lifecycle_with_started import (
    LifecycleWithStarted,
)
from databricks.bundles.sql_warehouses._models.spot_instance_policy import (
    SpotInstancePolicy,
)
from databricks.bundles.sql_warehouses._models.sql_warehouse import SqlWarehouse
from databricks.bundles.sql_warehouses._models.sql_warehouse_permission import (
    SqlWarehousePermission,
)
from databricks.bundles.sql_warehouses._models.warehouse_permission_level import (
    WarehousePermissionLevel,
)
from databricks_tests.core._resource_test_case import TestCase


def _test_case():
    return (
        TestCase(
            add_resource=Resources.add_sql_warehouse,
            dict_example={
                "channel": {},
                "lifecycle": {},
                "permissions": [{"level": "CAN_MANAGE"}],
                "spot_instance_policy": "POLICY_UNSPECIFIED",
                "tags": {},
                "warehouse_type": "TYPE_UNSPECIFIED",
            },
            dataclass_example=SqlWarehouse(
                channel=Channel(),
                lifecycle=LifecycleWithStarted(),
                permissions=[
                    SqlWarehousePermission(level=WarehousePermissionLevel.CAN_MANAGE)
                ],
                spot_instance_policy=SpotInstancePolicy.POLICY_UNSPECIFIED,
                tags=EndpointTags(),
                warehouse_type=CreateWarehouseRequestWarehouseType.TYPE_UNSPECIFIED,
            ),
            mutator=sql_warehouse_mutator,
        ),
        _resource_type(),
    )
