# Code generated by pydabs-codegen. DO NOT EDIT.

from databricks.bundles.core import Resources, vector_search_index_mutator
from databricks.bundles.core._generated.vector_search_indexes import _resource_type
from databricks.bundles.vector_search_indexes._models.delta_sync_vector_index_spec_request import (
    DeltaSyncVectorIndexSpecRequest,
)
from databricks.bundles.vector_search_indexes._models.direct_access_vector_index_spec import (
    DirectAccessVectorIndexSpec,
)
from databricks.bundles.vector_search_indexes._models.lifecycle import Lifecycle
from databricks.bundles.vector_search_indexes._models.privilege_assignment import (
    PrivilegeAssignment,
)
from databricks.bundles.vector_search_indexes._models.vector_index_type import (
    VectorIndexType,
)
from databricks.bundles.vector_search_indexes._models.vector_search_index import (
    VectorSearchIndex,
)
from databricks_tests.core._resource_test_case import TestCase


def _test_case():
    return (
        TestCase(
            add_resource=Resources.add_vector_search_index,
            dict_example={
                "delta_sync_index_spec": {},
                "direct_access_index_spec": {},
                "endpoint_name": "endpoint_name",
                "grants": [{}],
                "index_type": "DELTA_SYNC",
                "lifecycle": {},
                "name": "name",
                "primary_key": "primary_key",
            },
            dataclass_example=VectorSearchIndex(
                delta_sync_index_spec=DeltaSyncVectorIndexSpecRequest(),
                direct_access_index_spec=DirectAccessVectorIndexSpec(),
                endpoint_name="endpoint_name",
                grants=[PrivilegeAssignment()],
                index_type=VectorIndexType.DELTA_SYNC,
                lifecycle=Lifecycle(),
                name="name",
                primary_key="primary_key",
            ),
            mutator=vector_search_index_mutator,
        ),
        _resource_type(),
    )
