# Code generated by pydabs-codegen. DO NOT EDIT.

from dataclasses import dataclass
from typing import TYPE_CHECKING, TypedDict

from databricks.bundles.core._transform import _transform
from databricks.bundles.core._transform_to_json import _transform_to_json_value
from databricks.bundles.core._variable import VariableOr, VariableOrOptional

if TYPE_CHECKING:
    from typing_extensions import Self


@dataclass(kw_only=True)
class MonthlySchedule:
    """
    :meta private: [EXPERIMENTAL]

    Take a snapshot once per month, on the configured day at the configured hour.
    """

    day: VariableOr[int]
    """
    :meta private: [EXPERIMENTAL]
    
    [Private Preview] The day of the month on which to take the snapshot, in [1, 31]. In shorter
    months the snapshot is taken on the last day instead (day 31 runs on Feb 28
    or 29, and on Apr 30), so every month gets exactly one snapshot.
    """

    hour: VariableOrOptional[int] = None
    """
    :meta private: [EXPERIMENTAL]
    
    [Private Preview] The hour of the day, in UTC, at which to take the snapshot, in [0, 23].
    """

    @classmethod
    def from_dict(cls, value: "MonthlyScheduleDict") -> "Self":
        return _transform(cls, value)

    def as_dict(self) -> "MonthlyScheduleDict":
        return _transform_to_json_value(self)  # type:ignore


class MonthlyScheduleDict(TypedDict, total=False):
    """"""

    day: VariableOr[int]
    """
    :meta private: [EXPERIMENTAL]
    
    [Private Preview] The day of the month on which to take the snapshot, in [1, 31]. In shorter
    months the snapshot is taken on the last day instead (day 31 runs on Feb 28
    or 29, and on Apr 30), so every month gets exactly one snapshot.
    """

    hour: VariableOrOptional[int]
    """
    :meta private: [EXPERIMENTAL]
    
    [Private Preview] The hour of the day, in UTC, at which to take the snapshot, in [0, 23].
    """


MonthlyScheduleParam = MonthlyScheduleDict | MonthlySchedule
