# Code generated by pydabs-codegen. DO NOT EDIT.

from dataclasses import dataclass
from typing import TYPE_CHECKING, TypedDict

from databricks.bundles.core._transform import _transform
from databricks.bundles.core._transform_to_json import _transform_to_json_value
from databricks.bundles.core._variable import VariableOr, VariableOrOptional
from databricks.bundles.postgres_snapshot_schedules._models.day_of_week import (
    DayOfWeek,
    DayOfWeekParam,
)

if TYPE_CHECKING:
    from typing_extensions import Self


@dataclass(kw_only=True)
class WeeklySchedule:
    """
    :meta private: [EXPERIMENTAL]

    Take a snapshot once per week, on the configured day at the configured hour.
    """

    day_of_week: VariableOr[DayOfWeek]
    """
    :meta private: [EXPERIMENTAL]
    
    [Private Preview] The day of the week on which to take the snapshot.
    """

    hour: VariableOrOptional[int] = None
    """
    :meta private: [EXPERIMENTAL]
    
    [Private Preview] The hour of the day, in UTC, at which to take the snapshot, in [0, 23].
    """

    @classmethod
    def from_dict(cls, value: "WeeklyScheduleDict") -> "Self":
        return _transform(cls, value)

    def as_dict(self) -> "WeeklyScheduleDict":
        return _transform_to_json_value(self)  # type:ignore


class WeeklyScheduleDict(TypedDict, total=False):
    """"""

    day_of_week: VariableOr[DayOfWeekParam]
    """
    :meta private: [EXPERIMENTAL]
    
    [Private Preview] The day of the week on which to take the snapshot.
    """

    hour: VariableOrOptional[int]
    """
    :meta private: [EXPERIMENTAL]
    
    [Private Preview] The hour of the day, in UTC, at which to take the snapshot, in [0, 23].
    """


WeeklyScheduleParam = WeeklyScheduleDict | WeeklySchedule
