#!/bin/bash

touch dummy.whl
$CLI bundle deploy
pipeline_id="$(read_id.py my_pipeline)"

title "Modify pipeline target (schema) from my_schema to new_schema"
edit_resource.py pipelines $pipeline_id <<EOF
r["target"] = "new_schema"
EOF

title "Detect and save changes"
$CLI bundle config-remote-sync --save

title "Updated configuration"
echo
cat databricks.yml
