version: "2"
linters:
  default: none
  enable:
    - bodyclose
    - errcheck
    - gocritic
    - govet
    - ineffassign
    - intrange
    - mirror
    - perfsprint
    - revive
    - staticcheck
    - testifylint
    - unconvert
    - unused
    - copyloopvar
  settings:
    gocritic:
      disabled-checks:
        - ruleguard
