# Code generated by pydabs-codegen. DO NOT EDIT.

from dataclasses import dataclass, field
from typing import TYPE_CHECKING, TypedDict

from databricks.bundles.core._transform import _transform
from databricks.bundles.core._transform_to_json import _transform_to_json_value
from databricks.bundles.core._variable import (
    VariableOrDict,
    VariableOrList,
    VariableOrOptional,
)
from databricks.bundles.jobs._models.alert_task_subscriber import (
    AlertTaskSubscriber,
    AlertTaskSubscriberParam,
)

if TYPE_CHECKING:
    from typing_extensions import Self


@dataclass(kw_only=True)
class AlertTask:
    """"""

    alert_id: VariableOrOptional[str] = None
    """
    [Public Preview] The alert_id is the canonical identifier of the alert.
    """

    parameters: VariableOrDict[str] = field(default_factory=dict)
    """
    :meta private: [EXPERIMENTAL]
    
    [Private Preview] Per-run parameter overrides, keyed by parameter name, applied onto the alert's stored
    query parameters before the query is executed. Only scalar values are supported. Values
    may reference job parameters with `{{job.parameters.*}}`, which are resolved before the
    task runs. An override whose key does not match a stored parameter fails the task run.
    Limited to 10000 characters when serialized as JSON; keys must be 1-100 characters and
    contain only letters, digits, underscores, dashes, and periods.
    """

    subscribers: VariableOrList[AlertTaskSubscriber] = field(default_factory=list)
    """
    [Public Preview] The subscribers receive alert evaluation result notifications after the alert task is completed.
    The number of subscriptions is limited to 100.
    """

    warehouse_id: VariableOrOptional[str] = None
    """
    [Public Preview] The warehouse_id identifies the warehouse settings used by the alert task.
    """

    workspace_path: VariableOrOptional[str] = None
    """
    [Public Preview] The workspace_path is the path to the alert file in the workspace. The path:
    * must start with "/Workspace"
    * must be a normalized path.
    User has to select only one of alert_id or workspace_path to identify the alert.
    """

    @classmethod
    def from_dict(cls, value: "AlertTaskDict") -> "Self":
        return _transform(cls, value)

    def as_dict(self) -> "AlertTaskDict":
        return _transform_to_json_value(self)  # type:ignore


class AlertTaskDict(TypedDict, total=False):
    """"""

    alert_id: VariableOrOptional[str]
    """
    [Public Preview] The alert_id is the canonical identifier of the alert.
    """

    parameters: VariableOrDict[str]
    """
    :meta private: [EXPERIMENTAL]
    
    [Private Preview] Per-run parameter overrides, keyed by parameter name, applied onto the alert's stored
    query parameters before the query is executed. Only scalar values are supported. Values
    may reference job parameters with `{{job.parameters.*}}`, which are resolved before the
    task runs. An override whose key does not match a stored parameter fails the task run.
    Limited to 10000 characters when serialized as JSON; keys must be 1-100 characters and
    contain only letters, digits, underscores, dashes, and periods.
    """

    subscribers: VariableOrList[AlertTaskSubscriberParam]
    """
    [Public Preview] The subscribers receive alert evaluation result notifications after the alert task is completed.
    The number of subscriptions is limited to 100.
    """

    warehouse_id: VariableOrOptional[str]
    """
    [Public Preview] The warehouse_id identifies the warehouse settings used by the alert task.
    """

    workspace_path: VariableOrOptional[str]
    """
    [Public Preview] The workspace_path is the path to the alert file in the workspace. The path:
    * must start with "/Workspace"
    * must be a normalized path.
    User has to select only one of alert_id or workspace_path to identify the alert.
    """


AlertTaskParam = AlertTaskDict | AlertTask
