# Code generated by pydabs-codegen. DO NOT EDIT.

from dataclasses import dataclass
from typing import TYPE_CHECKING, TypedDict

from databricks.bundles.core._transform import _transform
from databricks.bundles.core._transform_to_json import _transform_to_json_value
from databricks.bundles.core._variable import VariableOr, VariableOrOptional
from databricks.bundles.jobs._models.sql_condition_trigger_mode import (
    SqlConditionTriggerMode,
    SqlConditionTriggerModeParam,
)

if TYPE_CHECKING:
    from typing_extensions import Self


@dataclass(kw_only=True)
class SqlConditionConfiguration:
    """
    :meta private: [EXPERIMENTAL]
    """

    sql_query_id: VariableOr[str]
    """
    :meta private: [EXPERIMENTAL]
    
    [Private Preview] The ID of the SQL query to evaluate as the trigger condition.
    """

    warehouse_id: VariableOr[str]
    """
    :meta private: [EXPERIMENTAL]
    
    [Private Preview] The canonical identifier of the SQL warehouse to run the condition query against.
    """

    trigger_mode: VariableOrOptional[SqlConditionTriggerMode] = None
    """
    :meta private: [EXPERIMENTAL]
    
    [Private Preview] Determines how the SQL query result is interpreted to decide whether the condition fires.
    Must be set to a recognized value when provided.
    When unset on an existing serialized configuration, the server preserves the original
    semantics by interpreting it as `QUERY_RETURNS_ROWS`. New configurations should set this
    explicitly — explicit `SQL_CONDITION_TRIGGER_MODE_UNSPECIFIED` is rejected at validation.
    """

    @classmethod
    def from_dict(cls, value: "SqlConditionConfigurationDict") -> "Self":
        return _transform(cls, value)

    def as_dict(self) -> "SqlConditionConfigurationDict":
        return _transform_to_json_value(self)  # type:ignore


class SqlConditionConfigurationDict(TypedDict, total=False):
    """"""

    sql_query_id: VariableOr[str]
    """
    :meta private: [EXPERIMENTAL]
    
    [Private Preview] The ID of the SQL query to evaluate as the trigger condition.
    """

    warehouse_id: VariableOr[str]
    """
    :meta private: [EXPERIMENTAL]
    
    [Private Preview] The canonical identifier of the SQL warehouse to run the condition query against.
    """

    trigger_mode: VariableOrOptional[SqlConditionTriggerModeParam]
    """
    :meta private: [EXPERIMENTAL]
    
    [Private Preview] Determines how the SQL query result is interpreted to decide whether the condition fires.
    Must be set to a recognized value when provided.
    When unset on an existing serialized configuration, the server preserves the original
    semantics by interpreting it as `QUERY_RETURNS_ROWS`. New configurations should set this
    explicitly — explicit `SQL_CONDITION_TRIGGER_MODE_UNSPECIFIED` is rejected at validation.
    """


SqlConditionConfigurationParam = (
    SqlConditionConfigurationDict | SqlConditionConfiguration
)
