# Code generated by pydabs-codegen. DO NOT EDIT.

from dataclasses import dataclass
from typing import TYPE_CHECKING, TypedDict

from databricks.bundles.core._transform import _transform
from databricks.bundles.core._transform_to_json import _transform_to_json_value
from databricks.bundles.core._variable import VariableOrOptional
from databricks.bundles.jobs._models.file_arrival_trigger_configuration import (
    FileArrivalTriggerConfiguration,
    FileArrivalTriggerConfigurationParam,
)
from databricks.bundles.jobs._models.model_trigger_configuration import (
    ModelTriggerConfiguration,
    ModelTriggerConfigurationParam,
)
from databricks.bundles.jobs._models.pause_status import PauseStatus, PauseStatusParam
from databricks.bundles.jobs._models.periodic_trigger_configuration import (
    PeriodicTriggerConfiguration,
    PeriodicTriggerConfigurationParam,
)
from databricks.bundles.jobs._models.sql_condition_configuration import (
    SqlConditionConfiguration,
    SqlConditionConfigurationParam,
)
from databricks.bundles.jobs._models.table_update_trigger_configuration import (
    TableUpdateTriggerConfiguration,
    TableUpdateTriggerConfigurationParam,
)

if TYPE_CHECKING:
    from typing_extensions import Self


@dataclass(kw_only=True)
class TriggerSettings:
    """"""

    file_arrival: VariableOrOptional[FileArrivalTriggerConfiguration] = None
    """
    File arrival trigger settings.
    """

    model: VariableOrOptional[ModelTriggerConfiguration] = None
    """
    :meta private: [EXPERIMENTAL]
    
    [Private Preview]
    """

    pause_status: VariableOrOptional[PauseStatus] = None
    """
    Whether this trigger is paused or not.
    """

    periodic: VariableOrOptional[PeriodicTriggerConfiguration] = None
    """
    Periodic trigger settings.
    """

    sql_condition: VariableOrOptional[SqlConditionConfiguration] = None
    """
    :meta private: [EXPERIMENTAL]
    
    [Private Preview] SQL condition that must be satisfied for the trigger to fire. Can be used in combination with other trigger types and
    runs *after* other trigger types conditions are evaluated.
    """

    table_update: VariableOrOptional[TableUpdateTriggerConfiguration] = None

    @classmethod
    def from_dict(cls, value: "TriggerSettingsDict") -> "Self":
        return _transform(cls, value)

    def as_dict(self) -> "TriggerSettingsDict":
        return _transform_to_json_value(self)  # type:ignore


class TriggerSettingsDict(TypedDict, total=False):
    """"""

    file_arrival: VariableOrOptional[FileArrivalTriggerConfigurationParam]
    """
    File arrival trigger settings.
    """

    model: VariableOrOptional[ModelTriggerConfigurationParam]
    """
    :meta private: [EXPERIMENTAL]
    
    [Private Preview]
    """

    pause_status: VariableOrOptional[PauseStatusParam]
    """
    Whether this trigger is paused or not.
    """

    periodic: VariableOrOptional[PeriodicTriggerConfigurationParam]
    """
    Periodic trigger settings.
    """

    sql_condition: VariableOrOptional[SqlConditionConfigurationParam]
    """
    :meta private: [EXPERIMENTAL]
    
    [Private Preview] SQL condition that must be satisfied for the trigger to fire. Can be used in combination with other trigger types and
    runs *after* other trigger types conditions are evaluated.
    """

    table_update: VariableOrOptional[TableUpdateTriggerConfigurationParam]


TriggerSettingsParam = TriggerSettingsDict | TriggerSettings
