#!/bin/bash

envsubst < databricks.yml.tmpl > databricks.yml

cleanup() {
  trace $CLI bundle destroy --auto-approve
}
trap cleanup EXIT

touch dummy.whl
$CLI bundle deploy
job_id="$(read_id.py test_job)"

edit_resource.py jobs $job_id <<EOF
r["max_concurrent_runs"] = 3
# Add tag without replacing the map — dev mode auto-adds a "dev" tag and we
# don't want the diff to show that as removed.
r.setdefault("tags", {})["env"] = "test"
EOF

title "JSON output format"
$CLI bundle config-remote-sync -o json > tmp.json
cat tmp.json
