# Code generated by pydabs-codegen. DO NOT EDIT.

from dataclasses import dataclass, field
from typing import TYPE_CHECKING, TypedDict

from databricks.bundles.core._resource import Resource
from databricks.bundles.core._transform import _transform
from databricks.bundles.core._transform_to_json import _transform_to_json_value
from databricks.bundles.core._variable import (
    VariableOr,
    VariableOrList,
    VariableOrOptional,
)
from databricks.bundles.secret_scopes._models.azure_key_vault_secret_scope_metadata import (
    AzureKeyVaultSecretScopeMetadata,
    AzureKeyVaultSecretScopeMetadataParam,
)
from databricks.bundles.secret_scopes._models.lifecycle import Lifecycle, LifecycleParam
from databricks.bundles.secret_scopes._models.scope_backend_type import (
    ScopeBackendType,
    ScopeBackendTypeParam,
)
from databricks.bundles.secret_scopes._models.secret_scope_permission import (
    SecretScopePermission,
    SecretScopePermissionParam,
)

if TYPE_CHECKING:
    from typing_extensions import Self


@dataclass(kw_only=True)
class SecretScope(Resource):
    """"""

    name: VariableOr[str]
    """
    Scope name requested by the user. Scope names are unique.
    """

    backend_type: VariableOrOptional[ScopeBackendType] = None
    """
    The backend type the scope will be created with. If not specified, will default to `DATABRICKS`
    """

    keyvault_metadata: VariableOrOptional[AzureKeyVaultSecretScopeMetadata] = None
    """
    The metadata for the secret scope if the `backend_type` is `AZURE_KEYVAULT`
    """

    lifecycle: VariableOrOptional[Lifecycle] = None
    """
    Settings that control the deployment lifecycle of the resource, such as preventing it from being destroyed.
    """

    permissions: VariableOrList[SecretScopePermission] = field(default_factory=list)
    """
    The permissions to apply to the secret scope. Permissions are managed via secret scope ACLs.
    """

    @classmethod
    def from_dict(cls, value: "SecretScopeDict") -> "Self":
        return _transform(cls, value)

    def as_dict(self) -> "SecretScopeDict":
        return _transform_to_json_value(self)  # type:ignore


class SecretScopeDict(TypedDict, total=False):
    """"""

    name: VariableOr[str]
    """
    Scope name requested by the user. Scope names are unique.
    """

    backend_type: VariableOrOptional[ScopeBackendTypeParam]
    """
    The backend type the scope will be created with. If not specified, will default to `DATABRICKS`
    """

    keyvault_metadata: VariableOrOptional[AzureKeyVaultSecretScopeMetadataParam]
    """
    The metadata for the secret scope if the `backend_type` is `AZURE_KEYVAULT`
    """

    lifecycle: VariableOrOptional[LifecycleParam]
    """
    Settings that control the deployment lifecycle of the resource, such as preventing it from being destroyed.
    """

    permissions: VariableOrList[SecretScopePermissionParam]
    """
    The permissions to apply to the secret scope. Permissions are managed via secret scope ACLs.
    """


SecretScopeParam = SecretScopeDict | SecretScope
