Cloud = false # tests don't interact with APIs

# job_runs are only supported in the current version of the wheel
EnvMatrix.PYDAB_VERSION = ["current"]

# job_runs are only supported on the direct deployment engine
EnvMatrix.DATABRICKS_BUNDLE_ENGINE = ["direct"]
