#!/bin/bash

touch dummy.whl
$CLI bundle deploy

job_one_id="$(read_id.py job_one)"
job_two_id="$(read_id.py job_two)"


title "Modify both jobs"
edit_resource.py jobs $job_one_id <<EOF
r["max_concurrent_runs"] = 5
r["tags"] = {"team": "data"}
EOF

edit_resource.py jobs $job_two_id <<EOF
r["max_concurrent_runs"] = 10
r["tags"] = {"team": "ml"}
EOF

title "Detect and save changes"
echo
cp databricks.yml databricks.yml.backup
$CLI bundle config-remote-sync --save

title "Configuration changes"
echo
file_diff databricks.yml.backup databricks.yml
rm databricks.yml.backup
