# Code generated by pydabs-codegen. DO NOT EDIT.

from dataclasses import dataclass
from typing import TYPE_CHECKING, TypedDict

from databricks.bundles.core._transform import _transform
from databricks.bundles.core._transform_to_json import _transform_to_json_value
from databricks.bundles.core._variable import VariableOrOptional
from databricks.bundles.pipelines._models.parse_mode import ParseMode, ParseModeParam
from databricks.bundles.pipelines._models.schema_registry_config import (
    SchemaRegistryConfig,
    SchemaRegistryConfigParam,
)

if TYPE_CHECKING:
    from typing_extensions import Self


@dataclass(kw_only=True)
class AvroTransformerOptions:
    """
    :meta private: [EXPERIMENTAL]
    """

    parse_mode: VariableOrOptional[ParseMode] = None
    """
    :meta private: [EXPERIMENTAL]
    
    [Private Preview] (Optional) Parse mode for Avro data.
    Valid values: FAILFAST, PERMISSIVE. Defaults to FAILFAST.
    """

    schema: VariableOrOptional[str] = None
    """
    :meta private: [EXPERIMENTAL]
    
    [Private Preview] Inline Avro JSON schema string.
    """

    schema_file_path: VariableOrOptional[str] = None
    """
    :meta private: [EXPERIMENTAL]
    
    [Private Preview] Path to a schema file (.avsc).
    """

    schema_registry: VariableOrOptional[SchemaRegistryConfig] = None
    """
    :meta private: [EXPERIMENTAL]
    
    [Private Preview] (Optional) Schema registry to resolve the Avro schema at runtime instead of
    providing it inline or via a file path.
    """

    @classmethod
    def from_dict(cls, value: "AvroTransformerOptionsDict") -> "Self":
        return _transform(cls, value)

    def as_dict(self) -> "AvroTransformerOptionsDict":
        return _transform_to_json_value(self)  # type:ignore


class AvroTransformerOptionsDict(TypedDict, total=False):
    """"""

    parse_mode: VariableOrOptional[ParseModeParam]
    """
    :meta private: [EXPERIMENTAL]
    
    [Private Preview] (Optional) Parse mode for Avro data.
    Valid values: FAILFAST, PERMISSIVE. Defaults to FAILFAST.
    """

    schema: VariableOrOptional[str]
    """
    :meta private: [EXPERIMENTAL]
    
    [Private Preview] Inline Avro JSON schema string.
    """

    schema_file_path: VariableOrOptional[str]
    """
    :meta private: [EXPERIMENTAL]
    
    [Private Preview] Path to a schema file (.avsc).
    """

    schema_registry: VariableOrOptional[SchemaRegistryConfigParam]
    """
    :meta private: [EXPERIMENTAL]
    
    [Private Preview] (Optional) Schema registry to resolve the Avro schema at runtime instead of
    providing it inline or via a file path.
    """


AvroTransformerOptionsParam = AvroTransformerOptionsDict | AvroTransformerOptions
