# Code generated by pydabs-codegen. DO NOT EDIT.

from dataclasses import dataclass, field
from typing import TYPE_CHECKING, TypedDict

from databricks.bundles.core._transform import _transform
from databricks.bundles.core._transform_to_json import _transform_to_json_value
from databricks.bundles.core._variable import VariableOrList, VariableOrOptional

if TYPE_CHECKING:
    from typing_extensions import Self


@dataclass(kw_only=True)
class MetaMarketingOptionsMetaMarketingCustomReportOptions:
    """
    :meta private: [EXPERIMENTAL]

    Defines the shape of a single Meta Ads custom report (one /insights call shape).
    start_date, custom_insights_lookback_window live on MetaMarketingOptions, not here.
    Metrics are not customer-selectable; the connector returns a fixed standard metric set.
    """

    action_attribution_windows: VariableOrList[str] = field(default_factory=list)
    """
    :meta private: [EXPERIMENTAL]
    
    [Private Preview] (Optional) Action attribution windows for insights reporting (e.g. "28d_click", "1d_view")
    """

    action_breakdowns: VariableOrList[str] = field(default_factory=list)
    """
    :meta private: [EXPERIMENTAL]
    
    [Private Preview] (Optional) Action breakdowns to configure for data aggregation
    """

    action_report_time: VariableOrOptional[str] = None
    """
    :meta private: [EXPERIMENTAL]
    
    [Private Preview] (Optional) Timing used to report action statistics (impression, conversion, mixed, or lifetime)
    """

    breakdowns: VariableOrList[str] = field(default_factory=list)
    """
    :meta private: [EXPERIMENTAL]
    
    [Private Preview] (Optional) Breakdowns to configure for data aggregation
    """

    level: VariableOrOptional[str] = None
    """
    :meta private: [EXPERIMENTAL]
    
    [Private Preview] (Optional) Granularity of data to pull (account, ad, adset, campaign)
    """

    time_increment: VariableOrOptional[str] = None
    """
    :meta private: [EXPERIMENTAL]
    
    [Private Preview] (Optional) Value in string by which to aggregate statistics (all_days, monthly or number of days)
    """

    @classmethod
    def from_dict(
        cls, value: "MetaMarketingOptionsMetaMarketingCustomReportOptionsDict"
    ) -> "Self":
        return _transform(cls, value)

    def as_dict(self) -> "MetaMarketingOptionsMetaMarketingCustomReportOptionsDict":
        return _transform_to_json_value(self)  # type:ignore


class MetaMarketingOptionsMetaMarketingCustomReportOptionsDict(TypedDict, total=False):
    """"""

    action_attribution_windows: VariableOrList[str]
    """
    :meta private: [EXPERIMENTAL]
    
    [Private Preview] (Optional) Action attribution windows for insights reporting (e.g. "28d_click", "1d_view")
    """

    action_breakdowns: VariableOrList[str]
    """
    :meta private: [EXPERIMENTAL]
    
    [Private Preview] (Optional) Action breakdowns to configure for data aggregation
    """

    action_report_time: VariableOrOptional[str]
    """
    :meta private: [EXPERIMENTAL]
    
    [Private Preview] (Optional) Timing used to report action statistics (impression, conversion, mixed, or lifetime)
    """

    breakdowns: VariableOrList[str]
    """
    :meta private: [EXPERIMENTAL]
    
    [Private Preview] (Optional) Breakdowns to configure for data aggregation
    """

    level: VariableOrOptional[str]
    """
    :meta private: [EXPERIMENTAL]
    
    [Private Preview] (Optional) Granularity of data to pull (account, ad, adset, campaign)
    """

    time_increment: VariableOrOptional[str]
    """
    :meta private: [EXPERIMENTAL]
    
    [Private Preview] (Optional) Value in string by which to aggregate statistics (all_days, monthly or number of days)
    """


MetaMarketingOptionsMetaMarketingCustomReportOptionsParam = (
    MetaMarketingOptionsMetaMarketingCustomReportOptionsDict
    | MetaMarketingOptionsMetaMarketingCustomReportOptions
)
