# Code generated by pydabs-codegen. DO NOT EDIT.

from dataclasses import dataclass
from typing import TYPE_CHECKING, TypedDict

from databricks.bundles.core._transform import _transform
from databricks.bundles.core._transform_to_json import _transform_to_json_value
from databricks.bundles.core._variable import VariableOrOptional
from databricks.bundles.pipelines._models.parse_mode import ParseMode, ParseModeParam
from databricks.bundles.pipelines._models.schema_registry_config import (
    SchemaRegistryConfig,
    SchemaRegistryConfigParam,
)

if TYPE_CHECKING:
    from typing_extensions import Self


@dataclass(kw_only=True)
class ProtobufTransformerOptions:
    """
    :meta private: [EXPERIMENTAL]
    """

    desc_file_path: VariableOrOptional[str] = None
    """
    :meta private: [EXPERIMENTAL]
    
    [Private Preview] Required: path to the .desc file (dbfs:/... or /Volumes/...).
    """

    message_name: VariableOrOptional[str] = None
    """
    :meta private: [EXPERIMENTAL]
    
    [Private Preview] Required: fully-qualified message type name.
    """

    parse_mode: VariableOrOptional[ParseMode] = None
    """
    :meta private: [EXPERIMENTAL]
    
    [Private Preview] (Optional) Parse mode for Protobuf data.
    Valid values: FAILFAST, PERMISSIVE. Defaults to FAILFAST.
    """

    recursive_fields_max_depth: VariableOrOptional[int] = None
    """
    :meta private: [EXPERIMENTAL]
    
    [Private Preview] (Optional) Maximum expansion depth for recursive protobuf fields.
    Spark SQL does not natively support recursive types, so recursive
    fields are expanded up to this depth and truncated beyond it.
    Valid values: -1 (disallow recursive fields), 0 (drop), 1-10.
    """

    schema_registry: VariableOrOptional[SchemaRegistryConfig] = None
    """
    :meta private: [EXPERIMENTAL]
    
    [Private Preview] (Optional) Schema registry to resolve the Protobuf schema at runtime instead
    of providing it via desc_file_path.
    """

    @classmethod
    def from_dict(cls, value: "ProtobufTransformerOptionsDict") -> "Self":
        return _transform(cls, value)

    def as_dict(self) -> "ProtobufTransformerOptionsDict":
        return _transform_to_json_value(self)  # type:ignore


class ProtobufTransformerOptionsDict(TypedDict, total=False):
    """"""

    desc_file_path: VariableOrOptional[str]
    """
    :meta private: [EXPERIMENTAL]
    
    [Private Preview] Required: path to the .desc file (dbfs:/... or /Volumes/...).
    """

    message_name: VariableOrOptional[str]
    """
    :meta private: [EXPERIMENTAL]
    
    [Private Preview] Required: fully-qualified message type name.
    """

    parse_mode: VariableOrOptional[ParseModeParam]
    """
    :meta private: [EXPERIMENTAL]
    
    [Private Preview] (Optional) Parse mode for Protobuf data.
    Valid values: FAILFAST, PERMISSIVE. Defaults to FAILFAST.
    """

    recursive_fields_max_depth: VariableOrOptional[int]
    """
    :meta private: [EXPERIMENTAL]
    
    [Private Preview] (Optional) Maximum expansion depth for recursive protobuf fields.
    Spark SQL does not natively support recursive types, so recursive
    fields are expanded up to this depth and truncated beyond it.
    Valid values: -1 (disallow recursive fields), 0 (drop), 1-10.
    """

    schema_registry: VariableOrOptional[SchemaRegistryConfigParam]
    """
    :meta private: [EXPERIMENTAL]
    
    [Private Preview] (Optional) Schema registry to resolve the Protobuf schema at runtime instead
    of providing it via desc_file_path.
    """


ProtobufTransformerOptionsParam = (
    ProtobufTransformerOptionsDict | ProtobufTransformerOptions
)
