# Code generated by pydabs-codegen. DO NOT EDIT.

from dataclasses import dataclass
from typing import TYPE_CHECKING, TypedDict

from databricks.bundles.core._transform import _transform
from databricks.bundles.core._transform_to_json import _transform_to_json_value
from databricks.bundles.core._variable import VariableOrOptional
from databricks.bundles.pipelines._models.reddit_ads_options_reddit_ads_custom_report_options import (
    RedditAdsOptionsRedditAdsCustomReportOptions,
    RedditAdsOptionsRedditAdsCustomReportOptionsParam,
)

if TYPE_CHECKING:
    from typing_extensions import Self


@dataclass(kw_only=True)
class RedditAdsOptions:
    """
    :meta private: [EXPERIMENTAL]

    Reddit Ads specific options for ingestion
    """

    custom_report_options: VariableOrOptional[
        RedditAdsOptionsRedditAdsCustomReportOptions
    ] = None
    """
    :meta private: [EXPERIMENTAL]
    
    [Private Preview] (Optional) Custom report definition. When set, the table is treated as a
    user-defined Reddit Ads custom report. When unset, the table must match
    one of the connector's prebuilt sources.
    """

    lookback_window_days: VariableOrOptional[int] = None
    """
    :meta private: [EXPERIMENTAL]
    
    [Private Preview] (Optional) Number of days to look back for report tables during incremental sync
    to capture late-arriving conversions and attribution data.
    If not specified, defaults to 30 days.
    """

    sync_start_date: VariableOrOptional[str] = None
    """
    :meta private: [EXPERIMENTAL]
    
    [Private Preview] (Optional) Start date for the initial sync of report tables in YYYY-MM-DD format.
    This determines the earliest date from which to sync historical data.
    If not specified, defaults to 2 years ago.
    """

    @classmethod
    def from_dict(cls, value: "RedditAdsOptionsDict") -> "Self":
        return _transform(cls, value)

    def as_dict(self) -> "RedditAdsOptionsDict":
        return _transform_to_json_value(self)  # type:ignore


class RedditAdsOptionsDict(TypedDict, total=False):
    """"""

    custom_report_options: VariableOrOptional[
        RedditAdsOptionsRedditAdsCustomReportOptionsParam
    ]
    """
    :meta private: [EXPERIMENTAL]
    
    [Private Preview] (Optional) Custom report definition. When set, the table is treated as a
    user-defined Reddit Ads custom report. When unset, the table must match
    one of the connector's prebuilt sources.
    """

    lookback_window_days: VariableOrOptional[int]
    """
    :meta private: [EXPERIMENTAL]
    
    [Private Preview] (Optional) Number of days to look back for report tables during incremental sync
    to capture late-arriving conversions and attribution data.
    If not specified, defaults to 30 days.
    """

    sync_start_date: VariableOrOptional[str]
    """
    :meta private: [EXPERIMENTAL]
    
    [Private Preview] (Optional) Start date for the initial sync of report tables in YYYY-MM-DD format.
    This determines the earliest date from which to sync historical data.
    If not specified, defaults to 2 years ago.
    """


RedditAdsOptionsParam = RedditAdsOptionsDict | RedditAdsOptions
