# Code generated by pydabs-codegen. DO NOT EDIT.

from dataclasses import dataclass
from typing import TYPE_CHECKING, TypedDict

from databricks.bundles.core._transform import _transform
from databricks.bundles.core._transform_to_json import _transform_to_json_value
from databricks.bundles.core._variable import VariableOrOptional
from databricks.bundles.pipelines._models.confluent_schema_registry_options import (
    ConfluentSchemaRegistryOptions,
    ConfluentSchemaRegistryOptionsParam,
)

if TYPE_CHECKING:
    from typing_extensions import Self


@dataclass(kw_only=True)
class SchemaRegistryConfig:
    """
    :meta private: [EXPERIMENTAL]
    """

    confluent_options: VariableOrOptional[ConfluentSchemaRegistryOptions] = None
    """
    :meta private: [EXPERIMENTAL]
    
    [Private Preview] Required: Confluent-compatible schema registry options.
    """

    connection_name: VariableOrOptional[str] = None
    """
    :meta private: [EXPERIMENTAL]
    
    [Private Preview] (Optional) UC connection for registry authentication.
    Specify if different from the top-level source connection.
    """

    protobuf_message_name: VariableOrOptional[str] = None
    """
    :meta private: [EXPERIMENTAL]
    
    [Private Preview] (Optional, Protobuf only) Selects a specific message from a schema that
    defines multiple Protobuf messages. Simple ("Location") or fully-qualified
    ("com.example.protos.Location"). Defaults to the first message.
    """

    @classmethod
    def from_dict(cls, value: "SchemaRegistryConfigDict") -> "Self":
        return _transform(cls, value)

    def as_dict(self) -> "SchemaRegistryConfigDict":
        return _transform_to_json_value(self)  # type:ignore


class SchemaRegistryConfigDict(TypedDict, total=False):
    """"""

    confluent_options: VariableOrOptional[ConfluentSchemaRegistryOptionsParam]
    """
    :meta private: [EXPERIMENTAL]
    
    [Private Preview] Required: Confluent-compatible schema registry options.
    """

    connection_name: VariableOrOptional[str]
    """
    :meta private: [EXPERIMENTAL]
    
    [Private Preview] (Optional) UC connection for registry authentication.
    Specify if different from the top-level source connection.
    """

    protobuf_message_name: VariableOrOptional[str]
    """
    :meta private: [EXPERIMENTAL]
    
    [Private Preview] (Optional, Protobuf only) Selects a specific message from a schema that
    defines multiple Protobuf messages. Simple ("Location") or fully-qualified
    ("com.example.protos.Location"). Defaults to the first message.
    """


SchemaRegistryConfigParam = SchemaRegistryConfigDict | SchemaRegistryConfig
