# Code generated by pydabs-codegen. DO NOT EDIT.

from dataclasses import dataclass, field
from typing import TYPE_CHECKING, TypedDict

from databricks.bundles.core._transform import _transform
from databricks.bundles.core._transform_to_json import _transform_to_json_value
from databricks.bundles.core._variable import VariableOrList, VariableOrOptional
from databricks.bundles.pipelines._models.tik_tok_ads_options_tik_tok_data_level import (
    TikTokAdsOptionsTikTokDataLevel,
    TikTokAdsOptionsTikTokDataLevelParam,
)
from databricks.bundles.pipelines._models.tik_tok_ads_options_tik_tok_report_type import (
    TikTokAdsOptionsTikTokReportType,
    TikTokAdsOptionsTikTokReportTypeParam,
)

if TYPE_CHECKING:
    from typing_extensions import Self


@dataclass(kw_only=True)
class TikTokAdsOptionsTikTokAdsCustomReportOptions:
    """
    :meta private: [EXPERIMENTAL]

    User-defined custom report for the TikTok Ads connector. Groups the
    dimensions + metrics + report type + data level that define a TikTok Ads
    custom report request.
    """

    data_level: VariableOrOptional[TikTokAdsOptionsTikTokDataLevel] = None
    """
    :meta private: [EXPERIMENTAL]
    
    [Private Preview] (Optional) Data level for the report.
    If not specified, defaults to AUCTION_CAMPAIGN.
    """

    dimensions: VariableOrList[str] = field(default_factory=list)
    """
    :meta private: [EXPERIMENTAL]
    
    [Private Preview] (Optional) Dimensions to include in the report (e.g. "campaign_id",
    "adgroup_id", "ad_id", "stat_time_day", "stat_time_hour").
    """

    metrics: VariableOrList[str] = field(default_factory=list)
    """
    :meta private: [EXPERIMENTAL]
    
    [Private Preview] (Optional) Metrics to include in the report (e.g. "spend", "impressions",
    "clicks", "conversion", "cpc").
    """

    query_lifetime: VariableOrOptional[bool] = None
    """
    :meta private: [EXPERIMENTAL]
    
    [Private Preview] (Optional) Whether to request lifetime metrics (all-time aggregated data).
    When true, the report returns all-time data.
    If not specified, defaults to false.
    """

    report_type: VariableOrOptional[TikTokAdsOptionsTikTokReportType] = None
    """
    :meta private: [EXPERIMENTAL]
    
    [Private Preview] (Optional) Report type for the TikTok Ads API.
    If not specified, defaults to BASIC.
    """

    @classmethod
    def from_dict(
        cls, value: "TikTokAdsOptionsTikTokAdsCustomReportOptionsDict"
    ) -> "Self":
        return _transform(cls, value)

    def as_dict(self) -> "TikTokAdsOptionsTikTokAdsCustomReportOptionsDict":
        return _transform_to_json_value(self)  # type:ignore


class TikTokAdsOptionsTikTokAdsCustomReportOptionsDict(TypedDict, total=False):
    """"""

    data_level: VariableOrOptional[TikTokAdsOptionsTikTokDataLevelParam]
    """
    :meta private: [EXPERIMENTAL]
    
    [Private Preview] (Optional) Data level for the report.
    If not specified, defaults to AUCTION_CAMPAIGN.
    """

    dimensions: VariableOrList[str]
    """
    :meta private: [EXPERIMENTAL]
    
    [Private Preview] (Optional) Dimensions to include in the report (e.g. "campaign_id",
    "adgroup_id", "ad_id", "stat_time_day", "stat_time_hour").
    """

    metrics: VariableOrList[str]
    """
    :meta private: [EXPERIMENTAL]
    
    [Private Preview] (Optional) Metrics to include in the report (e.g. "spend", "impressions",
    "clicks", "conversion", "cpc").
    """

    query_lifetime: VariableOrOptional[bool]
    """
    :meta private: [EXPERIMENTAL]
    
    [Private Preview] (Optional) Whether to request lifetime metrics (all-time aggregated data).
    When true, the report returns all-time data.
    If not specified, defaults to false.
    """

    report_type: VariableOrOptional[TikTokAdsOptionsTikTokReportTypeParam]
    """
    :meta private: [EXPERIMENTAL]
    
    [Private Preview] (Optional) Report type for the TikTok Ads API.
    If not specified, defaults to BASIC.
    """


TikTokAdsOptionsTikTokAdsCustomReportOptionsParam = (
    TikTokAdsOptionsTikTokAdsCustomReportOptionsDict
    | TikTokAdsOptionsTikTokAdsCustomReportOptions
)
