Ignore = [
  "requirements-latest.txt",
]

[EnvMatrix]
PYDAB_VERSION = [
  # pin to a specific version from the past to avoid issues with unintended breaking changes
  # we can't expect CLI and databricks-bundles versions to be always in sync
  "0.266.0",
  # "current" means use the wheel built from the same commit
  "current",
]

[EnvRepl]
# Don't replace PYDAB_VERSION values in output — "current" is too common a word
PYDAB_VERSION = false
