"""
Generates the per-resource TestCase data driving databricks_tests/core/test_resources.py.

For every wired resource a file _generated/<plural>.py is written (rendered from
test_case.py.tmpl) exposing _test_case() -> (TestCase, _ResourceType). The generated
_generated/__init__.py collects them into `test_cases`, which test_resources.py imports
and parametrizes its per-resource tests off.

dict_example and dataclass_example are synthesized from one value tree and rendered two
independent ways -- a dict literal and a constructor expression -- so the dict->dataclass
_transform assertion in test_resources.py stays meaningful (the two forms don't share the
runtime transform path).

Field policy: all required fields (fully expanded), plus optional composite fields
(nested dataclass / list / map / enum) on the resource itself; nested objects contribute
only their required fields, which keeps examples bounded and avoids recursive schemas
(e.g. jobs Task -> ForEachTask -> Task, reachable only through an optional field). Optional
scalar, deprecated, and experimental fields are omitted.
"""

from dataclasses import dataclass
from pathlib import Path
from string import Template
from typing import Union

import codegen.jsonschema as openapi
import codegen.packages as packages
from codegen.generated_enum import _camel_to_upper_snake
from codegen.generated_wiring import _WiredResource, _wired_resources

HEADER = "# Code generated by pydabs-codegen. DO NOT EDIT.\n\n"

_TEST_CASE_TEMPLATE = Template(
    (Path(__file__).parent / "test_case.py.tmpl").read_text()
)


# Synthesized value tree. Each node renders both as a dict literal (dict_example)
# and as a constructor expression (dataclass_example).


@dataclass
class _Scalar:
    dict_src: str
    dataclass_src: str


@dataclass
class _Enum:
    value: str
    class_name: str
    module: str
    member: str


@dataclass
class _Object:
    class_name: str
    module: str
    fields: "list[tuple[str, _Value]]"


@dataclass
class _List:
    item: "_Value"


@dataclass
class _Map:
    key: str
    value: "_Value"


_Value = Union[_Scalar, _Enum, _Object, _List, _Map]


def _ref_name(ref: str) -> str:
    return ref.split("/")[-1]


def _is_composite(ref: str) -> bool:
    if ref.startswith("#/$defs/slice/") or ref.startswith("#/$defs/map/"):
        return True

    return _ref_name(ref) not in packages.PRIMITIVES


def _synth_scalar(name: str, hint: str) -> _Scalar:
    if name == "string":
        return _Scalar(f'"{hint}"', f'"{hint}"')
    if name in ("integer", "int", "int64"):
        return _Scalar("0", "0")
    if name in ("number", "float", "float64"):
        return _Scalar("0.0", "0.0")
    if name in ("boolean", "bool"):
        return _Scalar("True", "True")

    raise ValueError(f"Unknown primitive: {name}")


def _synth_ref(
    namespace: str,
    ref: str,
    hint: str,
    schemas: dict[str, openapi.Schema],
    visiting: set[str],
) -> _Value:
    if ref.startswith("#/$defs/slice/"):
        element_ref = ref.replace("#/$defs/slice/", "#/$defs/")

        return _List(_synth_ref(namespace, element_ref, hint, schemas, visiting))

    if ref.startswith("#/$defs/map/"):
        # generate_type only ever produces dict[str, str] maps (map/string).
        if ref != "#/$defs/map/string":
            raise ValueError(f"Unsupported map ref: {ref}")

        return _Map("key", _Scalar('"value"', '"value"'))

    name = _ref_name(ref)
    if name in packages.PRIMITIVES:
        return _synth_scalar(name, hint)

    schema = schemas[name]
    class_name = packages.get_class_name(ref)
    module = packages.get_package(namespace, ref)
    assert module

    if schema.type == openapi.SchemaType.STRING:
        value = schema.enum[0]

        return _Enum(value, class_name, module, _camel_to_upper_snake(value))

    # Only reachable through required fields at this depth (see _synth_object); a
    # required cycle has no finite value, so fail loudly instead of looping.
    if name in visiting:
        raise ValueError(f"Required-field cycle through '{name}'")

    return _synth_object(namespace, name, schema, schemas, visiting, top_level=False)


def _synth_object(
    namespace: str,
    schema_name: str,
    schema: openapi.Schema,
    schemas: dict[str, openapi.Schema],
    visiting: set[str],
    top_level: bool,
) -> _Object:
    visiting = visiting | {schema_name}
    fields: list[tuple[str, _Value]] = []

    for field_name, prop in schema.properties.items():
        required = field_name in schema.required

        if not required:
            # Nested objects contribute only required fields; on the resource
            # itself, also include stable optional composite fields.
            if not top_level:
                continue
            if not _is_composite(prop.ref):
                continue
            if prop.deprecated or prop.stage == openapi.LaunchStage.PRIVATE_PREVIEW:
                continue

        value = _synth_ref(namespace, prop.ref, field_name, schemas, visiting)
        fields.append((field_name, value))

    return _Object(
        packages.get_class_name(schema_name), _module_of(namespace, schema_name), fields
    )


def _module_of(namespace: str, schema_name: str) -> str:
    module = packages.get_package(namespace, schema_name)
    assert module

    return module


def _render_dict(value: _Value) -> str:
    if isinstance(value, _Scalar):
        return value.dict_src
    if isinstance(value, _Enum):
        return f'"{value.value}"'
    if isinstance(value, _List):
        return f"[{_render_dict(value.item)}]"
    if isinstance(value, _Map):
        return "{" + f'"{value.key}": {_render_dict(value.value)}' + "}"

    fields = ", ".join(
        f'"{name}": {_render_dict(child)}' for name, child in value.fields
    )

    return "{" + fields + "}"


def _render_dataclass(value: _Value) -> str:
    if isinstance(value, _Scalar):
        return value.dataclass_src
    if isinstance(value, _Enum):
        return f"{value.class_name}.{value.member}"
    if isinstance(value, _List):
        return f"[{_render_dataclass(value.item)}]"
    if isinstance(value, _Map):
        return "{" + f'"{value.key}": {_render_dataclass(value.value)}' + "}"

    fields = ", ".join(
        f"{name}={_render_dataclass(child)}" for name, child in value.fields
    )

    return f"{value.class_name}({fields})"


def _collect_imports(value: _Value, out: set[tuple[str, str]]) -> None:
    if isinstance(value, _Enum):
        out.add((value.module, value.class_name))
    elif isinstance(value, _Object):
        out.add((value.module, value.class_name))
        for _, child in value.fields:
            _collect_imports(child, out)
    elif isinstance(value, _List):
        _collect_imports(value.item, out)
    elif isinstance(value, _Map):
        _collect_imports(value.value, out)


def write_test_cases(output: str, schemas: dict[str, openapi.Schema]):
    resources = _wired_resources()

    generated_path = Path(output) / "databricks_tests" / "core" / "_generated"
    generated_path.mkdir(parents=True, exist_ok=True)

    plural_to_ref = {ns: ref for ref, ns in packages.RESOURCE_NAMESPACE.items()}

    for r in resources:
        resource_ref = plural_to_ref[r.plural_name]
        schema = schemas[resource_ref]

        example = _synth_object(
            r.plural_name, resource_ref, schema, schemas, set(), top_level=True
        )

        imports: set[tuple[str, str]] = set()
        _collect_imports(example, imports)
        model_imports = "\n".join(
            f"from {module} import {class_name}"
            for module, class_name in sorted(imports)
        )

        code = _TEST_CASE_TEMPLATE.substitute(
            singular=r.singular_name,
            plural=r.plural_name,
            model_imports=model_imports,
            dict_example=_render_dict(example),
            dataclass_example=_render_dataclass(example),
        )
        (generated_path / f"{r.plural_name}.py").write_text(HEADER + code)

    (generated_path / "__init__.py").write_text(HEADER + _collector_code(resources))

    print(f"Writing test cases into {generated_path}")


def _collector_code(resources: list[_WiredResource]) -> str:
    module_imports = "\n".join(f"    {r.plural_name}," for r in resources)
    entries = "\n".join(f"    {r.plural_name}._test_case()," for r in resources)

    return f"""from databricks_tests.core._generated import (
{module_imports}
)

__all__ = ["test_cases"]

test_cases = [
{entries}
]
"""
