"""
Generates the per-resource wiring in databricks.bundles.core that used to be
hand-written. All output is rendered from the *.py.tmpl templates in this
directory.

Each wired resource gets its own file _generated/<plural>.py (rendered from
wiring_resource.py.tmpl): the add_* method + collection property mixin, the
*_mutator decorator, and the _ResourceType entry. The generated
_generated/__init__.py (generated_init.py.tmpl) collects them into
_GeneratedResources (mixed into Resources), _all_resource_types(), and the
mutator re-exports. The core package __init__ (core_init.py.tmpl) is generated
too (static exports plus the generated mutators).
"""

from dataclasses import dataclass
from pathlib import Path
from string import Template

import codegen.packages as packages

HEADER = "# Code generated by pydabs-codegen. DO NOT EDIT.\n\n"


def _load_template(name: str) -> Template:
    return Template((Path(__file__).parent / name).read_text())


_RESOURCE_TEMPLATE = _load_template("wiring_resource.py.tmpl")
_GENERATED_INIT_TEMPLATE = _load_template("generated_init.py.tmpl")
_CORE_INIT_TEMPLATE = _load_template("core_init.py.tmpl")


@dataclass(frozen=True)
class _WiredResource:
    class_name: str
    """Resource dataclass name, e.g. "Job"."""

    singular_name: str
    """Singular name used in methods and messages, e.g. "job"."""

    plural_name: str
    """Plural name, the same as the "resources" bundle section, e.g. "jobs"."""

    model_module: str
    """Module the resource dataclass lives in, e.g. "databricks.bundles.jobs._models.job"."""


def _wired_resources() -> list[_WiredResource]:
    # Every namespaced resource is wired. RESOURCE_NAMESPACE is the single source
    # of truth for both model generation and wiring.
    resources = []

    for ref, namespace in packages.RESOURCE_NAMESPACE.items():
        class_name = packages.get_class_name(ref)

        resources.append(
            _WiredResource(
                class_name=class_name,
                singular_name=packages.to_snake_case(class_name),
                plural_name=namespace,
                model_module=packages.get_package(namespace, ref),
            )
        )

    resources.sort(key=lambda r: r.plural_name)

    return resources


def write_wiring(output: str):
    resources = _wired_resources()

    core_path = Path(output) / "databricks" / "bundles" / "core"
    generated_path = core_path / "_generated"
    generated_path.mkdir(parents=True, exist_ok=True)

    for r in resources:
        code = _RESOURCE_TEMPLATE.substitute(
            {
                "class": r.class_name,
                "singular": r.singular_name,
                "plural": r.plural_name,
                "model_module": r.model_module,
            }
        )
        (generated_path / f"{r.plural_name}.py").write_text(HEADER + code)

    (generated_path / "__init__.py").write_text(HEADER + _collector_code(resources))
    (core_path / "__init__.py").write_text(HEADER + _core_init_code(resources))

    print(f"Writing wiring into {generated_path}")


def _collector_code(resources: list[_WiredResource]) -> str:
    imports = "\n".join(
        f"from databricks.bundles.core._generated.{r.plural_name} import "
        f"_{r.class_name}Resources, {r.singular_name}_mutator"
        for r in resources
    )

    mutator_names = [f"{r.singular_name}_mutator" for r in resources]
    exports = sorted(["_GeneratedResources", "_all_resource_types", *mutator_names])
    all_block = "\n".join(f'    "{name}",' for name in exports)

    mixins = "\n".join(f"    _{r.class_name}Resources," for r in resources)
    module_imports = "\n".join(f"        {r.plural_name}," for r in resources)
    type_entries = "\n".join(
        f"        {r.plural_name}._resource_type()," for r in resources
    )

    return _GENERATED_INIT_TEMPLATE.substitute(
        {
            "imports": imports,
            "all_block": all_block,
            "mixins": mixins,
            "module_imports": module_imports,
            "type_entries": type_entries,
        }
    )


# Static, non-resource exports of databricks.bundles.core, used to build the
# sorted __all__ (the resource mutators are appended). Must stay in sync with the
# import statements in core_init.py.tmpl.
_CORE_INIT_STATIC_EXPORTS = [
    "Bundle",
    "Diagnostic",
    "Diagnostics",
    "Location",
    "Resource",
    "ResourceMutator",
    "Resources",
    "Severity",
    "Variable",
    "VariableOr",
    "VariableOrDict",
    "VariableOrList",
    "VariableOrOptional",
    "load_resources_from_current_package_module",
    "load_resources_from_module",
    "load_resources_from_modules",
    "load_resources_from_package_module",
    "variables",
]


def _core_init_code(resources: list[_WiredResource]) -> str:
    mutator_names = [f"{r.singular_name}_mutator" for r in resources]

    all_exports = sorted(_CORE_INIT_STATIC_EXPORTS + mutator_names)
    all_block = "\n".join(f'    "{name}",' for name in all_exports)

    mutator_imports = ",\n".join(f"    {name}" for name in sorted(mutator_names))

    return _CORE_INIT_TEMPLATE.substitute(
        {
            "all_block": all_block,
            "mutator_imports": mutator_imports,
        }
    )
