# Code generated by pydabs-codegen. DO NOT EDIT.

from dataclasses import dataclass
from typing import TYPE_CHECKING, TypedDict

from databricks.bundles.core._transform import _transform
from databricks.bundles.core._transform_to_json import _transform_to_json_value
from databricks.bundles.core._variable import VariableOrOptional
from databricks.bundles.sql_warehouses._models.channel_name import (
    ChannelName,
    ChannelNameParam,
)

if TYPE_CHECKING:
    from typing_extensions import Self


@dataclass(kw_only=True)
class Channel:
    """
    Configures the channel name and DBSQL version of the warehouse. CHANNEL_NAME_CUSTOM should be chosen only when `dbsql_version` is specified.
    """

    dbsql_version: VariableOrOptional[str] = None

    name: VariableOrOptional[ChannelName] = None

    @classmethod
    def from_dict(cls, value: "ChannelDict") -> "Self":
        return _transform(cls, value)

    def as_dict(self) -> "ChannelDict":
        return _transform_to_json_value(self)  # type:ignore


class ChannelDict(TypedDict, total=False):
    """"""

    dbsql_version: VariableOrOptional[str]

    name: VariableOrOptional[ChannelNameParam]


ChannelParam = ChannelDict | Channel
