# Code generated by pydabs-codegen. DO NOT EDIT.

from enum import Enum
from typing import Literal


class CreateWarehouseRequestWarehouseType(Enum):
    TYPE_UNSPECIFIED = "TYPE_UNSPECIFIED"
    CLASSIC = "CLASSIC"
    PRO = "PRO"


CreateWarehouseRequestWarehouseTypeParam = (
    Literal["TYPE_UNSPECIFIED", "CLASSIC", "PRO"] | CreateWarehouseRequestWarehouseType
)
