# Code generated by pydabs-codegen. DO NOT EDIT.

from dataclasses import dataclass
from typing import TYPE_CHECKING, TypedDict

from databricks.bundles.core._transform import _transform
from databricks.bundles.core._transform_to_json import _transform_to_json_value
from databricks.bundles.core._variable import VariableOrOptional

if TYPE_CHECKING:
    from typing_extensions import Self


@dataclass(kw_only=True)
class EndpointTagPair:
    """"""

    key: VariableOrOptional[str] = None

    value: VariableOrOptional[str] = None

    @classmethod
    def from_dict(cls, value: "EndpointTagPairDict") -> "Self":
        return _transform(cls, value)

    def as_dict(self) -> "EndpointTagPairDict":
        return _transform_to_json_value(self)  # type:ignore


class EndpointTagPairDict(TypedDict, total=False):
    """"""

    key: VariableOrOptional[str]

    value: VariableOrOptional[str]


EndpointTagPairParam = EndpointTagPairDict | EndpointTagPair
