# Code generated by pydabs-codegen. DO NOT EDIT.

from enum import Enum
from typing import Literal


class SpotInstancePolicy(Enum):
    """
    EndpointSpotInstancePolicy configures whether the endpoint should use spot
    instances.

    The breakdown of how the EndpointSpotInstancePolicy converts to per cloud
    configurations is:

    - AWS, COST_OPTIMIZED: On Demand Driver with Spot Executors.
    - AWS, RELIABILITY_OPTIMIZED: On Demand Driver and Executors.
    - AZURE, COST_OPTIMIZED: On Demand Driver and Executors.
    - AZURE, RELIABILITY_OPTIMIZED: On Demand Driver and Executors.
    """

    POLICY_UNSPECIFIED = "POLICY_UNSPECIFIED"
    COST_OPTIMIZED = "COST_OPTIMIZED"
    RELIABILITY_OPTIMIZED = "RELIABILITY_OPTIMIZED"


SpotInstancePolicyParam = (
    Literal["POLICY_UNSPECIFIED", "COST_OPTIMIZED", "RELIABILITY_OPTIMIZED"]
    | SpotInstancePolicy
)
