#!/bin/bash

touch dummy.whl
$CLI bundle deploy
job_id="$(read_id.py my_job)"

title "Modify job trigger from 1 day to 2 hours"
edit_resource.py jobs $job_id <<EOF
r["trigger"]["periodic"]["interval"] = 2
r["trigger"]["periodic"]["unit"] = "HOURS"
EOF

title "Detect and save changes"
echo
cp databricks.yml databricks.yml.backup
$CLI bundle config-remote-sync --save

title "Configuration changes"
echo
diff -u databricks.yml.backup databricks.yml || true
rm databricks.yml.backup
