# Code generated by pydabs-codegen. DO NOT EDIT.

from typing import TYPE_CHECKING

from databricks.bundles.core._generated.alerts import _AlertResources, alert_mutator
from databricks.bundles.core._generated.catalogs import (
    _CatalogResources,
    catalog_mutator,
)
from databricks.bundles.core._generated.dashboards import (
    _DashboardResources,
    dashboard_mutator,
)
from databricks.bundles.core._generated.jobs import _JobResources, job_mutator
from databricks.bundles.core._generated.pipelines import (
    _PipelineResources,
    pipeline_mutator,
)
from databricks.bundles.core._generated.schemas import _SchemaResources, schema_mutator
from databricks.bundles.core._generated.volumes import _VolumeResources, volume_mutator

if TYPE_CHECKING:
    from databricks.bundles.core._resource_type import _ResourceType

__all__ = [
    "_GeneratedResources",
    "_all_resource_types",
    "alert_mutator",
    "catalog_mutator",
    "dashboard_mutator",
    "job_mutator",
    "pipeline_mutator",
    "schema_mutator",
    "volume_mutator",
]


class _GeneratedResources(
    _AlertResources,
    _CatalogResources,
    _DashboardResources,
    _JobResources,
    _PipelineResources,
    _SchemaResources,
    _VolumeResources,
):
    pass


def _all_resource_types() -> "tuple[_ResourceType, ...]":
    from databricks.bundles.core._generated import (
        alerts,
        catalogs,
        dashboards,
        jobs,
        pipelines,
        schemas,
        volumes,
    )

    return (
        alerts._resource_type(),
        catalogs._resource_type(),
        dashboards._resource_type(),
        jobs._resource_type(),
        pipelines._resource_type(),
        schemas._resource_type(),
        volumes._resource_type(),
    )
