# Code generated by pydabs-codegen. DO NOT EDIT.

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from databricks.bundles.core._resource_type import _ResourceType


def _all_resource_types() -> "tuple[_ResourceType, ...]":
    # Lazily import resource types so that databricks.bundles.core is not
    # imported from databricks.bundles.<resource_type>.
    from databricks.bundles.alerts._models.alert import Alert
    from databricks.bundles.catalogs._models.catalog import Catalog
    from databricks.bundles.core._resource_type import _ResourceType
    from databricks.bundles.jobs._models.job import Job
    from databricks.bundles.pipelines._models.pipeline import Pipeline
    from databricks.bundles.schemas._models.schema import Schema
    from databricks.bundles.volumes._models.volume import Volume

    return (
        _ResourceType(
            resource_type=Alert,
            singular_name="alert",
            plural_name="alerts",
        ),
        _ResourceType(
            resource_type=Catalog,
            singular_name="catalog",
            plural_name="catalogs",
        ),
        _ResourceType(
            resource_type=Job,
            singular_name="job",
            plural_name="jobs",
        ),
        _ResourceType(
            resource_type=Pipeline,
            singular_name="pipeline",
            plural_name="pipelines",
        ),
        _ResourceType(
            resource_type=Schema,
            singular_name="schema",
            plural_name="schemas",
        ),
        _ResourceType(
            resource_type=Volume,
            singular_name="volume",
            plural_name="volumes",
        ),
    )
