# Code generated by pydabs-codegen. DO NOT EDIT.

from collections.abc import Callable
from typing import TYPE_CHECKING, Optional, overload

from databricks.bundles.core._bundle import Bundle
from databricks.bundles.core._location import Location
from databricks.bundles.core._resource_mutator import ResourceMutator
from databricks.bundles.core._transform import _transform

if TYPE_CHECKING:
    from databricks.bundles.alerts._models.alert import Alert, AlertParam
    from databricks.bundles.core._resource_type import _ResourceType


def _resource_type() -> "_ResourceType":
    from databricks.bundles.alerts._models.alert import Alert
    from databricks.bundles.core._resource_type import _ResourceType

    return _ResourceType(
        resource_type=Alert,
        singular_name="alert",
        plural_name="alerts",
    )


class _AlertResources:
    """
    Generated alert accessors, mixed into Resources.
    """

    # Provided by the Resources subclass; declared here so the generated methods
    # below type-check.
    _resources: dict[str, dict]

    if TYPE_CHECKING:

        def add_location(self, path: tuple[str, ...], location: Location) -> None: ...

        def add_diagnostic_error(
            self,
            msg: str,
            *,
            detail: Optional[str] = None,
            path: Optional[tuple[str, ...]] = None,
            location: Optional[Location] = None,
        ) -> None: ...

    @property
    def alerts(self) -> dict[str, "Alert"]:
        return self._resources["alerts"]

    def add_alert(
        self,
        resource_name: str,
        alert: "AlertParam",
        *,
        location: Optional[Location] = None,
    ) -> None:
        """
        Adds the resource alert to the collection of resources. Resource name must be unique across all alerts.

        :param resource_name: unique identifier for the alert
        :param alert: the alert to add, can be Alert or dict
        :param location: optional location of the alert in the source code
        """
        from databricks.bundles.alerts._models.alert import Alert

        alert = _transform(Alert, alert)
        path = ("resources", "alerts", resource_name)
        location = location or Location.from_stack_frame(depth=1)

        if self._resources["alerts"].get(resource_name):
            self.add_diagnostic_error(
                msg=f"Duplicate resource name '{resource_name}' for resource 'alert'. Resource names must be unique.",
                location=location,
                path=path,
            )
        else:
            if location:
                self.add_location(path, location)

            self._resources["alerts"][resource_name] = alert


@overload
def alert_mutator(
    function: Callable[[Bundle, "Alert"], "Alert"],
) -> ResourceMutator["Alert"]: ...


@overload
def alert_mutator(
    function: Callable[["Alert"], "Alert"],
) -> ResourceMutator["Alert"]: ...


def alert_mutator(function: Callable) -> ResourceMutator["Alert"]:
    """
    Decorator for defining mutator for alerts. Function should return a new instance of the alert
    with the desired changes, instead of mutating the input alert.

    Example:

    .. code-block:: python

        @alert_mutator
        def my_alert_mutator(bundle: Bundle, alert: Alert) -> Alert:
            return replace(alert, ...)

    :param function: Function that mutates alerts.
    """
    from databricks.bundles.alerts._models.alert import Alert

    return ResourceMutator(resource_type=Alert, function=function)
