# Code generated by pydabs-codegen. DO NOT EDIT.

from collections.abc import Callable
from typing import TYPE_CHECKING, Optional, overload

from databricks.bundles.core._bundle import Bundle
from databricks.bundles.core._location import Location
from databricks.bundles.core._resource_mutator import ResourceMutator
from databricks.bundles.core._transform import _transform

if TYPE_CHECKING:
    from databricks.bundles.clusters._models.cluster import Cluster, ClusterParam
    from databricks.bundles.core._resource_type import _ResourceType


def _resource_type() -> "_ResourceType":
    from databricks.bundles.clusters._models.cluster import Cluster
    from databricks.bundles.core._resource_type import _ResourceType

    return _ResourceType(
        resource_type=Cluster,
        singular_name="cluster",
        plural_name="clusters",
    )


class _ClusterResources:
    """
    Generated cluster accessors, mixed into Resources.
    """

    # Provided by the Resources subclass; declared here so the generated methods
    # below type-check.
    _resources: dict[str, dict]

    if TYPE_CHECKING:

        def add_location(self, path: tuple[str, ...], location: Location) -> None: ...

        def add_diagnostic_error(
            self,
            msg: str,
            *,
            detail: Optional[str] = None,
            path: Optional[tuple[str, ...]] = None,
            location: Optional[Location] = None,
        ) -> None: ...

    @property
    def clusters(self) -> dict[str, "Cluster"]:
        return self._resources["clusters"]

    def add_cluster(
        self,
        resource_name: str,
        cluster: "ClusterParam",
        *,
        location: Optional[Location] = None,
    ) -> None:
        """
        Adds the resource cluster to the collection of resources. Resource name must be unique across all clusters.

        :param resource_name: unique identifier for the cluster
        :param cluster: the cluster to add, can be Cluster or dict
        :param location: optional location of the cluster in the source code
        """
        from databricks.bundles.clusters._models.cluster import Cluster

        cluster = _transform(Cluster, cluster)
        path = ("resources", "clusters", resource_name)
        location = location or Location.from_stack_frame(depth=1)

        if self._resources["clusters"].get(resource_name):
            self.add_diagnostic_error(
                msg=f"Duplicate resource name '{resource_name}' for resource 'cluster'. Resource names must be unique.",
                location=location,
                path=path,
            )
        else:
            if location:
                self.add_location(path, location)

            self._resources["clusters"][resource_name] = cluster


@overload
def cluster_mutator(
    function: Callable[[Bundle, "Cluster"], "Cluster"],
) -> ResourceMutator["Cluster"]: ...


@overload
def cluster_mutator(
    function: Callable[["Cluster"], "Cluster"],
) -> ResourceMutator["Cluster"]: ...


def cluster_mutator(function: Callable) -> ResourceMutator["Cluster"]:
    """
    Decorator for defining mutator for clusters. Function should return a new instance of the cluster
    with the desired changes, instead of mutating the input cluster.

    Example:

    .. code-block:: python

        @cluster_mutator
        def my_cluster_mutator(bundle: Bundle, cluster: Cluster) -> Cluster:
            return replace(cluster, ...)

    :param function: Function that mutates clusters.
    """
    from databricks.bundles.clusters._models.cluster import Cluster

    return ResourceMutator(resource_type=Cluster, function=function)
