# Code generated by pydabs-codegen. DO NOT EDIT.

from collections.abc import Callable
from typing import TYPE_CHECKING, Optional, overload

from databricks.bundles.core._bundle import Bundle
from databricks.bundles.core._location import Location
from databricks.bundles.core._resource_mutator import ResourceMutator
from databricks.bundles.core._transform import _transform

if TYPE_CHECKING:
    from databricks.bundles.core._resource_type import _ResourceType
    from databricks.bundles.instance_pools._models.instance_pool import (
        InstancePool,
        InstancePoolParam,
    )


def _resource_type() -> "_ResourceType":
    from databricks.bundles.core._resource_type import _ResourceType
    from databricks.bundles.instance_pools._models.instance_pool import InstancePool

    return _ResourceType(
        resource_type=InstancePool,
        singular_name="instance_pool",
        plural_name="instance_pools",
    )


class _InstancePoolResources:
    """
    Generated instance_pool accessors, mixed into Resources.
    """

    # Provided by the Resources subclass; declared here so the generated methods
    # below type-check.
    _resources: dict[str, dict]

    if TYPE_CHECKING:

        def add_location(self, path: tuple[str, ...], location: Location) -> None: ...

        def add_diagnostic_error(
            self,
            msg: str,
            *,
            detail: Optional[str] = None,
            path: Optional[tuple[str, ...]] = None,
            location: Optional[Location] = None,
        ) -> None: ...

    @property
    def instance_pools(self) -> dict[str, "InstancePool"]:
        return self._resources["instance_pools"]

    def add_instance_pool(
        self,
        resource_name: str,
        instance_pool: "InstancePoolParam",
        *,
        location: Optional[Location] = None,
    ) -> None:
        """
        Adds the resource instance_pool to the collection of resources. Resource name must be unique across all instance_pools.

        :param resource_name: unique identifier for the instance_pool
        :param instance_pool: the instance_pool to add, can be InstancePool or dict
        :param location: optional location of the instance_pool in the source code
        """
        from databricks.bundles.instance_pools._models.instance_pool import InstancePool

        instance_pool = _transform(InstancePool, instance_pool)
        path = ("resources", "instance_pools", resource_name)
        location = location or Location.from_stack_frame(depth=1)

        if self._resources["instance_pools"].get(resource_name):
            self.add_diagnostic_error(
                msg=f"Duplicate resource name '{resource_name}' for resource 'instance_pool'. Resource names must be unique.",
                location=location,
                path=path,
            )
        else:
            if location:
                self.add_location(path, location)

            self._resources["instance_pools"][resource_name] = instance_pool


@overload
def instance_pool_mutator(
    function: Callable[[Bundle, "InstancePool"], "InstancePool"],
) -> ResourceMutator["InstancePool"]: ...


@overload
def instance_pool_mutator(
    function: Callable[["InstancePool"], "InstancePool"],
) -> ResourceMutator["InstancePool"]: ...


def instance_pool_mutator(function: Callable) -> ResourceMutator["InstancePool"]:
    """
    Decorator for defining mutator for instance_pools. Function should return a new instance of the instance_pool
    with the desired changes, instead of mutating the input instance_pool.

    Example:

    .. code-block:: python

        @instance_pool_mutator
        def my_instance_pool_mutator(bundle: Bundle, instance_pool: InstancePool) -> InstancePool:
            return replace(instance_pool, ...)

    :param function: Function that mutates instance_pools.
    """
    from databricks.bundles.instance_pools._models.instance_pool import InstancePool

    return ResourceMutator(resource_type=InstancePool, function=function)
