# Code generated by pydabs-codegen. DO NOT EDIT.

from collections.abc import Callable
from typing import TYPE_CHECKING, Optional, overload

from databricks.bundles.core._bundle import Bundle
from databricks.bundles.core._location import Location
from databricks.bundles.core._resource_mutator import ResourceMutator
from databricks.bundles.core._transform import _transform

if TYPE_CHECKING:
    from databricks.bundles.core._resource_type import _ResourceType
    from databricks.bundles.jobs._models.job import Job, JobParam


def _resource_type() -> "_ResourceType":
    from databricks.bundles.core._resource_type import _ResourceType
    from databricks.bundles.jobs._models.job import Job

    return _ResourceType(
        resource_type=Job,
        singular_name="job",
        plural_name="jobs",
    )


class _JobResources:
    """
    Generated job accessors, mixed into Resources.
    """

    # Provided by the Resources subclass; declared here so the generated methods
    # below type-check.
    _resources: dict[str, dict]

    if TYPE_CHECKING:

        def add_location(self, path: tuple[str, ...], location: Location) -> None: ...

        def add_diagnostic_error(
            self,
            msg: str,
            *,
            detail: Optional[str] = None,
            path: Optional[tuple[str, ...]] = None,
            location: Optional[Location] = None,
        ) -> None: ...

    @property
    def jobs(self) -> dict[str, "Job"]:
        return self._resources["jobs"]

    def add_job(
        self,
        resource_name: str,
        job: "JobParam",
        *,
        location: Optional[Location] = None,
    ) -> None:
        """
        Adds the resource job to the collection of resources. Resource name must be unique across all jobs.

        :param resource_name: unique identifier for the job
        :param job: the job to add, can be Job or dict
        :param location: optional location of the job in the source code
        """
        from databricks.bundles.jobs._models.job import Job

        job = _transform(Job, job)
        path = ("resources", "jobs", resource_name)
        location = location or Location.from_stack_frame(depth=1)

        if self._resources["jobs"].get(resource_name):
            self.add_diagnostic_error(
                msg=f"Duplicate resource name '{resource_name}' for resource 'job'. Resource names must be unique.",
                location=location,
                path=path,
            )
        else:
            if location:
                self.add_location(path, location)

            self._resources["jobs"][resource_name] = job


@overload
def job_mutator(
    function: Callable[[Bundle, "Job"], "Job"],
) -> ResourceMutator["Job"]: ...


@overload
def job_mutator(
    function: Callable[["Job"], "Job"],
) -> ResourceMutator["Job"]: ...


def job_mutator(function: Callable) -> ResourceMutator["Job"]:
    """
    Decorator for defining mutator for jobs. Function should return a new instance of the job
    with the desired changes, instead of mutating the input job.

    Example:

    .. code-block:: python

        @job_mutator
        def my_job_mutator(bundle: Bundle, job: Job) -> Job:
            return replace(job, ...)

    :param function: Function that mutates jobs.
    """
    from databricks.bundles.jobs._models.job import Job

    return ResourceMutator(resource_type=Job, function=function)
