# Code generated by pydabs-codegen. DO NOT EDIT.

from collections.abc import Callable
from typing import TYPE_CHECKING, Optional, overload

from databricks.bundles.core._bundle import Bundle
from databricks.bundles.core._location import Location
from databricks.bundles.core._resource_mutator import ResourceMutator
from databricks.bundles.core._transform import _transform

if TYPE_CHECKING:
    from databricks.bundles.core._resource_type import _ResourceType
    from databricks.bundles.mcp_services._models.mcp_service import (
        McpService,
        McpServiceParam,
    )


def _resource_type() -> "_ResourceType":
    from databricks.bundles.core._resource_type import _ResourceType
    from databricks.bundles.mcp_services._models.mcp_service import McpService

    return _ResourceType(
        resource_type=McpService,
        singular_name="mcp_service",
        plural_name="mcp_services",
    )


class _McpServiceResources:
    """
    Generated mcp_service accessors, mixed into Resources.
    """

    # Provided by the Resources subclass; declared here so the generated methods
    # below type-check.
    _resources: dict[str, dict]

    if TYPE_CHECKING:

        def add_location(self, path: tuple[str, ...], location: Location) -> None: ...

        def add_diagnostic_error(
            self,
            msg: str,
            *,
            detail: Optional[str] = None,
            path: Optional[tuple[str, ...]] = None,
            location: Optional[Location] = None,
        ) -> None: ...

    @property
    def mcp_services(self) -> dict[str, "McpService"]:
        return self._resources["mcp_services"]

    def add_mcp_service(
        self,
        resource_name: str,
        mcp_service: "McpServiceParam",
        *,
        location: Optional[Location] = None,
    ) -> None:
        """
        Adds the resource mcp_service to the collection of resources. Resource name must be unique across all mcp_services.

        :param resource_name: unique identifier for the mcp_service
        :param mcp_service: the mcp_service to add, can be McpService or dict
        :param location: optional location of the mcp_service in the source code
        """
        from databricks.bundles.mcp_services._models.mcp_service import McpService

        mcp_service = _transform(McpService, mcp_service)
        path = ("resources", "mcp_services", resource_name)
        location = location or Location.from_stack_frame(depth=1)

        if self._resources["mcp_services"].get(resource_name):
            self.add_diagnostic_error(
                msg=f"Duplicate resource name '{resource_name}' for resource 'mcp_service'. Resource names must be unique.",
                location=location,
                path=path,
            )
        else:
            if location:
                self.add_location(path, location)

            self._resources["mcp_services"][resource_name] = mcp_service


@overload
def mcp_service_mutator(
    function: Callable[[Bundle, "McpService"], "McpService"],
) -> ResourceMutator["McpService"]: ...


@overload
def mcp_service_mutator(
    function: Callable[["McpService"], "McpService"],
) -> ResourceMutator["McpService"]: ...


def mcp_service_mutator(function: Callable) -> ResourceMutator["McpService"]:
    """
    Decorator for defining mutator for mcp_services. Function should return a new instance of the mcp_service
    with the desired changes, instead of mutating the input mcp_service.

    Example:

    .. code-block:: python

        @mcp_service_mutator
        def my_mcp_service_mutator(bundle: Bundle, mcp_service: McpService) -> McpService:
            return replace(mcp_service, ...)

    :param function: Function that mutates mcp_services.
    """
    from databricks.bundles.mcp_services._models.mcp_service import McpService

    return ResourceMutator(resource_type=McpService, function=function)
