# Code generated by pydabs-codegen. DO NOT EDIT.

from collections.abc import Callable
from typing import TYPE_CHECKING, Optional, overload

from databricks.bundles.core._bundle import Bundle
from databricks.bundles.core._location import Location
from databricks.bundles.core._resource_mutator import ResourceMutator
from databricks.bundles.core._transform import _transform

if TYPE_CHECKING:
    from databricks.bundles.core._resource_type import _ResourceType
    from databricks.bundles.secret_scopes._models.secret_scope import (
        SecretScope,
        SecretScopeParam,
    )


def _resource_type() -> "_ResourceType":
    from databricks.bundles.core._resource_type import _ResourceType
    from databricks.bundles.secret_scopes._models.secret_scope import SecretScope

    return _ResourceType(
        resource_type=SecretScope,
        singular_name="secret_scope",
        plural_name="secret_scopes",
    )


class _SecretScopeResources:
    """
    Generated secret_scope accessors, mixed into Resources.
    """

    # Provided by the Resources subclass; declared here so the generated methods
    # below type-check.
    _resources: dict[str, dict]

    if TYPE_CHECKING:

        def add_location(self, path: tuple[str, ...], location: Location) -> None: ...

        def add_diagnostic_error(
            self,
            msg: str,
            *,
            detail: Optional[str] = None,
            path: Optional[tuple[str, ...]] = None,
            location: Optional[Location] = None,
        ) -> None: ...

    @property
    def secret_scopes(self) -> dict[str, "SecretScope"]:
        return self._resources["secret_scopes"]

    def add_secret_scope(
        self,
        resource_name: str,
        secret_scope: "SecretScopeParam",
        *,
        location: Optional[Location] = None,
    ) -> None:
        """
        Adds the resource secret_scope to the collection of resources. Resource name must be unique across all secret_scopes.

        :param resource_name: unique identifier for the secret_scope
        :param secret_scope: the secret_scope to add, can be SecretScope or dict
        :param location: optional location of the secret_scope in the source code
        """
        from databricks.bundles.secret_scopes._models.secret_scope import SecretScope

        secret_scope = _transform(SecretScope, secret_scope)
        path = ("resources", "secret_scopes", resource_name)
        location = location or Location.from_stack_frame(depth=1)

        if self._resources["secret_scopes"].get(resource_name):
            self.add_diagnostic_error(
                msg=f"Duplicate resource name '{resource_name}' for resource 'secret_scope'. Resource names must be unique.",
                location=location,
                path=path,
            )
        else:
            if location:
                self.add_location(path, location)

            self._resources["secret_scopes"][resource_name] = secret_scope


@overload
def secret_scope_mutator(
    function: Callable[[Bundle, "SecretScope"], "SecretScope"],
) -> ResourceMutator["SecretScope"]: ...


@overload
def secret_scope_mutator(
    function: Callable[["SecretScope"], "SecretScope"],
) -> ResourceMutator["SecretScope"]: ...


def secret_scope_mutator(function: Callable) -> ResourceMutator["SecretScope"]:
    """
    Decorator for defining mutator for secret_scopes. Function should return a new instance of the secret_scope
    with the desired changes, instead of mutating the input secret_scope.

    Example:

    .. code-block:: python

        @secret_scope_mutator
        def my_secret_scope_mutator(bundle: Bundle, secret_scope: SecretScope) -> SecretScope:
            return replace(secret_scope, ...)

    :param function: Function that mutates secret_scopes.
    """
    from databricks.bundles.secret_scopes._models.secret_scope import SecretScope

    return ResourceMutator(resource_type=SecretScope, function=function)
