# Code generated by pydabs-codegen. DO NOT EDIT.

from collections.abc import Callable
from typing import TYPE_CHECKING, Optional, overload

from databricks.bundles.core._bundle import Bundle
from databricks.bundles.core._location import Location
from databricks.bundles.core._resource_mutator import ResourceMutator
from databricks.bundles.core._transform import _transform

if TYPE_CHECKING:
    from databricks.bundles.core._resource_type import _ResourceType
    from databricks.bundles.synced_database_tables._models.synced_database_table import (
        SyncedDatabaseTable,
        SyncedDatabaseTableParam,
    )


def _resource_type() -> "_ResourceType":
    from databricks.bundles.core._resource_type import _ResourceType
    from databricks.bundles.synced_database_tables._models.synced_database_table import (
        SyncedDatabaseTable,
    )

    return _ResourceType(
        resource_type=SyncedDatabaseTable,
        singular_name="synced_database_table",
        plural_name="synced_database_tables",
    )


class _SyncedDatabaseTableResources:
    """
    Generated synced_database_table accessors, mixed into Resources.
    """

    # Provided by the Resources subclass; declared here so the generated methods
    # below type-check.
    _resources: dict[str, dict]

    if TYPE_CHECKING:

        def add_location(self, path: tuple[str, ...], location: Location) -> None: ...

        def add_diagnostic_error(
            self,
            msg: str,
            *,
            detail: Optional[str] = None,
            path: Optional[tuple[str, ...]] = None,
            location: Optional[Location] = None,
        ) -> None: ...

    @property
    def synced_database_tables(self) -> dict[str, "SyncedDatabaseTable"]:
        return self._resources["synced_database_tables"]

    def add_synced_database_table(
        self,
        resource_name: str,
        synced_database_table: "SyncedDatabaseTableParam",
        *,
        location: Optional[Location] = None,
    ) -> None:
        """
        Adds the resource synced_database_table to the collection of resources. Resource name must be unique across all synced_database_tables.

        :param resource_name: unique identifier for the synced_database_table
        :param synced_database_table: the synced_database_table to add, can be SyncedDatabaseTable or dict
        :param location: optional location of the synced_database_table in the source code
        """
        from databricks.bundles.synced_database_tables._models.synced_database_table import (
            SyncedDatabaseTable,
        )

        synced_database_table = _transform(SyncedDatabaseTable, synced_database_table)
        path = ("resources", "synced_database_tables", resource_name)
        location = location or Location.from_stack_frame(depth=1)

        if self._resources["synced_database_tables"].get(resource_name):
            self.add_diagnostic_error(
                msg=f"Duplicate resource name '{resource_name}' for resource 'synced_database_table'. Resource names must be unique.",
                location=location,
                path=path,
            )
        else:
            if location:
                self.add_location(path, location)

            self._resources["synced_database_tables"][resource_name] = (
                synced_database_table
            )


@overload
def synced_database_table_mutator(
    function: Callable[[Bundle, "SyncedDatabaseTable"], "SyncedDatabaseTable"],
) -> ResourceMutator["SyncedDatabaseTable"]: ...


@overload
def synced_database_table_mutator(
    function: Callable[["SyncedDatabaseTable"], "SyncedDatabaseTable"],
) -> ResourceMutator["SyncedDatabaseTable"]: ...


def synced_database_table_mutator(
    function: Callable,
) -> ResourceMutator["SyncedDatabaseTable"]:
    """
    Decorator for defining mutator for synced_database_tables. Function should return a new instance of the synced_database_table
    with the desired changes, instead of mutating the input synced_database_table.

    Example:

    .. code-block:: python

        @synced_database_table_mutator
        def my_synced_database_table_mutator(bundle: Bundle, synced_database_table: SyncedDatabaseTable) -> SyncedDatabaseTable:
            return replace(synced_database_table, ...)

    :param function: Function that mutates synced_database_tables.
    """
    from databricks.bundles.synced_database_tables._models.synced_database_table import (
        SyncedDatabaseTable,
    )

    return ResourceMutator(resource_type=SyncedDatabaseTable, function=function)
