# Code generated by pydabs-codegen. DO NOT EDIT.

from collections.abc import Callable
from typing import TYPE_CHECKING, Optional, overload

from databricks.bundles.core._bundle import Bundle
from databricks.bundles.core._location import Location
from databricks.bundles.core._resource_mutator import ResourceMutator
from databricks.bundles.core._transform import _transform

if TYPE_CHECKING:
    from databricks.bundles.core._resource_type import _ResourceType
    from databricks.bundles.vector_search_endpoints._models.vector_search_endpoint import (
        VectorSearchEndpoint,
        VectorSearchEndpointParam,
    )


def _resource_type() -> "_ResourceType":
    from databricks.bundles.core._resource_type import _ResourceType
    from databricks.bundles.vector_search_endpoints._models.vector_search_endpoint import (
        VectorSearchEndpoint,
    )

    return _ResourceType(
        resource_type=VectorSearchEndpoint,
        singular_name="vector_search_endpoint",
        plural_name="vector_search_endpoints",
    )


class _VectorSearchEndpointResources:
    """
    Generated vector_search_endpoint accessors, mixed into Resources.
    """

    # Provided by the Resources subclass; declared here so the generated methods
    # below type-check.
    _resources: dict[str, dict]

    if TYPE_CHECKING:

        def add_location(self, path: tuple[str, ...], location: Location) -> None: ...

        def add_diagnostic_error(
            self,
            msg: str,
            *,
            detail: Optional[str] = None,
            path: Optional[tuple[str, ...]] = None,
            location: Optional[Location] = None,
        ) -> None: ...

    @property
    def vector_search_endpoints(self) -> dict[str, "VectorSearchEndpoint"]:
        return self._resources["vector_search_endpoints"]

    def add_vector_search_endpoint(
        self,
        resource_name: str,
        vector_search_endpoint: "VectorSearchEndpointParam",
        *,
        location: Optional[Location] = None,
    ) -> None:
        """
        Adds the resource vector_search_endpoint to the collection of resources. Resource name must be unique across all vector_search_endpoints.

        :param resource_name: unique identifier for the vector_search_endpoint
        :param vector_search_endpoint: the vector_search_endpoint to add, can be VectorSearchEndpoint or dict
        :param location: optional location of the vector_search_endpoint in the source code
        """
        from databricks.bundles.vector_search_endpoints._models.vector_search_endpoint import (
            VectorSearchEndpoint,
        )

        vector_search_endpoint = _transform(
            VectorSearchEndpoint, vector_search_endpoint
        )
        path = ("resources", "vector_search_endpoints", resource_name)
        location = location or Location.from_stack_frame(depth=1)

        if self._resources["vector_search_endpoints"].get(resource_name):
            self.add_diagnostic_error(
                msg=f"Duplicate resource name '{resource_name}' for resource 'vector_search_endpoint'. Resource names must be unique.",
                location=location,
                path=path,
            )
        else:
            if location:
                self.add_location(path, location)

            self._resources["vector_search_endpoints"][resource_name] = (
                vector_search_endpoint
            )


@overload
def vector_search_endpoint_mutator(
    function: Callable[[Bundle, "VectorSearchEndpoint"], "VectorSearchEndpoint"],
) -> ResourceMutator["VectorSearchEndpoint"]: ...


@overload
def vector_search_endpoint_mutator(
    function: Callable[["VectorSearchEndpoint"], "VectorSearchEndpoint"],
) -> ResourceMutator["VectorSearchEndpoint"]: ...


def vector_search_endpoint_mutator(
    function: Callable,
) -> ResourceMutator["VectorSearchEndpoint"]:
    """
    Decorator for defining mutator for vector_search_endpoints. Function should return a new instance of the vector_search_endpoint
    with the desired changes, instead of mutating the input vector_search_endpoint.

    Example:

    .. code-block:: python

        @vector_search_endpoint_mutator
        def my_vector_search_endpoint_mutator(bundle: Bundle, vector_search_endpoint: VectorSearchEndpoint) -> VectorSearchEndpoint:
            return replace(vector_search_endpoint, ...)

    :param function: Function that mutates vector_search_endpoints.
    """
    from databricks.bundles.vector_search_endpoints._models.vector_search_endpoint import (
        VectorSearchEndpoint,
    )

    return ResourceMutator(resource_type=VectorSearchEndpoint, function=function)
