# Code generated by pydabs-codegen. DO NOT EDIT.

from collections.abc import Callable
from typing import TYPE_CHECKING, Optional, overload

from databricks.bundles.core._bundle import Bundle
from databricks.bundles.core._location import Location
from databricks.bundles.core._resource_mutator import ResourceMutator
from databricks.bundles.core._transform import _transform

if TYPE_CHECKING:
    from databricks.bundles.core._resource_type import _ResourceType
    from databricks.bundles.volumes._models.volume import Volume, VolumeParam


def _resource_type() -> "_ResourceType":
    from databricks.bundles.core._resource_type import _ResourceType
    from databricks.bundles.volumes._models.volume import Volume

    return _ResourceType(
        resource_type=Volume,
        singular_name="volume",
        plural_name="volumes",
    )


class _VolumeResources:
    """
    Generated volume accessors, mixed into Resources.
    """

    # Provided by the Resources subclass; declared here so the generated methods
    # below type-check.
    _resources: dict[str, dict]

    if TYPE_CHECKING:

        def add_location(self, path: tuple[str, ...], location: Location) -> None: ...

        def add_diagnostic_error(
            self,
            msg: str,
            *,
            detail: Optional[str] = None,
            path: Optional[tuple[str, ...]] = None,
            location: Optional[Location] = None,
        ) -> None: ...

    @property
    def volumes(self) -> dict[str, "Volume"]:
        return self._resources["volumes"]

    def add_volume(
        self,
        resource_name: str,
        volume: "VolumeParam",
        *,
        location: Optional[Location] = None,
    ) -> None:
        """
        Adds the resource volume to the collection of resources. Resource name must be unique across all volumes.

        :param resource_name: unique identifier for the volume
        :param volume: the volume to add, can be Volume or dict
        :param location: optional location of the volume in the source code
        """
        from databricks.bundles.volumes._models.volume import Volume

        volume = _transform(Volume, volume)
        path = ("resources", "volumes", resource_name)
        location = location or Location.from_stack_frame(depth=1)

        if self._resources["volumes"].get(resource_name):
            self.add_diagnostic_error(
                msg=f"Duplicate resource name '{resource_name}' for resource 'volume'. Resource names must be unique.",
                location=location,
                path=path,
            )
        else:
            if location:
                self.add_location(path, location)

            self._resources["volumes"][resource_name] = volume


@overload
def volume_mutator(
    function: Callable[[Bundle, "Volume"], "Volume"],
) -> ResourceMutator["Volume"]: ...


@overload
def volume_mutator(
    function: Callable[["Volume"], "Volume"],
) -> ResourceMutator["Volume"]: ...


def volume_mutator(function: Callable) -> ResourceMutator["Volume"]:
    """
    Decorator for defining mutator for volumes. Function should return a new instance of the volume
    with the desired changes, instead of mutating the input volume.

    Example:

    .. code-block:: python

        @volume_mutator
        def my_volume_mutator(bundle: Bundle, volume: Volume) -> Volume:
            return replace(volume, ...)

    :param function: Function that mutates volumes.
    """
    from databricks.bundles.volumes._models.volume import Volume

    return ResourceMutator(resource_type=Volume, function=function)
