// Auto-generated by AppKit - DO NOT EDIT
import "@databricks/app-kit-ui/react";

declare module "@databricks/app-kit-ui/react" {
  interface PluginRegistry {
    "analytics": {
      "/users/me/query/:query_key": {
          chunk_index: number;
          row_offset: number;
          row_count: number;
          data: any[];
      };
      "/query/:query_key": {
          chunk_index: number;
          row_offset: number;
          row_count: number;
          data: any[];
      };
    }
  }

  interface QueryRegistry {

    mocked_sales: {
        max_month_num: number;
    }[];
    hello_world: {
        value: string;
    }[];
  }
}
