Badness = "run_as is still set even though it's not in bundle and not in reset request"
Ignore = [".databricks/.gitignore"]

Local = true
Cloud = true
# Deploys a job with a job cluster and run_as configuration
RequiresClassic = true
RecordRequests = true

[EnvMatrix]
  DATABRICKS_BUNDLE_ENGINE = ["direct"]
