# Code generated by pydabs-codegen. DO NOT EDIT.

from dataclasses import dataclass
from typing import TYPE_CHECKING, TypedDict

from databricks.bundles.core._transform import _transform
from databricks.bundles.core._transform_to_json import _transform_to_json_value

if TYPE_CHECKING:
    from typing_extensions import Self


@dataclass(kw_only=True)
class ModelServiceConfigRoutingConfigTrafficSplitting:
    """
    Marker message selecting request-based traffic splitting across primary
    destinations. Split weights are read from each DestinationConfig.traffic_percentage.
    """

    @classmethod
    def from_dict(
        cls, value: "ModelServiceConfigRoutingConfigTrafficSplittingDict"
    ) -> "Self":
        return _transform(cls, value)

    def as_dict(self) -> "ModelServiceConfigRoutingConfigTrafficSplittingDict":
        return _transform_to_json_value(self)  # type:ignore


class ModelServiceConfigRoutingConfigTrafficSplittingDict(TypedDict, total=False):
    """"""


ModelServiceConfigRoutingConfigTrafficSplittingParam = (
    ModelServiceConfigRoutingConfigTrafficSplittingDict
    | ModelServiceConfigRoutingConfigTrafficSplitting
)
