# Code generated by pydabs-codegen. DO NOT EDIT.

from dataclasses import dataclass, field
from typing import TYPE_CHECKING, TypedDict

from databricks.bundles.core._transform import _transform
from databricks.bundles.core._transform_to_json import _transform_to_json_value
from databricks.bundles.core._variable import VariableOrList, VariableOrOptional
from databricks.bundles.model_services._models.model_service_config_destination_config import (
    ModelServiceConfigDestinationConfig,
    ModelServiceConfigDestinationConfigParam,
)
from databricks.bundles.model_services._models.model_service_config_fallback_config import (
    ModelServiceConfigFallbackConfig,
    ModelServiceConfigFallbackConfigParam,
)

if TYPE_CHECKING:
    from typing_extensions import Self


@dataclass(kw_only=True)
class ModelServiceConfigRoutingConfig:
    """
    Routing configuration for a model service, nesting destinations and
    fallback under a single sub-message.
    """

    destinations: VariableOrList[ModelServiceConfigDestinationConfig] = field(
        default_factory=list
    )
    """
    Primary routing destinations. At most 10 are allowed. At least one is
    required on Create. On Update, provide this list when replacing the full
    `config` or updating `config.routing.destinations`; other granular routing
    updates do not require resending destinations. The intermediate
    `config.routing` mask path is not supported.
    """

    fallback: VariableOrOptional[ModelServiceConfigFallbackConfig] = None
    """
    Fallback routing applied after a primary destination fails. Fallback
    destinations are tried in the listed order.
    """

    @classmethod
    def from_dict(cls, value: "ModelServiceConfigRoutingConfigDict") -> "Self":
        return _transform(cls, value)

    def as_dict(self) -> "ModelServiceConfigRoutingConfigDict":
        return _transform_to_json_value(self)  # type:ignore


class ModelServiceConfigRoutingConfigDict(TypedDict, total=False):
    """"""

    destinations: VariableOrList[ModelServiceConfigDestinationConfigParam]
    """
    Primary routing destinations. At most 10 are allowed. At least one is
    required on Create. On Update, provide this list when replacing the full
    `config` or updating `config.routing.destinations`; other granular routing
    updates do not require resending destinations. The intermediate
    `config.routing` mask path is not supported.
    """

    fallback: VariableOrOptional[ModelServiceConfigFallbackConfigParam]
    """
    Fallback routing applied after a primary destination fails. Fallback
    destinations are tried in the listed order.
    """


ModelServiceConfigRoutingConfigParam = (
    ModelServiceConfigRoutingConfigDict | ModelServiceConfigRoutingConfig
)
