# Code generated by pydabs-codegen. DO NOT EDIT.

from dataclasses import dataclass, field
from typing import TYPE_CHECKING, TypedDict

from databricks.bundles.core._transform import _transform
from databricks.bundles.core._transform_to_json import _transform_to_json_value
from databricks.bundles.core._variable import VariableOrList
from databricks.bundles.model_services._models.model_service_config_destination_config import (
    ModelServiceConfigDestinationConfig,
    ModelServiceConfigDestinationConfigParam,
)

if TYPE_CHECKING:
    from typing_extensions import Self


@dataclass(kw_only=True)
class ModelServiceConfigFallbackConfig:
    """
    Fallback routing, applied after the primary destination returns a retryable
    error. Traversal is in list order; the attempt count is the length of the
    list.
    """

    destinations: VariableOrList[ModelServiceConfigDestinationConfig] = field(
        default_factory=list
    )
    """
    :meta private: [EXPERIMENTAL]
    
    [Beta] Ordered list of fallback destinations. Traversal is in list order; the
    attempt count is the length of the list. At most 5 are allowed.
    """

    @classmethod
    def from_dict(cls, value: "ModelServiceConfigFallbackConfigDict") -> "Self":
        return _transform(cls, value)

    def as_dict(self) -> "ModelServiceConfigFallbackConfigDict":
        return _transform_to_json_value(self)  # type:ignore


class ModelServiceConfigFallbackConfigDict(TypedDict, total=False):
    """"""

    destinations: VariableOrList[ModelServiceConfigDestinationConfigParam]
    """
    :meta private: [EXPERIMENTAL]
    
    [Beta] Ordered list of fallback destinations. Traversal is in list order; the
    attempt count is the length of the list. At most 5 are allowed.
    """


ModelServiceConfigFallbackConfigParam = (
    ModelServiceConfigFallbackConfigDict | ModelServiceConfigFallbackConfig
)
