# Code generated by pydabs-codegen. DO NOT EDIT.

from dataclasses import dataclass
from typing import TYPE_CHECKING, TypedDict

from databricks.bundles.core._transform import _transform
from databricks.bundles.core._transform_to_json import _transform_to_json_value
from databricks.bundles.core._variable import VariableOr, VariableOrOptional
from databricks.bundles.model_services._models.model_service_config_destination_config_destination_type import (
    ModelServiceConfigDestinationConfigDestinationType,
    ModelServiceConfigDestinationConfigDestinationTypeParam,
)
from databricks.bundles.model_services._models.model_service_config_external_model_config import (
    ModelServiceConfigExternalModelConfig,
    ModelServiceConfigExternalModelConfigParam,
)
from databricks.bundles.model_services._models.model_service_config_pay_per_token_config import (
    ModelServiceConfigPayPerTokenConfig,
    ModelServiceConfigPayPerTokenConfigParam,
)
from databricks.bundles.model_services._models.model_service_config_provisioned_throughput_config import (
    ModelServiceConfigProvisionedThroughputConfig,
    ModelServiceConfigProvisionedThroughputConfigParam,
)

if TYPE_CHECKING:
    from typing_extensions import Self


@dataclass(kw_only=True)
class ModelServiceConfigDestinationConfig:
    """
    A destination the model service can route traffic to. Exactly one of the
    per-type configs inside `type_config` must be set, and it must match
    `destination_type`.
    """

    destination_type: VariableOr[ModelServiceConfigDestinationConfigDestinationType]
    """
    Backing-model category. Provide the matching type-specific configuration
    and leave the other type-specific configurations unset.
    """

    name: VariableOr[str]
    """
    User-facing label for this destination, used in routing references.
    """

    external_model_config: VariableOrOptional[ModelServiceConfigExternalModelConfig] = (
        None
    )
    """
    Configuration for an external model reached through a model provider service.
    """

    pay_per_token_config: VariableOrOptional[ModelServiceConfigPayPerTokenConfig] = None
    """
    Configuration for a pay-per-token Databricks foundation model.
    """

    provisioned_throughput_config: VariableOrOptional[
        ModelServiceConfigProvisionedThroughputConfig
    ] = None
    """
    Configuration for a provisioned-throughput Databricks foundation model.
    """

    traffic_percentage: VariableOrOptional[int] = None
    """
    Percentage of primary traffic sent to this destination, from 0 to 100.
    Required when there is more than one primary destination, in which case the
    primary percentages must sum to 100; a single primary destination receives
    all traffic. Fallback destinations are ordered and do not use this field.
    """

    @classmethod
    def from_dict(cls, value: "ModelServiceConfigDestinationConfigDict") -> "Self":
        return _transform(cls, value)

    def as_dict(self) -> "ModelServiceConfigDestinationConfigDict":
        return _transform_to_json_value(self)  # type:ignore


class ModelServiceConfigDestinationConfigDict(TypedDict, total=False):
    """"""

    destination_type: VariableOr[
        ModelServiceConfigDestinationConfigDestinationTypeParam
    ]
    """
    Backing-model category. Provide the matching type-specific configuration
    and leave the other type-specific configurations unset.
    """

    name: VariableOr[str]
    """
    User-facing label for this destination, used in routing references.
    """

    external_model_config: VariableOrOptional[
        ModelServiceConfigExternalModelConfigParam
    ]
    """
    Configuration for an external model reached through a model provider service.
    """

    pay_per_token_config: VariableOrOptional[ModelServiceConfigPayPerTokenConfigParam]
    """
    Configuration for a pay-per-token Databricks foundation model.
    """

    provisioned_throughput_config: VariableOrOptional[
        ModelServiceConfigProvisionedThroughputConfigParam
    ]
    """
    Configuration for a provisioned-throughput Databricks foundation model.
    """

    traffic_percentage: VariableOrOptional[int]
    """
    Percentage of primary traffic sent to this destination, from 0 to 100.
    Required when there is more than one primary destination, in which case the
    primary percentages must sum to 100; a single primary destination receives
    all traffic. Fallback destinations are ordered and do not use this field.
    """


ModelServiceConfigDestinationConfigParam = (
    ModelServiceConfigDestinationConfigDict | ModelServiceConfigDestinationConfig
)
