# Code generated by pydabs-codegen. DO NOT EDIT.

from enum import Enum
from typing import Literal


class RateLimitRateLimitKey(Enum):
    """
    Scope key for a rate limit.
    """

    RATE_LIMIT_KEY_USER = "RATE_LIMIT_KEY_USER"
    RATE_LIMIT_KEY_USER_GROUP = "RATE_LIMIT_KEY_USER_GROUP"
    RATE_LIMIT_KEY_SERVICE_PRINCIPAL = "RATE_LIMIT_KEY_SERVICE_PRINCIPAL"
    RATE_LIMIT_KEY_SERVICE = "RATE_LIMIT_KEY_SERVICE"
    RATE_LIMIT_KEY_USER_DEFAULT = "RATE_LIMIT_KEY_USER_DEFAULT"
    RATE_LIMIT_KEY_REQUEST_TAG = "RATE_LIMIT_KEY_REQUEST_TAG"


RateLimitRateLimitKeyParam = (
    Literal[
        "RATE_LIMIT_KEY_USER",
        "RATE_LIMIT_KEY_USER_GROUP",
        "RATE_LIMIT_KEY_SERVICE_PRINCIPAL",
        "RATE_LIMIT_KEY_SERVICE",
        "RATE_LIMIT_KEY_USER_DEFAULT",
        "RATE_LIMIT_KEY_REQUEST_TAG",
    ]
    | RateLimitRateLimitKey
)
