Local = false
Cloud = true

EnvMatrix.DATABRICKS_CLI_DEPLOYMENT = ["terraform"]  # requires "bundle summary"

Ignore = [
    "databricks.yml",
    "resources.yml",
    ".databricks/"
]

[[Repls]]
Old = "[0-9]{10,}"
New = "[NUMID]"

[[Repls]]
Old = "[0-9a-z]{12,}"
New = "[ALPHANUMID]"
