fields:
  name: [id]
  compute_size: [backend_default]
  forward_user_access_token: [backend_default]
  lifecycle: [backend_default]
  lifecycle.started: [backend_default]
  space:
    ignore_remote: managed
