fields:
  name: [id]
  endpoint_name: [immutable]
  index_type: [immutable]
  index_subtype: [immutable]
  primary_key: [immutable]
  delta_sync_index_spec: [immutable]
  direct_access_index_spec: [immutable]
  direct_access_index_spec.schema_json:
    ignore_remote: normalized_by_backend
