#!/bin/bash

touch dummy.whl
$CLI bundle deploy
job_id="$(read_id.py my_job)"


title "Modify task cluster num_workers from 2 to 5"
edit_resource.py jobs $job_id <<EOF
r["tasks"][0]["new_cluster"]["num_workers"] = 5
EOF

title "Detect and save changes"
$CLI bundle config-remote-sync --save

title "Updated configuration"
echo
cat databricks.yml
