Cloud = true
CloudSlow = true
RecordRequests = false
RunsOnDbr = true

Ignore = [
    "databricks.yml",
    "databricks.yml.tmpl",
    "hello_world.py",
]

[[Repls]]
Old = '/runs/\d+'
New = '/runs/[RUN_ID]'

[[Repls]]
Old = '\\\\'
New = '/'

[[Repls]]
Old = '\\'
New = '/'
