#!/bin/bash

touch dummy.whl
$CLI bundle deploy
job_id="$(read_id.py my_job)"


title "Add new tag and modify existing tag"
edit_resource.py jobs $job_id <<EOF
r["tags"]["env"] = "staging"
r["tags"]["team"] = "data-eng"
EOF

title "Detect and save changes"
echo
cp databricks.yml databricks.yml.backup
$CLI bundle config-remote-sync --save

title "Configuration changes"
echo
diff -u databricks.yml.backup databricks.yml || true
