# Code generated by pydabs-codegen. DO NOT EDIT.

from enum import Enum
from typing import Literal


class ClusterPermissionLevel(Enum):
    """
    Permission level
    """

    CAN_MANAGE = "CAN_MANAGE"
    CAN_RESTART = "CAN_RESTART"
    CAN_ATTACH_TO = "CAN_ATTACH_TO"


ClusterPermissionLevelParam = (
    Literal["CAN_MANAGE", "CAN_RESTART", "CAN_ATTACH_TO"] | ClusterPermissionLevel
)
