# Code generated by pydabs-codegen. DO NOT EDIT.

from dataclasses import dataclass, field
from typing import TYPE_CHECKING, TypedDict

from databricks.bundles.core._transform import _transform
from databricks.bundles.core._transform_to_json import _transform_to_json_value
from databricks.bundles.core._variable import VariableOrList, VariableOrOptional
from databricks.bundles.model_serving_endpoints._models.telemetry_feature import (
    TelemetryFeature,
    TelemetryFeatureParam,
)
from databricks.bundles.model_serving_endpoints._models.telemetry_inference_table_config import (
    TelemetryInferenceTableConfig,
    TelemetryInferenceTableConfigParam,
)
from databricks.bundles.model_serving_endpoints._models.unity_catalog_table_names import (
    UnityCatalogTableNames,
    UnityCatalogTableNamesParam,
)

if TYPE_CHECKING:
    from typing_extensions import Self


@dataclass(kw_only=True)
class TelemetryConfig:
    """"""

    enabled_telemetry_features: VariableOrList[TelemetryFeature] = field(
        default_factory=list
    )
    """
    [Public Preview] The telemetry signals to enable for this endpoint. If empty or omitted, all signals are
    enabled; otherwise only the listed signals are enabled.
    """

    inference_table_config: VariableOrOptional[TelemetryInferenceTableConfig] = None
    """
    [Public Preview] Configuration for inference table payload logging, including sampling.
    """

    table_names: VariableOrOptional[UnityCatalogTableNames] = None
    """
    [Public Preview] The Unity Catalog tables to which endpoint telemetry (logs, traces, and metrics) is exported.
    Provide this to create a new telemetry profile for the endpoint from the given tables.
    """

    telemetry_profile_id: VariableOrOptional[str] = None
    """
    [Public Preview] The ID of an existing telemetry profile to apply to this endpoint. Provide this to reuse a
    telemetry profile that has already been created, instead of specifying table_names.
    """

    @classmethod
    def from_dict(cls, value: "TelemetryConfigDict") -> "Self":
        return _transform(cls, value)

    def as_dict(self) -> "TelemetryConfigDict":
        return _transform_to_json_value(self)  # type:ignore


class TelemetryConfigDict(TypedDict, total=False):
    """"""

    enabled_telemetry_features: VariableOrList[TelemetryFeatureParam]
    """
    [Public Preview] The telemetry signals to enable for this endpoint. If empty or omitted, all signals are
    enabled; otherwise only the listed signals are enabled.
    """

    inference_table_config: VariableOrOptional[TelemetryInferenceTableConfigParam]
    """
    [Public Preview] Configuration for inference table payload logging, including sampling.
    """

    table_names: VariableOrOptional[UnityCatalogTableNamesParam]
    """
    [Public Preview] The Unity Catalog tables to which endpoint telemetry (logs, traces, and metrics) is exported.
    Provide this to create a new telemetry profile for the endpoint from the given tables.
    """

    telemetry_profile_id: VariableOrOptional[str]
    """
    [Public Preview] The ID of an existing telemetry profile to apply to this endpoint. Provide this to reuse a
    telemetry profile that has already been created, instead of specifying table_names.
    """


TelemetryConfigParam = TelemetryConfigDict | TelemetryConfig
