#!/bin/bash

touch dummy.whl
$CLI bundle deploy
pipeline_id="$(read_id.py my_pipeline)"


title "Modify pipeline target from dev_target to prod_target"
edit_resource.py pipelines $pipeline_id <<EOF
r["target"] = "prod_target"
EOF

title "Detect and save changes"
$CLI bundle config-remote-sync --save

title "Updated configuration"
echo
cat databricks.yml
