Local = true
Cloud = false

[Env]
  CATALOG_KEY = "#catalog"
  CONFIG_UPDATE = "pipelines/custom pipelines/newcustom"
  ING_KEY = "#ingestion_definition"
  PYTHONDONTWRITEBYTECODE = "1"
  PYTHONUNBUFFERED = "1"
  PYTHONUTF8 = "1"
  STORAGE_KEY = "storage"
  UV_PYTHON = "3.10"

[EnvMatrix]
  DATABRICKS_BUNDLE_ENGINE = ["terraform", "direct-exp"]
