# Code generated by pydabs-codegen. DO NOT EDIT.

from enum import Enum
from typing import Literal


class EndpointType(Enum):
    """
    Type of endpoint.
    """

    STORAGE_OPTIMIZED = "STORAGE_OPTIMIZED"
    STANDARD = "STANDARD"


EndpointTypeParam = Literal["STORAGE_OPTIMIZED", "STANDARD"] | EndpointType
