# Code generated by pydabs-codegen. DO NOT EDIT.

from dataclasses import dataclass
from typing import TYPE_CHECKING, TypedDict

from databricks.bundles.core._transform import _transform
from databricks.bundles.core._transform_to_json import _transform_to_json_value
from databricks.bundles.core._variable import VariableOr, VariableOrOptional
from databricks.bundles.vector_search_endpoints._models.vector_search_endpoint_permission_level import (
    VectorSearchEndpointPermissionLevel,
    VectorSearchEndpointPermissionLevelParam,
)

if TYPE_CHECKING:
    from typing_extensions import Self


@dataclass(kw_only=True)
class VectorSearchEndpointPermission:
    """"""

    level: VariableOr[VectorSearchEndpointPermissionLevel]

    group_name: VariableOrOptional[str] = None

    service_principal_name: VariableOrOptional[str] = None

    user_name: VariableOrOptional[str] = None

    @classmethod
    def from_dict(cls, value: "VectorSearchEndpointPermissionDict") -> "Self":
        return _transform(cls, value)

    def as_dict(self) -> "VectorSearchEndpointPermissionDict":
        return _transform_to_json_value(self)  # type:ignore


class VectorSearchEndpointPermissionDict(TypedDict, total=False):
    """"""

    level: VariableOr[VectorSearchEndpointPermissionLevelParam]

    group_name: VariableOrOptional[str]

    service_principal_name: VariableOrOptional[str]

    user_name: VariableOrOptional[str]


VectorSearchEndpointPermissionParam = (
    VectorSearchEndpointPermissionDict | VectorSearchEndpointPermission
)
