// Generated from Databricks Terraform provider schema. DO NOT EDIT.

package schema

type DataSources struct {
	AccountFederationPolicies              map[string]any `json:"databricks_account_federation_policies,omitempty"`
	AccountFederationPolicy                map[string]any `json:"databricks_account_federation_policy,omitempty"`
	AccountNetworkPolicies                 map[string]any `json:"databricks_account_network_policies,omitempty"`
	AccountNetworkPolicy                   map[string]any `json:"databricks_account_network_policy,omitempty"`
	AccountSettingUserPreferenceV2         map[string]any `json:"databricks_account_setting_user_preference_v2,omitempty"`
	AccountSettingV2                       map[string]any `json:"databricks_account_setting_v2,omitempty"`
	AlertV2                                map[string]any `json:"databricks_alert_v2,omitempty"`
	AlertsV2                               map[string]any `json:"databricks_alerts_v2,omitempty"`
	App                                    map[string]any `json:"databricks_app,omitempty"`
	AppSpace                               map[string]any `json:"databricks_app_space,omitempty"`
	AppSpaces                              map[string]any `json:"databricks_app_spaces,omitempty"`
	Apps                                   map[string]any `json:"databricks_apps,omitempty"`
	AppsSettingsCustomTemplate             map[string]any `json:"databricks_apps_settings_custom_template,omitempty"`
	AppsSettingsCustomTemplates            map[string]any `json:"databricks_apps_settings_custom_templates,omitempty"`
	AwsAssumeRolePolicy                    map[string]any `json:"databricks_aws_assume_role_policy,omitempty"`
	AwsBucketPolicy                        map[string]any `json:"databricks_aws_bucket_policy,omitempty"`
	AwsCrossaccountPolicy                  map[string]any `json:"databricks_aws_crossaccount_policy,omitempty"`
	AwsUnityCatalogAssumeRolePolicy        map[string]any `json:"databricks_aws_unity_catalog_assume_role_policy,omitempty"`
	AwsUnityCatalogPolicy                  map[string]any `json:"databricks_aws_unity_catalog_policy,omitempty"`
	BudgetPolicies                         map[string]any `json:"databricks_budget_policies,omitempty"`
	BudgetPolicy                           map[string]any `json:"databricks_budget_policy,omitempty"`
	Catalog                                map[string]any `json:"databricks_catalog,omitempty"`
	Catalogs                               map[string]any `json:"databricks_catalogs,omitempty"`
	Cluster                                map[string]any `json:"databricks_cluster,omitempty"`
	ClusterPolicy                          map[string]any `json:"databricks_cluster_policy,omitempty"`
	Clusters                               map[string]any `json:"databricks_clusters,omitempty"`
	CurrentConfig                          map[string]any `json:"databricks_current_config,omitempty"`
	CurrentMetastore                       map[string]any `json:"databricks_current_metastore,omitempty"`
	CurrentUser                            map[string]any `json:"databricks_current_user,omitempty"`
	Dashboards                             map[string]any `json:"databricks_dashboards,omitempty"`
	DataClassificationCatalogConfig        map[string]any `json:"databricks_data_classification_catalog_config,omitempty"`
	DataQualityMonitor                     map[string]any `json:"databricks_data_quality_monitor,omitempty"`
	DataQualityMonitors                    map[string]any `json:"databricks_data_quality_monitors,omitempty"`
	DataQualityRefresh                     map[string]any `json:"databricks_data_quality_refresh,omitempty"`
	DataQualityRefreshes                   map[string]any `json:"databricks_data_quality_refreshes,omitempty"`
	DatabaseDatabaseCatalog                map[string]any `json:"databricks_database_database_catalog,omitempty"`
	DatabaseDatabaseCatalogs               map[string]any `json:"databricks_database_database_catalogs,omitempty"`
	DatabaseInstance                       map[string]any `json:"databricks_database_instance,omitempty"`
	DatabaseInstances                      map[string]any `json:"databricks_database_instances,omitempty"`
	DatabaseSyncedDatabaseTable            map[string]any `json:"databricks_database_synced_database_table,omitempty"`
	DatabaseSyncedDatabaseTables           map[string]any `json:"databricks_database_synced_database_tables,omitempty"`
	DbfsFile                               map[string]any `json:"databricks_dbfs_file,omitempty"`
	DbfsFilePaths                          map[string]any `json:"databricks_dbfs_file_paths,omitempty"`
	Directory                              map[string]any `json:"databricks_directory,omitempty"`
	Endpoint                               map[string]any `json:"databricks_endpoint,omitempty"`
	Endpoints                              map[string]any `json:"databricks_endpoints,omitempty"`
	EntityTagAssignment                    map[string]any `json:"databricks_entity_tag_assignment,omitempty"`
	EntityTagAssignments                   map[string]any `json:"databricks_entity_tag_assignments,omitempty"`
	ExternalLocation                       map[string]any `json:"databricks_external_location,omitempty"`
	ExternalLocations                      map[string]any `json:"databricks_external_locations,omitempty"`
	ExternalMetadata                       map[string]any `json:"databricks_external_metadata,omitempty"`
	ExternalMetadatas                      map[string]any `json:"databricks_external_metadatas,omitempty"`
	FeatureEngineeringFeature              map[string]any `json:"databricks_feature_engineering_feature,omitempty"`
	FeatureEngineeringFeatures             map[string]any `json:"databricks_feature_engineering_features,omitempty"`
	FeatureEngineeringKafkaConfig          map[string]any `json:"databricks_feature_engineering_kafka_config,omitempty"`
	FeatureEngineeringKafkaConfigs         map[string]any `json:"databricks_feature_engineering_kafka_configs,omitempty"`
	FeatureEngineeringMaterializedFeature  map[string]any `json:"databricks_feature_engineering_materialized_feature,omitempty"`
	FeatureEngineeringMaterializedFeatures map[string]any `json:"databricks_feature_engineering_materialized_features,omitempty"`
	Functions                              map[string]any `json:"databricks_functions,omitempty"`
	Group                                  map[string]any `json:"databricks_group,omitempty"`
	InstancePool                           map[string]any `json:"databricks_instance_pool,omitempty"`
	InstanceProfiles                       map[string]any `json:"databricks_instance_profiles,omitempty"`
	Job                                    map[string]any `json:"databricks_job,omitempty"`
	Jobs                                   map[string]any `json:"databricks_jobs,omitempty"`
	KnowledgeAssistant                     map[string]any `json:"databricks_knowledge_assistant,omitempty"`
	KnowledgeAssistantKnowledgeSource      map[string]any `json:"databricks_knowledge_assistant_knowledge_source,omitempty"`
	KnowledgeAssistantKnowledgeSources     map[string]any `json:"databricks_knowledge_assistant_knowledge_sources,omitempty"`
	KnowledgeAssistants                    map[string]any `json:"databricks_knowledge_assistants,omitempty"`
	MaterializedFeaturesFeatureTag         map[string]any `json:"databricks_materialized_features_feature_tag,omitempty"`
	MaterializedFeaturesFeatureTags        map[string]any `json:"databricks_materialized_features_feature_tags,omitempty"`
	Metastore                              map[string]any `json:"databricks_metastore,omitempty"`
	Metastores                             map[string]any `json:"databricks_metastores,omitempty"`
	MlflowExperiment                       map[string]any `json:"databricks_mlflow_experiment,omitempty"`
	MlflowModel                            map[string]any `json:"databricks_mlflow_model,omitempty"`
	MlflowModels                           map[string]any `json:"databricks_mlflow_models,omitempty"`
	MwsCredentials                         map[string]any `json:"databricks_mws_credentials,omitempty"`
	MwsNetworkConnectivityConfig           map[string]any `json:"databricks_mws_network_connectivity_config,omitempty"`
	MwsNetworkConnectivityConfigs          map[string]any `json:"databricks_mws_network_connectivity_configs,omitempty"`
	MwsWorkspaces                          map[string]any `json:"databricks_mws_workspaces,omitempty"`
	NodeType                               map[string]any `json:"databricks_node_type,omitempty"`
	Notebook                               map[string]any `json:"databricks_notebook,omitempty"`
	NotebookPaths                          map[string]any `json:"databricks_notebook_paths,omitempty"`
	NotificationDestinations               map[string]any `json:"databricks_notification_destinations,omitempty"`
	OnlineStore                            map[string]any `json:"databricks_online_store,omitempty"`
	OnlineStores                           map[string]any `json:"databricks_online_stores,omitempty"`
	Pipelines                              map[string]any `json:"databricks_pipelines,omitempty"`
	PolicyInfo                             map[string]any `json:"databricks_policy_info,omitempty"`
	PolicyInfos                            map[string]any `json:"databricks_policy_infos,omitempty"`
	PostgresBranch                         map[string]any `json:"databricks_postgres_branch,omitempty"`
	PostgresBranches                       map[string]any `json:"databricks_postgres_branches,omitempty"`
	PostgresDatabase                       map[string]any `json:"databricks_postgres_database,omitempty"`
	PostgresDatabases                      map[string]any `json:"databricks_postgres_databases,omitempty"`
	PostgresEndpoint                       map[string]any `json:"databricks_postgres_endpoint,omitempty"`
	PostgresEndpoints                      map[string]any `json:"databricks_postgres_endpoints,omitempty"`
	PostgresProject                        map[string]any `json:"databricks_postgres_project,omitempty"`
	PostgresProjects                       map[string]any `json:"databricks_postgres_projects,omitempty"`
	QualityMonitorV2                       map[string]any `json:"databricks_quality_monitor_v2,omitempty"`
	QualityMonitorsV2                      map[string]any `json:"databricks_quality_monitors_v2,omitempty"`
	RegisteredModel                        map[string]any `json:"databricks_registered_model,omitempty"`
	RegisteredModelVersions                map[string]any `json:"databricks_registered_model_versions,omitempty"`
	RfaAccessRequestDestinations           map[string]any `json:"databricks_rfa_access_request_destinations,omitempty"`
	Schema                                 map[string]any `json:"databricks_schema,omitempty"`
	Schemas                                map[string]any `json:"databricks_schemas,omitempty"`
	ServicePrincipal                       map[string]any `json:"databricks_service_principal,omitempty"`
	ServicePrincipalFederationPolicies     map[string]any `json:"databricks_service_principal_federation_policies,omitempty"`
	ServicePrincipalFederationPolicy       map[string]any `json:"databricks_service_principal_federation_policy,omitempty"`
	ServicePrincipals                      map[string]any `json:"databricks_service_principals,omitempty"`
	ServingEndpoints                       map[string]any `json:"databricks_serving_endpoints,omitempty"`
	Share                                  map[string]any `json:"databricks_share,omitempty"`
	Shares                                 map[string]any `json:"databricks_shares,omitempty"`
	SparkVersion                           map[string]any `json:"databricks_spark_version,omitempty"`
	SqlWarehouse                           map[string]any `json:"databricks_sql_warehouse,omitempty"`
	SqlWarehouses                          map[string]any `json:"databricks_sql_warehouses,omitempty"`
	StorageCredential                      map[string]any `json:"databricks_storage_credential,omitempty"`
	StorageCredentials                     map[string]any `json:"databricks_storage_credentials,omitempty"`
	Table                                  map[string]any `json:"databricks_table,omitempty"`
	Tables                                 map[string]any `json:"databricks_tables,omitempty"`
	TagPolicies                            map[string]any `json:"databricks_tag_policies,omitempty"`
	TagPolicy                              map[string]any `json:"databricks_tag_policy,omitempty"`
	User                                   map[string]any `json:"databricks_user,omitempty"`
	Users                                  map[string]any `json:"databricks_users,omitempty"`
	Views                                  map[string]any `json:"databricks_views,omitempty"`
	Volume                                 map[string]any `json:"databricks_volume,omitempty"`
	Volumes                                map[string]any `json:"databricks_volumes,omitempty"`
	WarehousesDefaultWarehouseOverride     map[string]any `json:"databricks_warehouses_default_warehouse_override,omitempty"`
	WarehousesDefaultWarehouseOverrides    map[string]any `json:"databricks_warehouses_default_warehouse_overrides,omitempty"`
	WorkspaceEntityTagAssignment           map[string]any `json:"databricks_workspace_entity_tag_assignment,omitempty"`
	WorkspaceEntityTagAssignments          map[string]any `json:"databricks_workspace_entity_tag_assignments,omitempty"`
	WorkspaceNetworkOption                 map[string]any `json:"databricks_workspace_network_option,omitempty"`
	WorkspaceSettingV2                     map[string]any `json:"databricks_workspace_setting_v2,omitempty"`
	Zones                                  map[string]any `json:"databricks_zones,omitempty"`
}
