resources:
  pipelines:
    # relative paths should get translated to remote paths
    one:
      configuration:
        spark.sql.ansi.enabled: "true"
      root_path: "../src/pipeline_one"
      libraries:
        - glob:
            include: "../src/pipeline_one/a/b/c/**"

    # absolute paths should remain as-is
    two:
      configuration:
        spark.sql.ansi.enabled: "true"
      root_path: "/Workspace/Users/me@company.com/src"
      libraries:
        - glob:
            include: "/Workspace/Users/me@company.com/a/b/c/**"
