[[Server]]
Pattern = "GET /api/2.2/jobs/get"
Response.Body = '''
{
    "job_id": 11223344,
    "settings": {
        "name": "sparkpythonjob",
        "tasks": [
            {
                "task_key": "workspace_file_task",
                "spark_python_task": {
                    "python_file": "/Workspace/Users/tester@databricks.com/outjob.py"
                }
            },
            {
                "task_key": "cloud_uri_task",
                "spark_python_task": {
                    "python_file": "dbfs:/FileStore/job.py"
                }
            }
        ]
    }
}
'''

[[Server]]
Pattern = "GET /api/2.0/workspace/get-status"
Response.Body = '''
{
    "path": "/Workspace/Users/tester@databricks.com/outjob.py",
    "object_type": "FILE",
    "language": "PYTHON",
    "repos_export_format": "SOURCE"
}
'''

[[Server]]
Pattern = "GET /api/2.0/workspace/export"
Response.Body = '''
print("Hello, World!")
'''
