# Code generated by pydabs-codegen. DO NOT EDIT.

from dataclasses import dataclass, field
from typing import TYPE_CHECKING, Any, TypedDict

from databricks.bundles.cluster_policies._models.cluster_policy_permission import (
    ClusterPolicyPermission,
    ClusterPolicyPermissionParam,
)
from databricks.bundles.cluster_policies._models.library import Library, LibraryParam
from databricks.bundles.cluster_policies._models.lifecycle import (
    Lifecycle,
    LifecycleParam,
)
from databricks.bundles.core._resource import Resource
from databricks.bundles.core._transform import _transform
from databricks.bundles.core._transform_to_json import _transform_to_json_value
from databricks.bundles.core._variable import VariableOrList, VariableOrOptional

if TYPE_CHECKING:
    from typing_extensions import Self


@dataclass(kw_only=True)
class ClusterPolicy(Resource):
    """"""

    definition: VariableOrOptional[Any] = None
    """
    Policy definition document expressed in [Databricks Cluster Policy Definition Language](https://docs.databricks.com/administration-guide/clusters/policy-definition.html).
    """

    description: VariableOrOptional[str] = None
    """
    Additional human-readable description of the cluster policy.
    """

    libraries: VariableOrList[Library] = field(default_factory=list)
    """
    A list of libraries to be installed on the next cluster restart that uses this policy. The maximum number of libraries is 500.
    """

    lifecycle: VariableOrOptional[Lifecycle] = None

    max_clusters_per_user: VariableOrOptional[int] = None
    """
    Max number of clusters per user that can be active using this policy. If not present, there is no max limit.
    """

    name: VariableOrOptional[str] = None
    """
    Cluster Policy name requested by the user. This has to be unique. Length must be between 1 and 100
    characters.
    """

    permissions: VariableOrList[ClusterPolicyPermission] = field(default_factory=list)
    """
    The permissions to apply to this resource.
    """

    policy_family_definition_overrides: VariableOrOptional[Any] = None
    """
    Policy definition JSON document expressed in [Databricks Policy Definition Language](https://docs.databricks.com/administration-guide/clusters/policy-definition.html).
    The JSON document must be passed as a string and cannot be embedded in the requests.
    
    You can use this to customize the policy definition inherited from the policy family.
    Policy rules specified here are merged into the inherited policy definition.
    """

    policy_family_id: VariableOrOptional[str] = None
    """
    ID of the policy family. The cluster policy's policy definition inherits the policy
    family's policy definition.
    
    Cannot be used with `definition`. Use `policy_family_definition_overrides` instead to
    customize the policy definition.
    """

    @classmethod
    def from_dict(cls, value: "ClusterPolicyDict") -> "Self":
        return _transform(cls, value)

    def as_dict(self) -> "ClusterPolicyDict":
        return _transform_to_json_value(self)  # type:ignore


class ClusterPolicyDict(TypedDict, total=False):
    """"""

    definition: VariableOrOptional[Any]
    """
    Policy definition document expressed in [Databricks Cluster Policy Definition Language](https://docs.databricks.com/administration-guide/clusters/policy-definition.html).
    """

    description: VariableOrOptional[str]
    """
    Additional human-readable description of the cluster policy.
    """

    libraries: VariableOrList[LibraryParam]
    """
    A list of libraries to be installed on the next cluster restart that uses this policy. The maximum number of libraries is 500.
    """

    lifecycle: VariableOrOptional[LifecycleParam]

    max_clusters_per_user: VariableOrOptional[int]
    """
    Max number of clusters per user that can be active using this policy. If not present, there is no max limit.
    """

    name: VariableOrOptional[str]
    """
    Cluster Policy name requested by the user. This has to be unique. Length must be between 1 and 100
    characters.
    """

    permissions: VariableOrList[ClusterPolicyPermissionParam]
    """
    The permissions to apply to this resource.
    """

    policy_family_definition_overrides: VariableOrOptional[Any]
    """
    Policy definition JSON document expressed in [Databricks Policy Definition Language](https://docs.databricks.com/administration-guide/clusters/policy-definition.html).
    The JSON document must be passed as a string and cannot be embedded in the requests.
    
    You can use this to customize the policy definition inherited from the policy family.
    Policy rules specified here are merged into the inherited policy definition.
    """

    policy_family_id: VariableOrOptional[str]
    """
    ID of the policy family. The cluster policy's policy definition inherits the policy
    family's policy definition.
    
    Cannot be used with `definition`. Use `policy_family_definition_overrides` instead to
    customize the policy definition.
    """


ClusterPolicyParam = ClusterPolicyDict | ClusterPolicy
