# Code generated by pydabs-codegen. DO NOT EDIT.

from dataclasses import dataclass
from typing import TYPE_CHECKING, TypedDict

from databricks.bundles.cluster_policies._models.cluster_policy_permission_level import (
    ClusterPolicyPermissionLevel,
    ClusterPolicyPermissionLevelParam,
)
from databricks.bundles.core._transform import _transform
from databricks.bundles.core._transform_to_json import _transform_to_json_value
from databricks.bundles.core._variable import VariableOr, VariableOrOptional

if TYPE_CHECKING:
    from typing_extensions import Self


@dataclass(kw_only=True)
class ClusterPolicyPermission:
    """"""

    level: VariableOr[ClusterPolicyPermissionLevel]
    """
    The permission level to apply. Cluster policies only support `CAN_USE`.
    """

    group_name: VariableOrOptional[str] = None
    """
    The name of the group granted the permission level.
    """

    service_principal_name: VariableOrOptional[str] = None
    """
    The name of the service principal granted the permission level.
    """

    user_name: VariableOrOptional[str] = None
    """
    The name of the user granted the permission level.
    """

    @classmethod
    def from_dict(cls, value: "ClusterPolicyPermissionDict") -> "Self":
        return _transform(cls, value)

    def as_dict(self) -> "ClusterPolicyPermissionDict":
        return _transform_to_json_value(self)  # type:ignore


class ClusterPolicyPermissionDict(TypedDict, total=False):
    """"""

    level: VariableOr[ClusterPolicyPermissionLevelParam]
    """
    The permission level to apply. Cluster policies only support `CAN_USE`.
    """

    group_name: VariableOrOptional[str]
    """
    The name of the group granted the permission level.
    """

    service_principal_name: VariableOrOptional[str]
    """
    The name of the service principal granted the permission level.
    """

    user_name: VariableOrOptional[str]
    """
    The name of the user granted the permission level.
    """


ClusterPolicyPermissionParam = ClusterPolicyPermissionDict | ClusterPolicyPermission
