#!/bin/bash

touch dummy.whl
$CLI bundle deploy -t dev
job_id="$(read_id.py my_job)"

title "Initial configuration"
cat databricks.yml

title "Modify fields in target override"
edit_resource.py jobs $job_id <<EOF
r["max_concurrent_runs"] = 10
r["tags"]["env"] = "staging"
r["tags"]["owner"] = "data-team"
EOF

title "Detect and save changes"
$CLI bundle config-remote-sync -t dev --save

title "Updated configuration"
cat databricks.yml
