#!/bin/bash

touch dummy.whl
$CLI bundle deploy
job_id="$(read_id.py my_job)"

title "Modify job parameters: change catalog default and add new parameter"
edit_resource.py jobs $job_id <<EOF
r["parameters"][0]["default"] = "staging"
r["parameters"].append({"name": "schema", "default": "default"})
EOF

title "Detect and save changes"
$CLI bundle config-remote-sync --save

title "Updated configuration"
echo
cat databricks.yml
