#!/usr/bin/env bash
set -euo pipefail

trace $CLI bundle validate

trace $CLI bundle deploy
trace jq -s '.[] | select(.path=="/api/2.2/jobs/create") | .body.environments' out.requests.txt
trace $CLI bundle validate -o json | jq '.resources.jobs.test_job.environments[0].spec.dependencies'
rm out.requests.txt
