// Package bundlecleanup discovers and destroys bundle deployments left by acceptance runs.
package bundlecleanup

import (
	"context"
	"errors"
	"fmt"
	"math/rand/v2"
	"os"
	"os/exec"
	"path"
	"path/filepath"
	"regexp"
	"slices"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/databricks/cli/libs/env"
	"github.com/databricks/cli/libs/iamutil"
	"github.com/databricks/cli/libs/log"
	"github.com/databricks/databricks-sdk-go"
	"github.com/databricks/databricks-sdk-go/apierr"
	"github.com/databricks/databricks-sdk-go/service/workspace"
)

const randomSuffixLen = 4

var (
	ciRunID   = regexp.MustCompile(`^[0-9]{1,11}$`)
	localBase = "local"
	alphabet  = "0123456789abcdefghijklmnopqrstuvwxyz"
)

// CleanPrefix returns the run-wide prefix used by the standalone cleaner.
// A valid GitHub run ID produces exactly ci<run-id>x. Without one, callers must
// supply the exact local prefix generated by NewBundleNamePrefix.
func CleanPrefix(ctx context.Context) (string, error) {
	runID := env.Get(ctx, "GITHUB_RUN_ID")
	if runID == "" {
		return "", nil
	}
	if !ciRunID.MatchString(runID) {
		return "", fmt.Errorf("GITHUB_RUN_ID %q is not a valid run id (must be 1-11 digits)", runID)
	}
	return "ci" + runID + "x", nil
}

// NewBundleNamePrefix builds the prefix stamped into each cloud acceptance
// bundle name. CI prefixes are exactly ci<run-id>x. Local prefixes contain the
// base36 Unix time and four random lowercase alphanumeric characters, so a
// standalone cleanup can be given the exact value from the log.
func NewBundleNamePrefix(ctx context.Context) (string, error) {
	prefix, err := CleanPrefix(ctx)
	if err != nil {
		return "", err
	}
	if prefix != "" {
		return prefix, nil
	}
	return localBase + strconv.FormatInt(time.Now().Unix(), 36) + randomSuffix(), nil
}

// ValidatePrefix verifies that prefix can identify one concrete run. On CI it
// must equal the current run-wide prefix. A local prefix must have the exact
// local<base36-time><four-random-characters> shape produced above.
func ValidatePrefix(prefix, runID string) error {
	if runID != "" {
		if !ciRunID.MatchString(runID) {
			return fmt.Errorf("GITHUB_RUN_ID %q is not a valid run id (must be 1-11 digits)", runID)
		}
		want := "ci" + runID + "x"
		if prefix != want {
			return fmt.Errorf("prefix %q does not match CI run prefix %q", prefix, want)
		}
		return nil
	}
	if !strings.HasPrefix(prefix, localBase) {
		return fmt.Errorf("prefix %q is neither a CI run prefix nor a local run prefix", prefix)
	}
	local := strings.TrimPrefix(prefix, localBase)
	if len(local) <= randomSuffixLen {
		return fmt.Errorf("local prefix %q is missing its base36 timestamp or random suffix", prefix)
	}
	stamp, suffix := local[:len(local)-randomSuffixLen], local[len(local)-randomSuffixLen:]
	if _, err := strconv.ParseInt(stamp, 36, 64); err != nil {
		return fmt.Errorf("local prefix %q has an invalid base36 timestamp: %w", prefix, err)
	}
	for _, char := range suffix {
		if !strings.ContainsRune(alphabet, char) {
			return fmt.Errorf("local prefix %q has an invalid random suffix", prefix)
		}
	}
	return nil
}

func randomSuffix() string {
	suffix := make([]byte, randomSuffixLen)
	for i := range suffix {
		suffix[i] = alphabet[rand.IntN(len(alphabet))]
	}
	return string(suffix)
}

// WorkspaceLister is the part of the SDK workspace API used by discovery.
type WorkspaceLister interface {
	ListAll(context.Context, workspace.ListWorkspaceRequest) ([]workspace.ObjectInfo, error)
}

// CleanBundles finds every bundle deployed under the current user's bundle
// roots with prefix and destroys each one using execPath.
func CleanBundles(ctx context.Context, execPath, prefix string) error {
	start := time.Now()

	w, err := databricks.NewWorkspaceClient()
	if err != nil {
		return fmt.Errorf("cannot create workspace client: %w", err)
	}
	me, err := iamutil.GetCurrentUser(ctx, w)
	if err != nil {
		return fmt.Errorf("cannot resolve current user: %w", err)
	}

	bundleRoots := []string{
		"/Workspace/Users/" + me.UserName + "/.bundle",
		"/Workspace/Shared/" + me.UserName + "/.bundle",
	}

	var roots []string
	for _, bundleRoot := range bundleRoots {
		for _, child := range ListChildDirs(ctx, w.Workspace, bundleRoot) {
			if strings.HasPrefix(path.Base(child), prefix) {
				roots = append(roots, FindDeploymentRoots(ctx, w.Workspace, child)...)
			}
		}
	}
	slices.Sort(roots)

	log.Infof(ctx, "bundle cleanup: found %d deployment(s) with prefix %q", len(roots), prefix)

	const maxConcurrentDestroys = 20
	sem := make(chan struct{}, maxConcurrentDestroys)
	var wg sync.WaitGroup
	var mu sync.Mutex
	var failed []string
	for _, root := range roots {
		sem <- struct{}{}
		wg.Go(func() {
			defer func() { <-sem }()
			log.Infof(ctx, "destroying %s", root)
			if out, err := DestroyBundle(execPath, root); err != nil {
				log.Infof(ctx, "destroy failed: %s\n%s", root, out)
				mu.Lock()
				failed = append(failed, root)
				mu.Unlock()
			}
		})
	}
	wg.Wait()

	slices.Sort(failed)
	log.Infof(ctx, "bundle cleanup: destroyed %d/%d deployment(s) in %s", len(roots)-len(failed), len(roots), time.Since(start))
	if len(failed) > 0 {
		return fmt.Errorf("failed to destroy %d deployment(s): %s", len(failed), strings.Join(failed, ", "))
	}
	return nil
}

// FindDeploymentRoots walks the workspace tree under dir and returns deployment roots.
func FindDeploymentRoots(ctx context.Context, w WorkspaceLister, dir string) []string {
	var roots []string
	var childDirs []string
	isDeployment := false
	for _, child := range ListChildDirs(ctx, w, dir) {
		if base := path.Base(child); base == "state" || base == "files" {
			isDeployment = true
			continue
		}
		childDirs = append(childDirs, child)
	}
	if isDeployment {
		roots = append(roots, dir)
	}

	for _, child := range childDirs {
		roots = append(roots, FindDeploymentRoots(ctx, w, child)...)
	}
	return roots
}

// ListChildDirs returns immediate child directories. A missing directory is
// silent; other listing failures are logged and do not stop the sweep.
func ListChildDirs(ctx context.Context, w WorkspaceLister, dir string) []string {
	objects, err := w.ListAll(ctx, workspace.ListWorkspaceRequest{Path: dir})
	if err != nil {
		if !errors.Is(err, apierr.ErrNotFound) {
			log.Infof(ctx, "WARNING: bundle cleanup incomplete, cannot list %s: %s", dir, err)
		}
		return nil
	}
	var dirs []string
	for _, object := range objects {
		if object.ObjectType == workspace.ObjectTypeDirectory {
			dirs = append(dirs, object.Path)
		}
	}
	return dirs
}

// DestroyBundle destroys the bundle at rootPath using the CLI binary.
func DestroyBundle(execPath, rootPath string) ([]byte, error) {
	dir, err := os.MkdirTemp("", "bundle-clean")
	if err != nil {
		return nil, err
	}
	defer os.RemoveAll(dir)

	databricksYML := "bundle:\n  name: cleanup\nworkspace:\n  root_path: " + rootPath + "\ntargets:\n  default: {}\n"
	if err := os.WriteFile(filepath.Join(dir, "databricks.yml"), []byte(databricksYML), 0o644); err != nil {
		return nil, err
	}

	cmd := exec.Command(execPath, "bundle", "destroy", "--target", "default", "--auto-approve", "--force-lock")
	cmd.Dir = dir
	cmd.Env = os.Environ()
	return cmd.CombinedOutput()
}
