# Code generated by pydabs-codegen. DO NOT EDIT.

from dataclasses import dataclass, field
from typing import TYPE_CHECKING, TypedDict

from databricks.bundles.core._transform import _transform
from databricks.bundles.core._transform_to_json import _transform_to_json_value
from databricks.bundles.core._variable import VariableOrList, VariableOrOptional
from databricks.bundles.mcp_services._models.mcp_service_config_source_connection import (
    McpServiceConfigSourceConnection,
    McpServiceConfigSourceConnectionParam,
)
from databricks.bundles.mcp_services._models.rate_limit import RateLimit, RateLimitParam

if TYPE_CHECKING:
    from typing_extensions import Self


@dataclass(kw_only=True)
class McpServiceConfig:
    """
    Operational configuration for an MCP service. Groups the source reference,
    tool selectors, and rate limits -- the fields that configure how the MCP
    service behaves at invocation time.
    """

    include_tool_selectors: VariableOrList[str] = field(default_factory=list)
    """
    Tool names or prefix patterns to expose from the MCP server. Use exact
    tool names or prefix patterns such as `read_*`. An empty list exposes all
    tools. At most 1,024 selectors are allowed, and each selector can contain
    at most 256 characters.
    """

    rate_limits: VariableOrList[RateLimit] = field(default_factory=list)
    """
    Rate limits for tool invocations. Supported scopes are user, group, service
    principal, the service as a whole, and each user by default. Request and
    token limits are supported. Empty when no rate limit is configured.
    """

    source_connection: VariableOrOptional[McpServiceConfigSourceConnection] = None
    """
    Unity Catalog connection referencing the MCP server. Required on Create.
    """

    @classmethod
    def from_dict(cls, value: "McpServiceConfigDict") -> "Self":
        return _transform(cls, value)

    def as_dict(self) -> "McpServiceConfigDict":
        return _transform_to_json_value(self)  # type:ignore


class McpServiceConfigDict(TypedDict, total=False):
    """"""

    include_tool_selectors: VariableOrList[str]
    """
    Tool names or prefix patterns to expose from the MCP server. Use exact
    tool names or prefix patterns such as `read_*`. An empty list exposes all
    tools. At most 1,024 selectors are allowed, and each selector can contain
    at most 256 characters.
    """

    rate_limits: VariableOrList[RateLimitParam]
    """
    Rate limits for tool invocations. Supported scopes are user, group, service
    principal, the service as a whole, and each user by default. Request and
    token limits are supported. Empty when no rate limit is configured.
    """

    source_connection: VariableOrOptional[McpServiceConfigSourceConnectionParam]
    """
    Unity Catalog connection referencing the MCP server. Required on Create.
    """


McpServiceConfigParam = McpServiceConfigDict | McpServiceConfig
