# Code generated by pydabs-codegen. DO NOT EDIT.

from dataclasses import dataclass
from typing import TYPE_CHECKING, TypedDict

from databricks.bundles.core._resource import Resource
from databricks.bundles.core._transform import _transform
from databricks.bundles.core._transform_to_json import _transform_to_json_value
from databricks.bundles.core._variable import VariableOr, VariableOrOptional
from databricks.bundles.mcp_services._models.lifecycle import Lifecycle, LifecycleParam
from databricks.bundles.mcp_services._models.mcp_service_config import (
    McpServiceConfig,
    McpServiceConfigParam,
)

if TYPE_CHECKING:
    from typing_extensions import Self


@dataclass(kw_only=True)
class McpService(Resource):
    """"""

    mcp_service_id: VariableOr[str]

    parent: VariableOr[str]

    comment: VariableOrOptional[str] = None

    config: VariableOrOptional[McpServiceConfig] = None

    lifecycle: VariableOrOptional[Lifecycle] = None

    @classmethod
    def from_dict(cls, value: "McpServiceDict") -> "Self":
        return _transform(cls, value)

    def as_dict(self) -> "McpServiceDict":
        return _transform_to_json_value(self)  # type:ignore


class McpServiceDict(TypedDict, total=False):
    """"""

    mcp_service_id: VariableOr[str]

    parent: VariableOr[str]

    comment: VariableOrOptional[str]

    config: VariableOrOptional[McpServiceConfigParam]

    lifecycle: VariableOrOptional[LifecycleParam]


McpServiceParam = McpServiceDict | McpService
