#!/bin/bash

touch dummy.whl
$CLI bundle deploy
job_id="$(read_id.py my_job)"
pipeline_id="$(read_id.py my_pipeline)"

title "Modify pipeline_task full_refresh to True"
edit_resource.py jobs $job_id <<EOF
r["tasks"][0]["pipeline_task"]["full_refresh"] = True
EOF

title "Modify pipeline development to True"
edit_resource.py pipelines $pipeline_id <<EOF
r["development"] = True
EOF


title "Detect and save changes"
$CLI bundle config-remote-sync --save

title "Updated configuration"
echo
cat databricks.yml
