Local = true
Cloud = true
RequiresUnityCatalog = true
EnvMatrix.DATABRICKS_BUNDLE_ENGINE = ["terraform", "direct"]
EnvMatrix.DLT = ["yes", "no"]
EnvMatrix.NBOOK = ["yes", "no"]
EnvMatrix.PY = ["yes", "no"]
EnvMatrix.READPLAN = ["", "1"]
