// Code generated by Databricks SDK Generator. DO NOT EDIT.

package files

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"iter"
	"log/slog"
	"net/http"
	"net/url"
	"strconv"
	"sync"

	"github.com/databricks/cli/libs/tmp/auth"
	"github.com/databricks/cli/libs/tmp/files/internal"
	"github.com/databricks/cli/libs/tmp/options/call"
	"github.com/databricks/cli/libs/tmp/options/client"
	"github.com/databricks/cli/libs/tmp/options/internaloptions"
	"github.com/databricks/sdk-go/core/clientinfo"
)

type Client struct {
	internalClient

	// extensions is a per-client store for hand-written mixins to attach
	// lazily-built state. Keys should be unexported types private to the
	// mixin, following the context.Value convention, to avoid collisions.
	// The zero value is ready to use; it is safe for concurrent use.
	extensions sync.Map
}

type internalClient struct {
	httpClient  *http.Client
	credentials auth.Credentials
	logger      *slog.Logger
	userAgent   string
	host        string
	workspaceID string
	accountID   string
}

func NewClient(ctx context.Context, opts ...client.Option) (*Client, error) {
	cfg := internaloptions.ClientOptions{}
	for _, opt := range opts {
		if err := opt(&cfg); err != nil {
			return nil, err
		}
	}
	if err := cfg.Resolve(); err != nil {
		return nil, err
	}
	info, err := clientinfo.Default().With(
		internal.ModuleName, internal.Version,
		"auth", cfg.Credentials.Name(),
	)
	if err != nil {
		return nil, err
	}

	return &Client{
		internalClient: internalClient{
			httpClient:  cfg.HTTPClient,
			credentials: cfg.Credentials,
			logger:      cfg.Logger,
			userAgent:   info.String(),
			host:        cfg.Host,
			workspaceID: cfg.WorkspaceID,
			accountID:   cfg.AccountID,
		},
	}, nil
}

// Appends a block of data to the stream specified by the input handle. If the
// handle does not exist, this call will throw an exception with
// “RESOURCE_DOES_NOT_EXIST“.
//
// If the block of data exceeds 1 MB, this call will throw an exception with
// “MAX_BLOCK_SIZE_EXCEEDED“.
func (c *internalClient) AddBlock(ctx context.Context, req *AddBlockRequest, opts ...call.Option) (*AddBlockResponse, error) {
	body, err := json.Marshal(addBlockRequestToWire(req))
	if err != nil {
		return nil, err
	}

	headers := http.Header{}
	if c.userAgent != "" {
		headers.Set("User-Agent", c.userAgent)
	}
	headers.Set("Content-Type", "application/json")

	baseURL, err := url.Parse(c.host)
	if err != nil {
		return nil, err
	}
	baseURL.Path = "/api/2.0/dbfs/add-block"
	queryParams := url.Values{}
	baseURL.RawQuery = queryParams.Encode()
	urlStr := baseURL.String()

	var resp *AddBlockResponse

	call := func(ctx context.Context) error {
		httpReq, err := newHTTPRequest(ctx, httpRequestOptions{
			Method:      "POST",
			URL:         urlStr,
			Credentials: c.credentials,
			Headers:     headers,
			Body:        bytes.NewBuffer(body),
		})
		if err != nil {
			return err
		}

		respBody, _, err := executeHTTPCall(httpCallOptions{
			req:    httpReq,
			client: c.httpClient,
			logger: c.logger,
		})
		if err != nil {
			return err
		}
		var wireResp addBlockResponseWire
		if err := unmarshalResponse(respBody, &wireResp); err != nil {
			return err
		}
		resp = addBlockResponseFromWire(&wireResp)
		return nil
	}

	if err := executeCall(ctx, call, opts); err != nil {
		return nil, err
	}
	return resp, nil
}

// Closes the stream specified by the input handle. If the handle does not
// exist, this call throws an exception with “RESOURCE_DOES_NOT_EXIST“.
func (c *internalClient) Close(ctx context.Context, req *CloseRequest, opts ...call.Option) (*CloseResponse, error) {
	body, err := json.Marshal(closeRequestToWire(req))
	if err != nil {
		return nil, err
	}

	headers := http.Header{}
	if c.userAgent != "" {
		headers.Set("User-Agent", c.userAgent)
	}
	headers.Set("Content-Type", "application/json")

	baseURL, err := url.Parse(c.host)
	if err != nil {
		return nil, err
	}
	baseURL.Path = "/api/2.0/dbfs/close"
	queryParams := url.Values{}
	baseURL.RawQuery = queryParams.Encode()
	urlStr := baseURL.String()

	var resp *CloseResponse

	call := func(ctx context.Context) error {
		httpReq, err := newHTTPRequest(ctx, httpRequestOptions{
			Method:      "POST",
			URL:         urlStr,
			Credentials: c.credentials,
			Headers:     headers,
			Body:        bytes.NewBuffer(body),
		})
		if err != nil {
			return err
		}

		respBody, _, err := executeHTTPCall(httpCallOptions{
			req:    httpReq,
			client: c.httpClient,
			logger: c.logger,
		})
		if err != nil {
			return err
		}
		var wireResp closeResponseWire
		if err := unmarshalResponse(respBody, &wireResp); err != nil {
			return err
		}
		resp = closeResponseFromWire(&wireResp)
		return nil
	}

	if err := executeCall(ctx, call, opts); err != nil {
		return nil, err
	}
	return resp, nil
}

// Opens a stream to write to a file and returns a handle to this stream. There
// is a 10 minute idle timeout on this handle. If a file or directory already
// exists on the given path and __overwrite__ is set to false, this call will
// throw an exception with “RESOURCE_ALREADY_EXISTS“.
//
// A typical workflow for file upload would be:
//
// 1. Issue a “create“ call and get a handle. 2. Issue one or more
// “add-block“ calls with the handle you have. 3. Issue a “close“ call with
// the handle you have.
func (c *internalClient) Create(ctx context.Context, req *CreateRequest, opts ...call.Option) (*CreateResponse, error) {
	body, err := json.Marshal(createRequestToWire(req))
	if err != nil {
		return nil, err
	}

	headers := http.Header{}
	if c.userAgent != "" {
		headers.Set("User-Agent", c.userAgent)
	}
	headers.Set("Content-Type", "application/json")

	baseURL, err := url.Parse(c.host)
	if err != nil {
		return nil, err
	}
	baseURL.Path = "/api/2.0/dbfs/create"
	queryParams := url.Values{}
	baseURL.RawQuery = queryParams.Encode()
	urlStr := baseURL.String()

	var resp *CreateResponse

	call := func(ctx context.Context) error {
		httpReq, err := newHTTPRequest(ctx, httpRequestOptions{
			Method:      "POST",
			URL:         urlStr,
			Credentials: c.credentials,
			Headers:     headers,
			Body:        bytes.NewBuffer(body),
		})
		if err != nil {
			return err
		}

		respBody, _, err := executeHTTPCall(httpCallOptions{
			req:    httpReq,
			client: c.httpClient,
			logger: c.logger,
		})
		if err != nil {
			return err
		}
		var wireResp createResponseWire
		if err := unmarshalResponse(respBody, &wireResp); err != nil {
			return err
		}
		resp = createResponseFromWire(&wireResp)
		return nil
	}

	if err := executeCall(ctx, call, opts); err != nil {
		return nil, err
	}
	return resp, nil
}

// Delete the file or directory (optionally recursively delete all files in the
// directory). This call throws an exception with `IO_ERROR` if the path is a
// non-empty directory and `recursive` is set to `false` or on other similar
// errors.
//
// When you delete a large number of files, the delete operation is done in
// increments. The call returns a response after approximately 45 seconds with
// an error message (503 Service Unavailable) asking you to re-invoke the delete
// operation until the directory structure is fully deleted.
//
// For operations that delete more than 10K files, we discourage using the DBFS
// REST API, but advise you to perform such operations in the context of a
// cluster, using the [File system utility
// (dbutils.fs)](/dev-tools/databricks-utils.html#dbutils-fs). `dbutils.fs`
// covers the functional scope of the DBFS REST API, but from notebooks. Running
// such operations using notebooks provides better control and manageability,
// such as selective deletes, and the possibility to automate periodic delete
// jobs.
func (c *internalClient) Delete(ctx context.Context, req *DeleteRequest, opts ...call.Option) (*DeleteResponse, error) {
	body, err := json.Marshal(deleteRequestToWire(req))
	if err != nil {
		return nil, err
	}

	headers := http.Header{}
	if c.userAgent != "" {
		headers.Set("User-Agent", c.userAgent)
	}
	headers.Set("Content-Type", "application/json")

	baseURL, err := url.Parse(c.host)
	if err != nil {
		return nil, err
	}
	baseURL.Path = "/api/2.0/dbfs/delete"
	queryParams := url.Values{}
	baseURL.RawQuery = queryParams.Encode()
	urlStr := baseURL.String()

	var resp *DeleteResponse

	call := func(ctx context.Context) error {
		httpReq, err := newHTTPRequest(ctx, httpRequestOptions{
			Method:      "POST",
			URL:         urlStr,
			Credentials: c.credentials,
			Headers:     headers,
			Body:        bytes.NewBuffer(body),
		})
		if err != nil {
			return err
		}

		respBody, _, err := executeHTTPCall(httpCallOptions{
			req:    httpReq,
			client: c.httpClient,
			logger: c.logger,
		})
		if err != nil {
			return err
		}
		var wireResp deleteResponseWire
		if err := unmarshalResponse(respBody, &wireResp); err != nil {
			return err
		}
		resp = deleteResponseFromWire(&wireResp)
		return nil
	}

	if err := executeCall(ctx, call, opts); err != nil {
		return nil, err
	}
	return resp, nil
}

// Gets the file information for a file or directory. If the file or directory
// does not exist, this call throws an exception with `RESOURCE_DOES_NOT_EXIST`.
func (c *internalClient) GetStatus(ctx context.Context, req *GetStatusRequest, opts ...call.Option) (*GetStatusResponse, error) {

	headers := http.Header{}
	if c.userAgent != "" {
		headers.Set("User-Agent", c.userAgent)
	}
	headers.Set("Content-Type", "application/json")

	baseURL, err := url.Parse(c.host)
	if err != nil {
		return nil, err
	}
	baseURL.Path = "/api/2.0/dbfs/get-status"
	queryParams := url.Values{}
	if err := addQueryValue(queryParams, "path", req.Path); err != nil {
		return nil, err
	}
	baseURL.RawQuery = queryParams.Encode()
	urlStr := baseURL.String()

	var resp *GetStatusResponse

	call := func(ctx context.Context) error {
		httpReq, err := newHTTPRequest(ctx, httpRequestOptions{
			Method:      "GET",
			URL:         urlStr,
			Credentials: c.credentials,
			Headers:     headers,
		})
		if err != nil {
			return err
		}

		respBody, _, err := executeHTTPCall(httpCallOptions{
			req:    httpReq,
			client: c.httpClient,
			logger: c.logger,
		})
		if err != nil {
			return err
		}
		var wireResp getStatusResponseWire
		if err := unmarshalResponse(respBody, &wireResp); err != nil {
			return err
		}
		resp = getStatusResponseFromWire(&wireResp)
		return nil
	}

	if err := executeCall(ctx, call, opts); err != nil {
		return nil, err
	}
	return resp, nil
}

// List the contents of a directory, or details of the file. If the file or
// directory does not exist, this call throws an exception with
// `RESOURCE_DOES_NOT_EXIST`.
//
// When calling list on a large directory, the list operation will time out
// after approximately 60 seconds. We strongly recommend using list only on
// directories containing less than 10K files and discourage using the DBFS REST
// API for operations that list more than 10K files. Instead, we recommend that
// you perform such operations in the context of a cluster, using the [File
// system utility (dbutils.fs)](/dev-tools/databricks-utils.html#dbutils-fs),
// which provides the same functionality without timing out.
func (c *internalClient) List(ctx context.Context, req *ListStatusRequest, opts ...call.Option) (*ListStatusResponse, error) {

	headers := http.Header{}
	if c.userAgent != "" {
		headers.Set("User-Agent", c.userAgent)
	}
	headers.Set("Content-Type", "application/json")

	baseURL, err := url.Parse(c.host)
	if err != nil {
		return nil, err
	}
	baseURL.Path = "/api/2.0/dbfs/list"
	queryParams := url.Values{}
	if err := addQueryValue(queryParams, "path", req.Path); err != nil {
		return nil, err
	}
	baseURL.RawQuery = queryParams.Encode()
	urlStr := baseURL.String()

	var resp *ListStatusResponse

	call := func(ctx context.Context) error {
		httpReq, err := newHTTPRequest(ctx, httpRequestOptions{
			Method:      "GET",
			URL:         urlStr,
			Credentials: c.credentials,
			Headers:     headers,
		})
		if err != nil {
			return err
		}

		respBody, _, err := executeHTTPCall(httpCallOptions{
			req:    httpReq,
			client: c.httpClient,
			logger: c.logger,
		})
		if err != nil {
			return err
		}
		var wireResp listStatusResponseWire
		if err := unmarshalResponse(respBody, &wireResp); err != nil {
			return err
		}
		resp = listStatusResponseFromWire(&wireResp)
		return nil
	}

	if err := executeCall(ctx, call, opts); err != nil {
		return nil, err
	}
	return resp, nil
}

// Creates the given directory and necessary parent directories if they do not
// exist. If a file (not a directory) exists at any prefix of the input path,
// this call throws an exception with `RESOURCE_ALREADY_EXISTS`. **Note**: If
// this operation fails, it might have succeeded in creating some of the
// necessary parent directories.
func (c *internalClient) Mkdirs(ctx context.Context, req *MkDirsRequest, opts ...call.Option) (*MkDirsResponse, error) {
	body, err := json.Marshal(mkDirsRequestToWire(req))
	if err != nil {
		return nil, err
	}

	headers := http.Header{}
	if c.userAgent != "" {
		headers.Set("User-Agent", c.userAgent)
	}
	headers.Set("Content-Type", "application/json")

	baseURL, err := url.Parse(c.host)
	if err != nil {
		return nil, err
	}
	baseURL.Path = "/api/2.0/dbfs/mkdirs"
	queryParams := url.Values{}
	baseURL.RawQuery = queryParams.Encode()
	urlStr := baseURL.String()

	var resp *MkDirsResponse

	call := func(ctx context.Context) error {
		httpReq, err := newHTTPRequest(ctx, httpRequestOptions{
			Method:      "POST",
			URL:         urlStr,
			Credentials: c.credentials,
			Headers:     headers,
			Body:        bytes.NewBuffer(body),
		})
		if err != nil {
			return err
		}

		respBody, _, err := executeHTTPCall(httpCallOptions{
			req:    httpReq,
			client: c.httpClient,
			logger: c.logger,
		})
		if err != nil {
			return err
		}
		var wireResp mkDirsResponseWire
		if err := unmarshalResponse(respBody, &wireResp); err != nil {
			return err
		}
		resp = mkDirsResponseFromWire(&wireResp)
		return nil
	}

	if err := executeCall(ctx, call, opts); err != nil {
		return nil, err
	}
	return resp, nil
}

// Moves a file from one location to another location within DBFS. If the source
// file does not exist, this call throws an exception with
// `RESOURCE_DOES_NOT_EXIST`. If a file already exists in the destination path,
// this call throws an exception with `RESOURCE_ALREADY_EXISTS`. If the given
// source path is a directory, this call always recursively moves all files.
func (c *internalClient) Move(ctx context.Context, req *MoveRequest, opts ...call.Option) (*MoveResponse, error) {
	body, err := json.Marshal(moveRequestToWire(req))
	if err != nil {
		return nil, err
	}

	headers := http.Header{}
	if c.userAgent != "" {
		headers.Set("User-Agent", c.userAgent)
	}
	headers.Set("Content-Type", "application/json")

	baseURL, err := url.Parse(c.host)
	if err != nil {
		return nil, err
	}
	baseURL.Path = "/api/2.0/dbfs/move"
	queryParams := url.Values{}
	baseURL.RawQuery = queryParams.Encode()
	urlStr := baseURL.String()

	var resp *MoveResponse

	call := func(ctx context.Context) error {
		httpReq, err := newHTTPRequest(ctx, httpRequestOptions{
			Method:      "POST",
			URL:         urlStr,
			Credentials: c.credentials,
			Headers:     headers,
			Body:        bytes.NewBuffer(body),
		})
		if err != nil {
			return err
		}

		respBody, _, err := executeHTTPCall(httpCallOptions{
			req:    httpReq,
			client: c.httpClient,
			logger: c.logger,
		})
		if err != nil {
			return err
		}
		var wireResp moveResponseWire
		if err := unmarshalResponse(respBody, &wireResp); err != nil {
			return err
		}
		resp = moveResponseFromWire(&wireResp)
		return nil
	}

	if err := executeCall(ctx, call, opts); err != nil {
		return nil, err
	}
	return resp, nil
}

// Uploads a file through the use of multipart form post. It is mainly used for
// streaming uploads, but can also be used as a convenient single call for data
// upload.
//
// Alternatively you can pass contents as base64 string.
//
// The amount of data that can be passed (when not streaming) using the
// __contents__ parameter is limited to 1 MB. `MAX_BLOCK_SIZE_EXCEEDED` will be
// thrown if this limit is exceeded.
//
// If you want to upload large files, use the streaming upload. For details, see
// :method:dbfs/create, :method:dbfs/addBlock, :method:dbfs/close.
func (c *internalClient) Put(ctx context.Context, req *PutRequest, opts ...call.Option) (*PutResponse, error) {
	body, err := json.Marshal(putRequestToWire(req))
	if err != nil {
		return nil, err
	}

	headers := http.Header{}
	if c.userAgent != "" {
		headers.Set("User-Agent", c.userAgent)
	}
	headers.Set("Content-Type", "application/json")

	baseURL, err := url.Parse(c.host)
	if err != nil {
		return nil, err
	}
	baseURL.Path = "/api/2.0/dbfs/put"
	queryParams := url.Values{}
	baseURL.RawQuery = queryParams.Encode()
	urlStr := baseURL.String()

	var resp *PutResponse

	call := func(ctx context.Context) error {
		httpReq, err := newHTTPRequest(ctx, httpRequestOptions{
			Method:      "POST",
			URL:         urlStr,
			Credentials: c.credentials,
			Headers:     headers,
			Body:        bytes.NewBuffer(body),
		})
		if err != nil {
			return err
		}

		respBody, _, err := executeHTTPCall(httpCallOptions{
			req:    httpReq,
			client: c.httpClient,
			logger: c.logger,
		})
		if err != nil {
			return err
		}
		var wireResp putResponseWire
		if err := unmarshalResponse(respBody, &wireResp); err != nil {
			return err
		}
		resp = putResponseFromWire(&wireResp)
		return nil
	}

	if err := executeCall(ctx, call, opts); err != nil {
		return nil, err
	}
	return resp, nil
}

// Returns the contents of a file. If the file does not exist, this call throws
// an exception with `RESOURCE_DOES_NOT_EXIST`. If the path is a directory, the
// read length is negative, or if the offset is negative, this call throws an
// exception with `INVALID_PARAMETER_VALUE`. If the read length exceeds 1 MB,
// this call throws an exception with `MAX_READ_SIZE_EXCEEDED`.
//
// If `offset + length` exceeds the number of bytes in a file, it reads the
// contents until the end of file.
func (c *internalClient) Read(ctx context.Context, req *ReadRequest, opts ...call.Option) (*ReadResponse, error) {

	headers := http.Header{}
	if c.userAgent != "" {
		headers.Set("User-Agent", c.userAgent)
	}
	headers.Set("Content-Type", "application/json")

	baseURL, err := url.Parse(c.host)
	if err != nil {
		return nil, err
	}
	baseURL.Path = "/api/2.0/dbfs/read"
	queryParams := url.Values{}
	if err := addQueryValue(queryParams, "path", req.Path); err != nil {
		return nil, err
	}
	if err := addQueryValue(queryParams, "offset", req.Offset); err != nil {
		return nil, err
	}
	if err := addQueryValue(queryParams, "length", req.Length); err != nil {
		return nil, err
	}
	baseURL.RawQuery = queryParams.Encode()
	urlStr := baseURL.String()

	var resp *ReadResponse

	call := func(ctx context.Context) error {
		httpReq, err := newHTTPRequest(ctx, httpRequestOptions{
			Method:      "GET",
			URL:         urlStr,
			Credentials: c.credentials,
			Headers:     headers,
		})
		if err != nil {
			return err
		}

		respBody, _, err := executeHTTPCall(httpCallOptions{
			req:    httpReq,
			client: c.httpClient,
			logger: c.logger,
		})
		if err != nil {
			return err
		}
		var wireResp readResponseWire
		if err := unmarshalResponse(respBody, &wireResp); err != nil {
			return err
		}
		resp = readResponseFromWire(&wireResp)
		return nil
	}

	if err := executeCall(ctx, call, opts); err != nil {
		return nil, err
	}
	return resp, nil
}

// Creates an empty directory. If necessary, also creates any parent directories
// of the new, empty directory (like the shell command `mkdir -p`). If called on
// an existing directory, returns a success response; this method is idempotent
// (it will succeed if the directory already exists).
func (c *internalClient) CreateDirectory(ctx context.Context, req *CreateDirectoryRequest, opts ...call.Option) (*CreateDirectoryResponse, error) {

	headers := http.Header{}
	if c.userAgent != "" {
		headers.Set("User-Agent", c.userAgent)
	}
	headers.Set("Content-Type", "application/json")

	baseURL, err := url.Parse(c.host)
	if err != nil {
		return nil, err
	}
	pb := pathBuilder{}
	pb.literal("/api/2.0/fs/directories")
	pb.multiSegments(*req.DirectoryPath)
	baseURL.Path, baseURL.RawPath = pb.build()
	queryParams := url.Values{}
	baseURL.RawQuery = queryParams.Encode()
	urlStr := baseURL.String()

	var resp *CreateDirectoryResponse

	call := func(ctx context.Context) error {
		httpReq, err := newHTTPRequest(ctx, httpRequestOptions{
			Method:      "PUT",
			URL:         urlStr,
			Credentials: c.credentials,
			Headers:     headers,
		})
		if err != nil {
			return err
		}

		respBody, _, err := executeHTTPCall(httpCallOptions{
			req:    httpReq,
			client: c.httpClient,
			logger: c.logger,
		})
		if err != nil {
			return err
		}
		var wireResp createDirectoryResponseWire
		if err := unmarshalResponse(respBody, &wireResp); err != nil {
			return err
		}
		resp = createDirectoryResponseFromWire(&wireResp)
		return nil
	}

	if err := executeCall(ctx, call, opts); err != nil {
		return nil, err
	}
	return resp, nil
}

// Deletes an empty directory.
//
// To delete a non-empty directory, first delete all of its contents. This can
// be done by listing the directory contents and deleting each file and
// subdirectory recursively.
func (c *internalClient) DeleteDirectory(ctx context.Context, req *DeleteDirectoryRequest, opts ...call.Option) (*DeleteDirectoryResponse, error) {

	headers := http.Header{}
	if c.userAgent != "" {
		headers.Set("User-Agent", c.userAgent)
	}
	headers.Set("Content-Type", "application/json")

	baseURL, err := url.Parse(c.host)
	if err != nil {
		return nil, err
	}
	pb := pathBuilder{}
	pb.literal("/api/2.0/fs/directories")
	pb.multiSegments(*req.DirectoryPath)
	baseURL.Path, baseURL.RawPath = pb.build()
	queryParams := url.Values{}
	baseURL.RawQuery = queryParams.Encode()
	urlStr := baseURL.String()

	var resp *DeleteDirectoryResponse

	call := func(ctx context.Context) error {
		httpReq, err := newHTTPRequest(ctx, httpRequestOptions{
			Method:      "DELETE",
			URL:         urlStr,
			Credentials: c.credentials,
			Headers:     headers,
		})
		if err != nil {
			return err
		}

		respBody, _, err := executeHTTPCall(httpCallOptions{
			req:    httpReq,
			client: c.httpClient,
			logger: c.logger,
		})
		if err != nil {
			return err
		}
		var wireResp deleteDirectoryResponseWire
		if err := unmarshalResponse(respBody, &wireResp); err != nil {
			return err
		}
		resp = deleteDirectoryResponseFromWire(&wireResp)
		return nil
	}

	if err := executeCall(ctx, call, opts); err != nil {
		return nil, err
	}
	return resp, nil
}

// Deletes a file. If the request is successful, there is no response body.
func (c *internalClient) DeleteFile(ctx context.Context, req *DeleteFileRequest, opts ...call.Option) (*DeleteFileResponse, error) {

	headers := http.Header{}
	if c.userAgent != "" {
		headers.Set("User-Agent", c.userAgent)
	}
	headers.Set("Content-Type", "application/json")

	baseURL, err := url.Parse(c.host)
	if err != nil {
		return nil, err
	}
	pb := pathBuilder{}
	pb.literal("/api/2.0/fs/files")
	pb.multiSegments(*req.FilePath)
	baseURL.Path, baseURL.RawPath = pb.build()
	queryParams := url.Values{}
	baseURL.RawQuery = queryParams.Encode()
	urlStr := baseURL.String()

	var resp *DeleteFileResponse

	call := func(ctx context.Context) error {
		httpReq, err := newHTTPRequest(ctx, httpRequestOptions{
			Method:      "DELETE",
			URL:         urlStr,
			Credentials: c.credentials,
			Headers:     headers,
		})
		if err != nil {
			return err
		}

		respBody, _, err := executeHTTPCall(httpCallOptions{
			req:    httpReq,
			client: c.httpClient,
			logger: c.logger,
		})
		if err != nil {
			return err
		}
		var wireResp deleteFileResponseWire
		if err := unmarshalResponse(respBody, &wireResp); err != nil {
			return err
		}
		resp = deleteFileResponseFromWire(&wireResp)
		return nil
	}

	if err := executeCall(ctx, call, opts); err != nil {
		return nil, err
	}
	return resp, nil
}

// Downloads a file. The file contents are the response body. This is a standard
// HTTP file download, not a JSON RPC. It supports the Range and
// If-Unmodified-Since HTTP headers.
func (c *internalClient) DownloadFile(ctx context.Context, req *DownloadFileRequest, opts ...call.Option) (*DownloadFileResponse, error) {

	headers := http.Header{}
	if c.userAgent != "" {
		headers.Set("User-Agent", c.userAgent)
	}
	headers.Set("Content-Type", "application/json")
	headers.Set("Accept", "application/octet-stream")
	if req.Range != nil {
		headers.Set("Range", fmt.Sprintf("%v", *req.Range))
	}
	if req.IfUnmodifiedSince != nil {
		headers.Set("If-Unmodified-Since", fmt.Sprintf("%v", *req.IfUnmodifiedSince))
	}

	baseURL, err := url.Parse(c.host)
	if err != nil {
		return nil, err
	}
	pb := pathBuilder{}
	pb.literal("/api/2.0/fs/files")
	pb.multiSegments(*req.FilePath)
	baseURL.Path, baseURL.RawPath = pb.build()
	queryParams := url.Values{}
	baseURL.RawQuery = queryParams.Encode()
	urlStr := baseURL.String()

	var resp *DownloadFileResponse

	call := func(ctx context.Context) error {
		httpReq, err := newHTTPRequest(ctx, httpRequestOptions{
			Method:      "GET",
			URL:         urlStr,
			Credentials: c.credentials,
			Headers:     headers,
		})
		if err != nil {
			return err
		}

		httpResp, err := executeStreamingHTTPCall(httpCallOptions{
			req:    httpReq,
			client: c.httpClient,
			logger: c.logger,
		})
		if err != nil {
			return err
		}
		resp = &DownloadFileResponse{}
		resp.Contents = httpResp.Body
		if v := httpResp.Header.Get("content-length"); v != "" {
			n, err := strconv.ParseInt(v, 10, 64)
			if err != nil {
				httpResp.Body.Close() // avoid leaking the connection
				return err
			}
			resp.ContentLength = &n
		}
		if v := httpResp.Header.Get("content-type"); v != "" {
			h := v
			resp.ContentType = &h
		}
		if v := httpResp.Header.Get("last-modified"); v != "" {
			h := v
			resp.LastModified = &h
		}
		return nil
	}

	if err := executeCall(ctx, call, opts); err != nil {
		return nil, err
	}
	return resp, nil
}

// Get the metadata of a directory. The response HTTP headers contain the
// metadata. There is no response body.
//
// This method is useful to check if a directory exists and the caller has
// access to it.
//
// If you wish to ensure the directory exists, you can instead use `PUT`, which
// will create the directory if it does not exist, and is idempotent (it will
// succeed if the directory already exists).
func (c *internalClient) GetDirectoryMetadata(ctx context.Context, req *GetDirectoryMetadataRequest, opts ...call.Option) (*GetDirectoryMetadataResponse, error) {

	headers := http.Header{}
	if c.userAgent != "" {
		headers.Set("User-Agent", c.userAgent)
	}
	headers.Set("Content-Type", "application/json")

	baseURL, err := url.Parse(c.host)
	if err != nil {
		return nil, err
	}
	pb := pathBuilder{}
	pb.literal("/api/2.0/fs/directories")
	pb.multiSegments(*req.DirectoryPath)
	baseURL.Path, baseURL.RawPath = pb.build()
	queryParams := url.Values{}
	baseURL.RawQuery = queryParams.Encode()
	urlStr := baseURL.String()

	var resp *GetDirectoryMetadataResponse

	call := func(ctx context.Context) error {
		httpReq, err := newHTTPRequest(ctx, httpRequestOptions{
			Method:      "HEAD",
			URL:         urlStr,
			Credentials: c.credentials,
			Headers:     headers,
		})
		if err != nil {
			return err
		}

		respBody, _, err := executeHTTPCall(httpCallOptions{
			req:    httpReq,
			client: c.httpClient,
			logger: c.logger,
		})
		if err != nil {
			return err
		}
		var wireResp getDirectoryMetadataResponseWire
		if err := unmarshalResponse(respBody, &wireResp); err != nil {
			return err
		}
		resp = getDirectoryMetadataResponseFromWire(&wireResp)
		return nil
	}

	if err := executeCall(ctx, call, opts); err != nil {
		return nil, err
	}
	return resp, nil
}

// Get the metadata of a file. The response HTTP headers contain the metadata.
// There is no response body.
func (c *internalClient) GetFileMetadata(ctx context.Context, req *GetFileMetadataRequest, opts ...call.Option) (*GetFileMetadataResponse, error) {

	headers := http.Header{}
	if c.userAgent != "" {
		headers.Set("User-Agent", c.userAgent)
	}
	headers.Set("Content-Type", "application/json")
	if req.Range != nil {
		headers.Set("Range", fmt.Sprintf("%v", *req.Range))
	}
	if req.IfUnmodifiedSince != nil {
		headers.Set("If-Unmodified-Since", fmt.Sprintf("%v", *req.IfUnmodifiedSince))
	}

	baseURL, err := url.Parse(c.host)
	if err != nil {
		return nil, err
	}
	pb := pathBuilder{}
	pb.literal("/api/2.0/fs/files")
	pb.multiSegments(*req.FilePath)
	baseURL.Path, baseURL.RawPath = pb.build()
	queryParams := url.Values{}
	baseURL.RawQuery = queryParams.Encode()
	urlStr := baseURL.String()

	var resp *GetFileMetadataResponse

	call := func(ctx context.Context) error {
		httpReq, err := newHTTPRequest(ctx, httpRequestOptions{
			Method:      "HEAD",
			URL:         urlStr,
			Credentials: c.credentials,
			Headers:     headers,
		})
		if err != nil {
			return err
		}

		respBody, respHeader, err := executeHTTPCall(httpCallOptions{
			req:    httpReq,
			client: c.httpClient,
			logger: c.logger,
		})
		if err != nil {
			return err
		}
		_ = respBody
		resp = &GetFileMetadataResponse{}
		if v := respHeader.Get("content-length"); v != "" {
			n, err := strconv.ParseInt(v, 10, 64)
			if err != nil {
				return err
			}
			resp.ContentLength = &n
		}
		if v := respHeader.Get("content-type"); v != "" {
			h := v
			resp.ContentType = &h
		}
		if v := respHeader.Get("last-modified"); v != "" {
			h := v
			resp.LastModified = &h
		}
		return nil
	}

	if err := executeCall(ctx, call, opts); err != nil {
		return nil, err
	}
	return resp, nil
}

// Returns the contents of a directory. If there is no directory at the
// specified path, the API returns an HTTP 404 error.
func (c *internalClient) ListDirectoryContents(ctx context.Context, req *ListDirectoryContentsRequest, opts ...call.Option) (*ListDirectoryResponse, error) {

	headers := http.Header{}
	if c.userAgent != "" {
		headers.Set("User-Agent", c.userAgent)
	}
	headers.Set("Content-Type", "application/json")

	baseURL, err := url.Parse(c.host)
	if err != nil {
		return nil, err
	}
	pb := pathBuilder{}
	pb.literal("/api/2.0/fs/directories")
	pb.multiSegments(*req.DirectoryPath)
	baseURL.Path, baseURL.RawPath = pb.build()
	queryParams := url.Values{}
	if err := addQueryValue(queryParams, "page_size", req.PageSize); err != nil {
		return nil, err
	}
	if err := addQueryValue(queryParams, "page_token", req.PageToken); err != nil {
		return nil, err
	}
	baseURL.RawQuery = queryParams.Encode()
	urlStr := baseURL.String()

	var resp *ListDirectoryResponse

	call := func(ctx context.Context) error {
		httpReq, err := newHTTPRequest(ctx, httpRequestOptions{
			Method:      "GET",
			URL:         urlStr,
			Credentials: c.credentials,
			Headers:     headers,
		})
		if err != nil {
			return err
		}

		respBody, _, err := executeHTTPCall(httpCallOptions{
			req:    httpReq,
			client: c.httpClient,
			logger: c.logger,
		})
		if err != nil {
			return err
		}
		var wireResp listDirectoryResponseWire
		if err := unmarshalResponse(respBody, &wireResp); err != nil {
			return err
		}
		resp = listDirectoryResponseFromWire(&wireResp)
		return nil
	}

	if err := executeCall(ctx, call, opts); err != nil {
		return nil, err
	}
	return resp, nil
}

// ListDirectoryContentsIter returns an iterator that iterates
// over the results of ListDirectoryContents.
//
// For example:
//
//	for item, err := range c.ListDirectoryContentsIter(ctx, &ListDirectoryContentsRequest{}) {
//	  if err != nil {
//	    return err
//	  }
//	  fmt.Println(item)
//	}
//
// Options opts are passed to each ListDirectoryContents call
// made by the iterator under the hood.
//
// Callers who need custom pagination logic should use
// ListDirectoryContents directly.
func (c *internalClient) ListDirectoryContentsIter(ctx context.Context, req *ListDirectoryContentsRequest, opts ...call.Option) iter.Seq2[*DirectoryEntry, error] {
	return func(yield func(*DirectoryEntry, error) bool) {
		// Deep copy the request via JSON round-trip to avoid modifying the original.
		reqBody, err := json.Marshal(req)
		if err != nil {
			yield(nil, err)
			return
		}
		pageReq := ListDirectoryContentsRequest{}
		if err := json.Unmarshal(reqBody, &pageReq); err != nil {
			yield(nil, err)
			return
		}
		for {
			resp, err := c.ListDirectoryContents(ctx, &pageReq, opts...)
			if err != nil {
				yield(nil, err)
				return
			}
			for i := range resp.Contents {
				if !yield(&resp.Contents[i], nil) {
					return
				}
			}
			if resp.NextPageToken == nil || *resp.NextPageToken == "" {
				return
			}
			pageReq.PageToken = resp.NextPageToken
		}
	}
}

// Uploads a file of up to 5 GiB. The file contents should be sent as the
// request body as raw bytes (an octet stream); do not encode or otherwise
// modify the bytes before sending. The contents of the resulting file will be
// exactly the bytes sent in the request body. If the request is successful,
// there is no response body.
func (c *internalClient) UploadFile(ctx context.Context, req *UploadFileRequest, opts ...call.Option) (*UploadFileResponse, error) {

	headers := http.Header{}
	if c.userAgent != "" {
		headers.Set("User-Agent", c.userAgent)
	}
	headers.Set("Content-Type", "application/octet-stream")

	baseURL, err := url.Parse(c.host)
	if err != nil {
		return nil, err
	}
	pb := pathBuilder{}
	pb.literal("/api/2.0/fs/files")
	pb.multiSegments(*req.FilePath)
	baseURL.Path, baseURL.RawPath = pb.build()
	queryParams := url.Values{}
	if err := addQueryValue(queryParams, "overwrite", req.Overwrite); err != nil {
		return nil, err
	}
	baseURL.RawQuery = queryParams.Encode()
	urlStr := baseURL.String()

	var resp *UploadFileResponse

	// A streaming request body is consumed on the first attempt and cannot be
	// replayed, so retries default to disabled to avoid resending a partial
	// body. Prepended (not appended) so a caller who explicitly passes a
	// retry option still overrides this default. Set before the call closure
	// below shadows the call package identifier.
	opts = append([]call.Option{call.WithDisableRetry()}, opts...)

	call := func(ctx context.Context) error {
		var reqBody io.Reader
		if req.Contents != nil {
			reqBody = req.Contents
		}
		httpReq, err := newHTTPRequest(ctx, httpRequestOptions{
			Method:      "PUT",
			URL:         urlStr,
			Credentials: c.credentials,
			Headers:     headers,
			Body:        reqBody,
		})
		if err != nil {
			return err
		}

		respBody, _, err := executeHTTPCall(httpCallOptions{
			req:    httpReq,
			client: c.httpClient,
			logger: c.logger,
		})
		if err != nil {
			return err
		}
		var wireResp uploadFileResponseWire
		if err := unmarshalResponse(respBody, &wireResp); err != nil {
			return err
		}
		resp = uploadFileResponseFromWire(&wireResp)
		return nil
	}

	if err := executeCall(ctx, call, opts); err != nil {
		return nil, err
	}
	return resp, nil
}
