Cloud = false # tests don't interact with APIs

# genie_spaces are only supported in the current version of the wheel
EnvMatrix.PYDAB_VERSION = ["current"]

# genie_spaces are only supported on the direct deployment engine
EnvMatrix.DATABRICKS_BUNDLE_ENGINE = ["direct"]
