#!/bin/bash

touch dummy.whl
$CLI bundle deploy
pipeline_id="$(read_id.py my_pipeline)"


title "Modify pipeline cluster num_workers from 2 to 5"
edit_resource.py pipelines $pipeline_id <<EOF
r["clusters"][0]["num_workers"] = 5
EOF

title "Detect and save changes"
$CLI bundle config-remote-sync --save

title "Updated configuration"
echo
cat databricks.yml
