// Auto-generated by AppKit - DO NOT EDIT
// Generated at: 2025-12-01T13:45:01.278Z

import "@databricks/app-kit-ui/react";

declare module "@databricks/app-kit-ui/react" {
  interface PluginRegistry {

  }

}
