#!/bin/bash

envsubst < databricks.yml.tmpl > databricks.yml

cleanup() {
  trace $CLI bundle destroy --auto-approve
}
trap cleanup EXIT

touch dummy.whl
$CLI bundle deploy
job_id="$(read_id.py my_job)"

title "Case 1: Added locally, updated remotely with different value"
echo
old=$(cat <<'EOF'
          email_notifications:
            on_success:
              - success@example.com
EOF
)
new=$(cat <<'EOF'
          email_notifications:
            on_success:
              - success@example.com
            on_failure:
              - config-failure@example.com
EOF
)
update_file.py databricks.yml "$old" "$new"
read -r -d '' case1 <<'EOF' || true
r["email_notifications"]["on_failure"] = ["remote-failure@example.com"]
EOF

title "Case 2: Added locally, removed remotely"
echo
old=$(cat <<'EOF'
          max_concurrent_runs: 1
EOF
)
new=$(cat <<'EOF'
          max_concurrent_runs: 1
          timeout_seconds: 3600
EOF
)
update_file.py databricks.yml "$old" "$new"
read -r -d '' case2 <<'EOF' || true
r.pop("timeout_seconds", None)
EOF

title "Case 3: Removed locally, removed remotely"
echo
old=$(cat <<'EOF'
          tags:
            env: dev
            version: v1
            team: data-team
EOF
)
new=$(cat <<'EOF'
          tags:
            env: dev
            team: data-team
EOF
)
update_file.py databricks.yml "$old" "$new"
read -r -d '' case3 <<'EOF' || true
r["tags"].pop("version", None)
EOF

title "Case 4: Updated locally, updated remotely with different value"
echo
update_file.py databricks.yml 'max_concurrent_runs: 1' 'max_concurrent_runs: 3'
read -r -d '' case4 <<'EOF' || true
r["max_concurrent_runs"] = 5
EOF

title "Case 5: Updated locally, removed remotely"
echo
update_file.py databricks.yml 'env: dev' 'env: config-production'
read -r -d '' case5 <<'EOF' || true
r["tags"].pop("env", None)
EOF

title "Case 6: Added locally and remotely with same value (no drift expected)"
echo
old=$(cat <<'EOF'
        my_job:
          email_notifications:
EOF
)
new=$(cat <<'EOF'
        my_job:
          description: A test job
          email_notifications:
EOF
)
update_file.py databricks.yml "$old" "$new"
read -r -d '' case6 <<'EOF' || true
r["description"] = "A test job"
EOF

title "Edit job remotely"
echo
edit_resource.py jobs $job_id <<EOF
$case1

$case2

$case3

$case4

$case5

$case6
EOF

title "Detect and save changes"
echo
cp databricks.yml databricks.yml.backup
$CLI bundle config-remote-sync --save

title "Configuration changes"
echo
trace diff.py databricks.yml.backup databricks.yml
rm databricks.yml.backup
