# Code generated by pydabs-codegen. DO NOT EDIT.

from dataclasses import dataclass
from typing import TYPE_CHECKING, TypedDict

from databricks.bundles.core._transform import _transform
from databricks.bundles.core._transform_to_json import _transform_to_json_value
from databricks.bundles.core._variable import VariableOrOptional
from databricks.bundles.model_provider_services._models.model_provider_service_config_entra_service_principal import (
    ModelProviderServiceConfigEntraServicePrincipal,
    ModelProviderServiceConfigEntraServicePrincipalParam,
)
from databricks.bundles.model_provider_services._models.model_provider_service_config_provider_secret import (
    ModelProviderServiceConfigProviderSecret,
    ModelProviderServiceConfigProviderSecretParam,
)
from databricks.bundles.model_provider_services._models.model_provider_service_config_service_credential import (
    ModelProviderServiceConfigServiceCredential,
    ModelProviderServiceConfigServiceCredentialParam,
)

if TYPE_CHECKING:
    from typing_extensions import Self


@dataclass(kw_only=True)
class ModelProviderServiceConfigAzureOpenAiProviderDirectConfig:
    """
    Direct form of Azure OpenAI provider config. Exactly one of three
    mutually-exclusive auth modes must be supplied on Create:
    - API key: set `api_key`, leave `entra_service_principal` and
    `service_credential` unset.
    - Entra ID (service principal): set `entra_service_principal`, leave
    `api_key` and `service_credential` unset.
    - Unity Catalog service credential: set `service_credential.name` to the
    resource name `credentials/{name}`, leave `api_key` and
    `entra_service_principal` unset. The credential value lives in Unity
    Catalog and is referenced by name, not held on this message. Only
    supported on Azure-hosted workspaces.
    Setting more than one mode is rejected.
    """

    api_key: VariableOrOptional[ModelProviderServiceConfigProviderSecret] = None
    """
    Azure OpenAI API key. Supply the value in `api_key.plaintext`. Mutually
    exclusive with Entra ID and Unity Catalog service credential
    authentication.
    """

    base_url: VariableOrOptional[str] = None
    """
    Full Azure OpenAI endpoint base URL, e.g.
    `https://myresource.openai.azure.com`. Required on Create.
    """

    entra_service_principal: VariableOrOptional[
        ModelProviderServiceConfigEntraServicePrincipal
    ] = None
    """
    Entra ID service-principal authentication. Set `tenant_id`, `client_id`,
    and `client_secret.plaintext`. Mutually exclusive with `api_key` and
    `service_credential`.
    """

    service_credential: VariableOrOptional[
        ModelProviderServiceConfigServiceCredential
    ] = None
    """
    Reference to a Unity Catalog service credential authorizing Azure OpenAI
    requests. On Create, supply `service_credential.name` in the form
    `credentials/{name}`. Required on Create when using service-credential
    authentication; mutually exclusive with `api_key` and
    `entra_service_principal`. The credential is referenced by name; its value
    is not carried here. Only supported on Azure-hosted workspaces.
    """

    @classmethod
    def from_dict(
        cls, value: "ModelProviderServiceConfigAzureOpenAiProviderDirectConfigDict"
    ) -> "Self":
        return _transform(cls, value)

    def as_dict(
        self,
    ) -> "ModelProviderServiceConfigAzureOpenAiProviderDirectConfigDict":
        return _transform_to_json_value(self)  # type:ignore


class ModelProviderServiceConfigAzureOpenAiProviderDirectConfigDict(
    TypedDict, total=False
):
    """"""

    api_key: VariableOrOptional[ModelProviderServiceConfigProviderSecretParam]
    """
    Azure OpenAI API key. Supply the value in `api_key.plaintext`. Mutually
    exclusive with Entra ID and Unity Catalog service credential
    authentication.
    """

    base_url: VariableOrOptional[str]
    """
    Full Azure OpenAI endpoint base URL, e.g.
    `https://myresource.openai.azure.com`. Required on Create.
    """

    entra_service_principal: VariableOrOptional[
        ModelProviderServiceConfigEntraServicePrincipalParam
    ]
    """
    Entra ID service-principal authentication. Set `tenant_id`, `client_id`,
    and `client_secret.plaintext`. Mutually exclusive with `api_key` and
    `service_credential`.
    """

    service_credential: VariableOrOptional[
        ModelProviderServiceConfigServiceCredentialParam
    ]
    """
    Reference to a Unity Catalog service credential authorizing Azure OpenAI
    requests. On Create, supply `service_credential.name` in the form
    `credentials/{name}`. Required on Create when using service-credential
    authentication; mutually exclusive with `api_key` and
    `entra_service_principal`. The credential is referenced by name; its value
    is not carried here. Only supported on Azure-hosted workspaces.
    """


ModelProviderServiceConfigAzureOpenAiProviderDirectConfigParam = (
    ModelProviderServiceConfigAzureOpenAiProviderDirectConfigDict
    | ModelProviderServiceConfigAzureOpenAiProviderDirectConfig
)
