# Code generated by pydabs-codegen. DO NOT EDIT.

from dataclasses import dataclass, field
from typing import TYPE_CHECKING, TypedDict

from databricks.bundles.core._transform import _transform
from databricks.bundles.core._transform_to_json import _transform_to_json_value
from databricks.bundles.core._variable import VariableOr, VariableOrList

if TYPE_CHECKING:
    from typing_extensions import Self


@dataclass(kw_only=True)
class ModelProviderServiceConfigModelTargetConfig:
    """
    Model target configuration for an external model destination.
    """

    model: VariableOr[str]
    """
    Provider-side model identifier, such as `gpt-5` or `claude-opus-4-7`.
    This identifies a model at the upstream provider; it is not a Unity
    Catalog model resource.
    """

    native_api_types: VariableOrList[str] = field(default_factory=list)
    """
    Provider-native API types supported by this model, such as
    `openai/v1/chat/completions`. At least one value is required. AI Gateway
    uses these values to translate requests and responses. At most 64 entries
    of 256 characters each are allowed.
    """

    @classmethod
    def from_dict(
        cls, value: "ModelProviderServiceConfigModelTargetConfigDict"
    ) -> "Self":
        return _transform(cls, value)

    def as_dict(self) -> "ModelProviderServiceConfigModelTargetConfigDict":
        return _transform_to_json_value(self)  # type:ignore


class ModelProviderServiceConfigModelTargetConfigDict(TypedDict, total=False):
    """"""

    model: VariableOr[str]
    """
    Provider-side model identifier, such as `gpt-5` or `claude-opus-4-7`.
    This identifies a model at the upstream provider; it is not a Unity
    Catalog model resource.
    """

    native_api_types: VariableOrList[str]
    """
    Provider-native API types supported by this model, such as
    `openai/v1/chat/completions`. At least one value is required. AI Gateway
    uses these values to translate requests and responses. At most 64 entries
    of 256 characters each are allowed.
    """


ModelProviderServiceConfigModelTargetConfigParam = (
    ModelProviderServiceConfigModelTargetConfigDict
    | ModelProviderServiceConfigModelTargetConfig
)
