# Code generated by pydabs-codegen. DO NOT EDIT.

from dataclasses import dataclass
from typing import TYPE_CHECKING, TypedDict

from databricks.bundles.core._transform import _transform
from databricks.bundles.core._transform_to_json import _transform_to_json_value
from databricks.bundles.core._variable import VariableOrOptional
from databricks.bundles.model_provider_services._models.model_provider_service_config_provider_secret import (
    ModelProviderServiceConfigProviderSecret,
    ModelProviderServiceConfigProviderSecretParam,
)

if TYPE_CHECKING:
    from typing_extensions import Self


@dataclass(kw_only=True)
class ModelProviderServiceConfigAwsAccessKey:
    """
    AWS access-key-pair auth for Amazon Bedrock: a SigV4-signing key pair.
    """

    access_key_id: VariableOrOptional[str] = None
    """
    :meta private: [EXPERIMENTAL]
    
    [Beta] AWS access key ID. Required on Create when using access-key auth. Treated as
    username-equivalent (not a secret value): round-trips on reads and is
    scrubbed from audit logs.
    """

    secret_access_key: VariableOrOptional[ModelProviderServiceConfigProviderSecret] = (
        None
    )
    """
    :meta private: [EXPERIMENTAL]
    
    [Beta] AWS secret access key paired with `access_key_id`. Required on Create when
    using access-key auth. Supplied as inline plaintext via
    `ProviderSecret.plaintext`.
    """

    @classmethod
    def from_dict(cls, value: "ModelProviderServiceConfigAwsAccessKeyDict") -> "Self":
        return _transform(cls, value)

    def as_dict(self) -> "ModelProviderServiceConfigAwsAccessKeyDict":
        return _transform_to_json_value(self)  # type:ignore


class ModelProviderServiceConfigAwsAccessKeyDict(TypedDict, total=False):
    """"""

    access_key_id: VariableOrOptional[str]
    """
    :meta private: [EXPERIMENTAL]
    
    [Beta] AWS access key ID. Required on Create when using access-key auth. Treated as
    username-equivalent (not a secret value): round-trips on reads and is
    scrubbed from audit logs.
    """

    secret_access_key: VariableOrOptional[ModelProviderServiceConfigProviderSecretParam]
    """
    :meta private: [EXPERIMENTAL]
    
    [Beta] AWS secret access key paired with `access_key_id`. Required on Create when
    using access-key auth. Supplied as inline plaintext via
    `ProviderSecret.plaintext`.
    """


ModelProviderServiceConfigAwsAccessKeyParam = (
    ModelProviderServiceConfigAwsAccessKeyDict | ModelProviderServiceConfigAwsAccessKey
)
