# Code generated by pydabs-codegen. DO NOT EDIT.

from dataclasses import dataclass
from typing import TYPE_CHECKING, TypedDict

from databricks.bundles.core._transform import _transform
from databricks.bundles.core._transform_to_json import _transform_to_json_value
from databricks.bundles.core._variable import VariableOrOptional
from databricks.bundles.model_provider_services._models.model_provider_service_config_provider_secret import (
    ModelProviderServiceConfigProviderSecret,
    ModelProviderServiceConfigProviderSecretParam,
)

if TYPE_CHECKING:
    from typing_extensions import Self


@dataclass(kw_only=True)
class ModelProviderServiceConfigCustomProviderApiKeyHeaderAuth:
    """
    :meta private: [EXPERIMENTAL]

    Header-based API-key authentication for a custom provider: the secret is
    forwarded on outbound requests under a caller-chosen HTTP header, as
    `<api_key_name>: <api_key_value>`.
    """

    api_key_name: VariableOrOptional[str] = None
    """
    :meta private: [EXPERIMENTAL]
    
    [Private Preview] HTTP header name that carries the API key on outbound requests (e.g.,
    `Ocp-Apim-Subscription-Key`). The value forwarded under this header is
    supplied via `api_key_value`.
    """

    api_key_value: VariableOrOptional[ModelProviderServiceConfigProviderSecret] = None
    """
    :meta private: [EXPERIMENTAL]
    
    [Private Preview] Secret value forwarded under the `api_key_name` header on outbound
    requests. Supplied as inline plaintext via `ProviderSecret.plaintext`.
    """

    @classmethod
    def from_dict(
        cls, value: "ModelProviderServiceConfigCustomProviderApiKeyHeaderAuthDict"
    ) -> "Self":
        return _transform(cls, value)

    def as_dict(self) -> "ModelProviderServiceConfigCustomProviderApiKeyHeaderAuthDict":
        return _transform_to_json_value(self)  # type:ignore


class ModelProviderServiceConfigCustomProviderApiKeyHeaderAuthDict(
    TypedDict, total=False
):
    """"""

    api_key_name: VariableOrOptional[str]
    """
    :meta private: [EXPERIMENTAL]
    
    [Private Preview] HTTP header name that carries the API key on outbound requests (e.g.,
    `Ocp-Apim-Subscription-Key`). The value forwarded under this header is
    supplied via `api_key_value`.
    """

    api_key_value: VariableOrOptional[ModelProviderServiceConfigProviderSecretParam]
    """
    :meta private: [EXPERIMENTAL]
    
    [Private Preview] Secret value forwarded under the `api_key_name` header on outbound
    requests. Supplied as inline plaintext via `ProviderSecret.plaintext`.
    """


ModelProviderServiceConfigCustomProviderApiKeyHeaderAuthParam = (
    ModelProviderServiceConfigCustomProviderApiKeyHeaderAuthDict
    | ModelProviderServiceConfigCustomProviderApiKeyHeaderAuth
)
