# Code generated by pydabs-codegen. DO NOT EDIT.

from dataclasses import dataclass
from typing import TYPE_CHECKING, TypedDict

from databricks.bundles.core._transform import _transform
from databricks.bundles.core._transform_to_json import _transform_to_json_value
from databricks.bundles.core._variable import VariableOrOptional
from databricks.bundles.model_provider_services._models.model_provider_service_config_gemini_enterprise_provider_direct_config import (
    ModelProviderServiceConfigGeminiEnterpriseProviderDirectConfig,
    ModelProviderServiceConfigGeminiEnterpriseProviderDirectConfigParam,
)

if TYPE_CHECKING:
    from typing_extensions import Self


@dataclass(kw_only=True)
class ModelProviderServiceConfigGeminiEnterpriseProviderConfig:
    """
    Gemini Enterprise provider configuration.
    """

    direct: VariableOrOptional[
        ModelProviderServiceConfigGeminiEnterpriseProviderDirectConfig
    ] = None
    """
    Gemini Enterprise project, region, and authentication configuration.
    """

    @classmethod
    def from_dict(
        cls, value: "ModelProviderServiceConfigGeminiEnterpriseProviderConfigDict"
    ) -> "Self":
        return _transform(cls, value)

    def as_dict(self) -> "ModelProviderServiceConfigGeminiEnterpriseProviderConfigDict":
        return _transform_to_json_value(self)  # type:ignore


class ModelProviderServiceConfigGeminiEnterpriseProviderConfigDict(
    TypedDict, total=False
):
    """"""

    direct: VariableOrOptional[
        ModelProviderServiceConfigGeminiEnterpriseProviderDirectConfigParam
    ]
    """
    Gemini Enterprise project, region, and authentication configuration.
    """


ModelProviderServiceConfigGeminiEnterpriseProviderConfigParam = (
    ModelProviderServiceConfigGeminiEnterpriseProviderConfigDict
    | ModelProviderServiceConfigGeminiEnterpriseProviderConfig
)
