# Code generated by pydabs-codegen. DO NOT EDIT.

from dataclasses import dataclass
from typing import TYPE_CHECKING, TypedDict

from databricks.bundles.core._transform import _transform
from databricks.bundles.core._transform_to_json import _transform_to_json_value
from databricks.bundles.core._variable import VariableOrOptional
from databricks.bundles.model_provider_services._models.model_provider_service_config_azure_open_ai_provider_direct_config import (
    ModelProviderServiceConfigAzureOpenAiProviderDirectConfig,
    ModelProviderServiceConfigAzureOpenAiProviderDirectConfigParam,
)

if TYPE_CHECKING:
    from typing_extensions import Self


@dataclass(kw_only=True)
class ModelProviderServiceConfigAzureOpenAiProviderConfig:
    """
    Azure OpenAI provider configuration.
    """

    direct: VariableOrOptional[
        ModelProviderServiceConfigAzureOpenAiProviderDirectConfig
    ] = None
    """
    :meta private: [EXPERIMENTAL]
    
    [Beta] Direct form of Azure OpenAI provider config. Exactly one of three
    mutually-exclusive auth modes must be supplied on Create:
    - API key: set `api_key`, leave `entra_service_principal` and
    `service_credential` unset.
    - Entra ID (service principal): set `entra_service_principal`, leave
    `api_key` and `service_credential` unset.
    - UC service credential: set `service_credential.name` to the AIP-122
    resource-name form `credentials/{name}`, leave `api_key` and
    `entra_service_principal` unset. The credential value lives in UC and is
    referenced by name, not held on this message. Only supported on
    Azure-hosted workspaces.
    Setting more than one mode is rejected.
    """

    @classmethod
    def from_dict(
        cls, value: "ModelProviderServiceConfigAzureOpenAiProviderConfigDict"
    ) -> "Self":
        return _transform(cls, value)

    def as_dict(self) -> "ModelProviderServiceConfigAzureOpenAiProviderConfigDict":
        return _transform_to_json_value(self)  # type:ignore


class ModelProviderServiceConfigAzureOpenAiProviderConfigDict(TypedDict, total=False):
    """"""

    direct: VariableOrOptional[
        ModelProviderServiceConfigAzureOpenAiProviderDirectConfigParam
    ]
    """
    :meta private: [EXPERIMENTAL]
    
    [Beta] Direct form of Azure OpenAI provider config. Exactly one of three
    mutually-exclusive auth modes must be supplied on Create:
    - API key: set `api_key`, leave `entra_service_principal` and
    `service_credential` unset.
    - Entra ID (service principal): set `entra_service_principal`, leave
    `api_key` and `service_credential` unset.
    - UC service credential: set `service_credential.name` to the AIP-122
    resource-name form `credentials/{name}`, leave `api_key` and
    `entra_service_principal` unset. The credential value lives in UC and is
    referenced by name, not held on this message. Only supported on
    Azure-hosted workspaces.
    Setting more than one mode is rejected.
    """


ModelProviderServiceConfigAzureOpenAiProviderConfigParam = (
    ModelProviderServiceConfigAzureOpenAiProviderConfigDict
    | ModelProviderServiceConfigAzureOpenAiProviderConfig
)
