# Code generated by pydabs-codegen. DO NOT EDIT.

from dataclasses import dataclass, field
from typing import TYPE_CHECKING, TypedDict

from databricks.bundles.core._transform import _transform
from databricks.bundles.core._transform_to_json import _transform_to_json_value
from databricks.bundles.core._variable import VariableOr, VariableOrList

if TYPE_CHECKING:
    from typing_extensions import Self


@dataclass(kw_only=True)
class ModelProviderServiceConfigModelTargetConfig:
    """
    Model target configuration for an external model destination.
    """

    model: VariableOr[str]
    """
    :meta private: [EXPERIMENTAL]
    
    [Beta] Provider-side model identifier (e.g. "gpt-5", "claude-opus-4-7"). This is
    a string on the LLM provider's side, not a UC entity. The UC governance
    hook for external destinations is the ModelProviderService referenced by
    `ExternalModelConfig.model_provider_service`, not the model itself.
    """

    native_api_types: VariableOrList[str] = field(default_factory=list)
    """
    :meta private: [EXPERIMENTAL]
    
    [Beta] Provider-native API types the model supports (e.g.
    "openai/v1/chat/completions"). Used by the platform for request/response
    translation from the unified API type. At most 64 entries of at most 256
    characters each; the list is persisted into the destination binding's
    bounded storage envelope.
    """

    @classmethod
    def from_dict(
        cls, value: "ModelProviderServiceConfigModelTargetConfigDict"
    ) -> "Self":
        return _transform(cls, value)

    def as_dict(self) -> "ModelProviderServiceConfigModelTargetConfigDict":
        return _transform_to_json_value(self)  # type:ignore


class ModelProviderServiceConfigModelTargetConfigDict(TypedDict, total=False):
    """"""

    model: VariableOr[str]
    """
    :meta private: [EXPERIMENTAL]
    
    [Beta] Provider-side model identifier (e.g. "gpt-5", "claude-opus-4-7"). This is
    a string on the LLM provider's side, not a UC entity. The UC governance
    hook for external destinations is the ModelProviderService referenced by
    `ExternalModelConfig.model_provider_service`, not the model itself.
    """

    native_api_types: VariableOrList[str]
    """
    :meta private: [EXPERIMENTAL]
    
    [Beta] Provider-native API types the model supports (e.g.
    "openai/v1/chat/completions"). Used by the platform for request/response
    translation from the unified API type. At most 64 entries of at most 256
    characters each; the list is persisted into the destination binding's
    bounded storage envelope.
    """


ModelProviderServiceConfigModelTargetConfigParam = (
    ModelProviderServiceConfigModelTargetConfigDict
    | ModelProviderServiceConfigModelTargetConfig
)
