# Code generated by pydabs-codegen. DO NOT EDIT.

from dataclasses import dataclass
from typing import TYPE_CHECKING, TypedDict

from databricks.bundles.core._transform import _transform
from databricks.bundles.core._transform_to_json import _transform_to_json_value
from databricks.bundles.core._variable import VariableOrOptional
from databricks.bundles.model_provider_services._models.model_provider_service_config_secret_reference import (
    ModelProviderServiceConfigSecretReference,
    ModelProviderServiceConfigSecretReferenceParam,
)

if TYPE_CHECKING:
    from typing_extensions import Self


@dataclass(kw_only=True)
class ModelProviderServiceConfigProviderSecret:
    """
    A secret value supplied as part of an inline provider config. The caller
    supplies the value as inline `plaintext` on writes; the platform stores it
    encrypted. The `plaintext` field is `INPUT_ONLY` and never round-trips on
    reads.
    """

    plaintext: VariableOrOptional[str] = None
    """
    Inline plaintext credential. INPUT_ONLY: the value never round-trips on
    reads. Get and List responses omit `plaintext`; the enclosing secret
    object remains present to indicate that a secret is configured.
    """

    secret_reference: VariableOrOptional[ModelProviderServiceConfigSecretReference] = (
        None
    )
    """
    Reference to a customer-owned UC Secret that carries this secret value.
    The value is read at invoke time under the model provider service
    owner's access and is never copied onto the model provider service, so
    rotating the UC Secret takes effect with no change to the model provider
    service. On Create, supply `secret_reference.name` as
    `secrets/{catalog}.{schema}.{secret}`.
    """

    @classmethod
    def from_dict(cls, value: "ModelProviderServiceConfigProviderSecretDict") -> "Self":
        return _transform(cls, value)

    def as_dict(self) -> "ModelProviderServiceConfigProviderSecretDict":
        return _transform_to_json_value(self)  # type:ignore


class ModelProviderServiceConfigProviderSecretDict(TypedDict, total=False):
    """"""

    plaintext: VariableOrOptional[str]
    """
    Inline plaintext credential. INPUT_ONLY: the value never round-trips on
    reads. Get and List responses omit `plaintext`; the enclosing secret
    object remains present to indicate that a secret is configured.
    """

    secret_reference: VariableOrOptional[ModelProviderServiceConfigSecretReferenceParam]
    """
    Reference to a customer-owned UC Secret that carries this secret value.
    The value is read at invoke time under the model provider service
    owner's access and is never copied onto the model provider service, so
    rotating the UC Secret takes effect with no change to the model provider
    service. On Create, supply `secret_reference.name` as
    `secrets/{catalog}.{schema}.{secret}`.
    """


ModelProviderServiceConfigProviderSecretParam = (
    ModelProviderServiceConfigProviderSecretDict
    | ModelProviderServiceConfigProviderSecret
)
