# Code generated by pydabs-codegen. DO NOT EDIT.

from dataclasses import dataclass
from typing import TYPE_CHECKING, TypedDict

from databricks.bundles.core._transform import _transform
from databricks.bundles.core._transform_to_json import _transform_to_json_value
from databricks.bundles.core._variable import VariableOrOptional
from databricks.bundles.model_provider_services._models.model_provider_service_config_aws_access_key import (
    ModelProviderServiceConfigAwsAccessKey,
    ModelProviderServiceConfigAwsAccessKeyParam,
)
from databricks.bundles.model_provider_services._models.model_provider_service_config_service_credential import (
    ModelProviderServiceConfigServiceCredential,
    ModelProviderServiceConfigServiceCredentialParam,
)

if TYPE_CHECKING:
    from typing_extensions import Self


@dataclass(kw_only=True)
class ModelProviderServiceConfigAmazonBedrockProviderDirectConfig:
    """
    Direct form of Amazon Bedrock provider config.

    Authentication is one of two mutually exclusive modes, exactly one of which
    must be supplied on Create:
    - Access keys: set `aws_access_key`, leave `service_credential` unset.
    - Unity Catalog service credential: set `service_credential.name` to the
    resource name `credentials/{name}`, leave `aws_access_key` unset. The
    credential value lives in Unity Catalog and is referenced by name, not
    held on this message.
    Setting more than one mode is rejected.
    """

    aws_access_key: VariableOrOptional[ModelProviderServiceConfigAwsAccessKey] = None
    """
    AWS access-key-pair authentication. Set `access_key_id` and
    `secret_access_key.plaintext`. Mutually exclusive with
    `service_credential`.
    """

    region: VariableOrOptional[str] = None
    """
    AWS region where the Bedrock endpoint is hosted (e.g., `us-east-1`).
    Required on Create.
    """

    service_credential: VariableOrOptional[
        ModelProviderServiceConfigServiceCredential
    ] = None
    """
    Reference to a Unity Catalog service credential authorizing Bedrock
    requests. On Create, supply `service_credential.name` in the form
    `credentials/{name}`. Required on Create when using service-credential
    authentication; mutually exclusive with `aws_access_key`. The credential
    is referenced by name; its value is not carried here. Only
    supported on AWS-hosted workspaces.
    """

    @classmethod
    def from_dict(
        cls, value: "ModelProviderServiceConfigAmazonBedrockProviderDirectConfigDict"
    ) -> "Self":
        return _transform(cls, value)

    def as_dict(
        self,
    ) -> "ModelProviderServiceConfigAmazonBedrockProviderDirectConfigDict":
        return _transform_to_json_value(self)  # type:ignore


class ModelProviderServiceConfigAmazonBedrockProviderDirectConfigDict(
    TypedDict, total=False
):
    """"""

    aws_access_key: VariableOrOptional[ModelProviderServiceConfigAwsAccessKeyParam]
    """
    AWS access-key-pair authentication. Set `access_key_id` and
    `secret_access_key.plaintext`. Mutually exclusive with
    `service_credential`.
    """

    region: VariableOrOptional[str]
    """
    AWS region where the Bedrock endpoint is hosted (e.g., `us-east-1`).
    Required on Create.
    """

    service_credential: VariableOrOptional[
        ModelProviderServiceConfigServiceCredentialParam
    ]
    """
    Reference to a Unity Catalog service credential authorizing Bedrock
    requests. On Create, supply `service_credential.name` in the form
    `credentials/{name}`. Required on Create when using service-credential
    authentication; mutually exclusive with `aws_access_key`. The credential
    is referenced by name; its value is not carried here. Only
    supported on AWS-hosted workspaces.
    """


ModelProviderServiceConfigAmazonBedrockProviderDirectConfigParam = (
    ModelProviderServiceConfigAmazonBedrockProviderDirectConfigDict
    | ModelProviderServiceConfigAmazonBedrockProviderDirectConfig
)
