# Code generated by pydabs-codegen. DO NOT EDIT.

from dataclasses import dataclass
from typing import TYPE_CHECKING, TypedDict

from databricks.bundles.core._transform import _transform
from databricks.bundles.core._transform_to_json import _transform_to_json_value
from databricks.bundles.core._variable import VariableOrOptional
from databricks.bundles.model_provider_services._models.model_provider_service_config_anthropic_provider_direct_config import (
    ModelProviderServiceConfigAnthropicProviderDirectConfig,
    ModelProviderServiceConfigAnthropicProviderDirectConfigParam,
)
from databricks.bundles.model_provider_services._models.model_provider_service_config_anthropic_provider_relayed_config import (
    ModelProviderServiceConfigAnthropicProviderRelayedConfig,
    ModelProviderServiceConfigAnthropicProviderRelayedConfigParam,
)

if TYPE_CHECKING:
    from typing_extensions import Self


@dataclass(kw_only=True)
class ModelProviderServiceConfigAnthropicProviderConfig:
    """
    Anthropic provider configuration. Exactly one of `direct` or `relayed` must
    be set on Create; the two are mutually exclusive.
    """

    direct: VariableOrOptional[
        ModelProviderServiceConfigAnthropicProviderDirectConfig
    ] = None
    """
    Direct authentication with an API key supplied in
    `direct.api_key.plaintext`. Required unless `relayed` is set.
    """

    relayed: VariableOrOptional[
        ModelProviderServiceConfigAnthropicProviderRelayedConfig
    ] = None
    """
    Relayed authentication. Each inference request supplies the caller's
    OAuth token, which is forwarded to Anthropic. No Anthropic credential is
    stored. Mutually exclusive with `direct`.
    """

    @classmethod
    def from_dict(
        cls, value: "ModelProviderServiceConfigAnthropicProviderConfigDict"
    ) -> "Self":
        return _transform(cls, value)

    def as_dict(self) -> "ModelProviderServiceConfigAnthropicProviderConfigDict":
        return _transform_to_json_value(self)  # type:ignore


class ModelProviderServiceConfigAnthropicProviderConfigDict(TypedDict, total=False):
    """"""

    direct: VariableOrOptional[
        ModelProviderServiceConfigAnthropicProviderDirectConfigParam
    ]
    """
    Direct authentication with an API key supplied in
    `direct.api_key.plaintext`. Required unless `relayed` is set.
    """

    relayed: VariableOrOptional[
        ModelProviderServiceConfigAnthropicProviderRelayedConfigParam
    ]
    """
    Relayed authentication. Each inference request supplies the caller's
    OAuth token, which is forwarded to Anthropic. No Anthropic credential is
    stored. Mutually exclusive with `direct`.
    """


ModelProviderServiceConfigAnthropicProviderConfigParam = (
    ModelProviderServiceConfigAnthropicProviderConfigDict
    | ModelProviderServiceConfigAnthropicProviderConfig
)
