# Code generated by pydabs-codegen. DO NOT EDIT.

from dataclasses import dataclass
from typing import TYPE_CHECKING, TypedDict

from databricks.bundles.core._transform import _transform
from databricks.bundles.core._transform_to_json import _transform_to_json_value
from databricks.bundles.core._variable import VariableOr

if TYPE_CHECKING:
    from typing_extensions import Self


@dataclass(kw_only=True)
class ModelProviderServiceConfigServiceCredential:
    """
    ---- Provider configuration (nested; see the `provider` oneof below) ----
    The customer-owned UC service credential a ModelProviderService uses to
    authenticate to its provider, referenced by name.
    """

    name: VariableOr[str]
    """
    :meta private: [EXPERIMENTAL]
    
    [Beta] Resource name of the bound UC service credential, in the AIP-122 form
    `credentials/{name}` (a metastore-level single-part credential name). On
    create the caller supplies the name here. On read it reflects the
    credential's current name at read time.
    """

    @classmethod
    def from_dict(
        cls, value: "ModelProviderServiceConfigServiceCredentialDict"
    ) -> "Self":
        return _transform(cls, value)

    def as_dict(self) -> "ModelProviderServiceConfigServiceCredentialDict":
        return _transform_to_json_value(self)  # type:ignore


class ModelProviderServiceConfigServiceCredentialDict(TypedDict, total=False):
    """"""

    name: VariableOr[str]
    """
    :meta private: [EXPERIMENTAL]
    
    [Beta] Resource name of the bound UC service credential, in the AIP-122 form
    `credentials/{name}` (a metastore-level single-part credential name). On
    create the caller supplies the name here. On read it reflects the
    credential's current name at read time.
    """


ModelProviderServiceConfigServiceCredentialParam = (
    ModelProviderServiceConfigServiceCredentialDict
    | ModelProviderServiceConfigServiceCredential
)
