# Code generated by pydabs-codegen. DO NOT EDIT.

from dataclasses import dataclass
from typing import TYPE_CHECKING, TypedDict

from databricks.bundles.core._transform import _transform
from databricks.bundles.core._transform_to_json import _transform_to_json_value
from databricks.bundles.core._variable import VariableOrOptional
from databricks.bundles.model_provider_services._models.model_provider_service_config_amazon_bedrock_provider_direct_config import (
    ModelProviderServiceConfigAmazonBedrockProviderDirectConfig,
    ModelProviderServiceConfigAmazonBedrockProviderDirectConfigParam,
)

if TYPE_CHECKING:
    from typing_extensions import Self


@dataclass(kw_only=True)
class ModelProviderServiceConfigAmazonBedrockProviderConfig:
    """
    Amazon Bedrock provider configuration.
    """

    direct: VariableOrOptional[
        ModelProviderServiceConfigAmazonBedrockProviderDirectConfig
    ] = None
    """
    Amazon Bedrock region and authentication configuration.
    """

    @classmethod
    def from_dict(
        cls, value: "ModelProviderServiceConfigAmazonBedrockProviderConfigDict"
    ) -> "Self":
        return _transform(cls, value)

    def as_dict(self) -> "ModelProviderServiceConfigAmazonBedrockProviderConfigDict":
        return _transform_to_json_value(self)  # type:ignore


class ModelProviderServiceConfigAmazonBedrockProviderConfigDict(TypedDict, total=False):
    """"""

    direct: VariableOrOptional[
        ModelProviderServiceConfigAmazonBedrockProviderDirectConfigParam
    ]
    """
    Amazon Bedrock region and authentication configuration.
    """


ModelProviderServiceConfigAmazonBedrockProviderConfigParam = (
    ModelProviderServiceConfigAmazonBedrockProviderConfigDict
    | ModelProviderServiceConfigAmazonBedrockProviderConfig
)
