# Code generated by pydabs-codegen. DO NOT EDIT.

from dataclasses import dataclass
from typing import TYPE_CHECKING, TypedDict

from databricks.bundles.core._transform import _transform
from databricks.bundles.core._transform_to_json import _transform_to_json_value
from databricks.bundles.core._variable import VariableOrOptional
from databricks.bundles.model_provider_services._models.model_provider_service_config_microsoft_foundry_provider_direct_config import (
    ModelProviderServiceConfigMicrosoftFoundryProviderDirectConfig,
    ModelProviderServiceConfigMicrosoftFoundryProviderDirectConfigParam,
)

if TYPE_CHECKING:
    from typing_extensions import Self


@dataclass(kw_only=True)
class ModelProviderServiceConfigMicrosoftFoundryProviderConfig:
    """
    Microsoft Foundry provider configuration.
    """

    direct: VariableOrOptional[
        ModelProviderServiceConfigMicrosoftFoundryProviderDirectConfig
    ] = None
    """
    :meta private: [EXPERIMENTAL]
    
    [Beta] Direct form of Microsoft Foundry provider config.
    
    Authentication is one of three mutually exclusive modes, exactly one of which
    must be supplied on Create:
    - API key: set `api_key`, leave `entra_service_principal` and
    `service_credential` unset.
    - Entra ID (service principal): set `entra_service_principal`, leave
    `api_key` and `service_credential` unset. AI Gateway exchanges these for
    an Entra bearer token on outbound requests via the OAuth2
    client-credentials grant.
    - UC service credential: set `service_credential.name` to the AIP-122
    resource-name form `credentials/{name}`, leave `api_key` and
    `entra_service_principal` unset. The credential value lives in UC and is
    referenced by name, not held on this message. Only supported on
    Azure-hosted workspaces.
    Setting more than one mode is rejected.
    """

    @classmethod
    def from_dict(
        cls, value: "ModelProviderServiceConfigMicrosoftFoundryProviderConfigDict"
    ) -> "Self":
        return _transform(cls, value)

    def as_dict(self) -> "ModelProviderServiceConfigMicrosoftFoundryProviderConfigDict":
        return _transform_to_json_value(self)  # type:ignore


class ModelProviderServiceConfigMicrosoftFoundryProviderConfigDict(
    TypedDict, total=False
):
    """"""

    direct: VariableOrOptional[
        ModelProviderServiceConfigMicrosoftFoundryProviderDirectConfigParam
    ]
    """
    :meta private: [EXPERIMENTAL]
    
    [Beta] Direct form of Microsoft Foundry provider config.
    
    Authentication is one of three mutually exclusive modes, exactly one of which
    must be supplied on Create:
    - API key: set `api_key`, leave `entra_service_principal` and
    `service_credential` unset.
    - Entra ID (service principal): set `entra_service_principal`, leave
    `api_key` and `service_credential` unset. AI Gateway exchanges these for
    an Entra bearer token on outbound requests via the OAuth2
    client-credentials grant.
    - UC service credential: set `service_credential.name` to the AIP-122
    resource-name form `credentials/{name}`, leave `api_key` and
    `entra_service_principal` unset. The credential value lives in UC and is
    referenced by name, not held on this message. Only supported on
    Azure-hosted workspaces.
    Setting more than one mode is rejected.
    """


ModelProviderServiceConfigMicrosoftFoundryProviderConfigParam = (
    ModelProviderServiceConfigMicrosoftFoundryProviderConfigDict
    | ModelProviderServiceConfigMicrosoftFoundryProviderConfig
)
