# Code generated by pydabs-codegen. DO NOT EDIT.

from dataclasses import dataclass
from typing import TYPE_CHECKING, TypedDict

from databricks.bundles.core._transform import _transform
from databricks.bundles.core._transform_to_json import _transform_to_json_value
from databricks.bundles.core._variable import VariableOrOptional
from databricks.bundles.model_provider_services._models.model_provider_service_config_azure_open_ai_provider_direct_config import (
    ModelProviderServiceConfigAzureOpenAiProviderDirectConfig,
    ModelProviderServiceConfigAzureOpenAiProviderDirectConfigParam,
)

if TYPE_CHECKING:
    from typing_extensions import Self


@dataclass(kw_only=True)
class ModelProviderServiceConfigAzureOpenAiProviderConfig:
    """
    Azure OpenAI provider configuration.
    """

    direct: VariableOrOptional[
        ModelProviderServiceConfigAzureOpenAiProviderDirectConfig
    ] = None
    """
    Azure OpenAI endpoint and authentication configuration.
    """

    @classmethod
    def from_dict(
        cls, value: "ModelProviderServiceConfigAzureOpenAiProviderConfigDict"
    ) -> "Self":
        return _transform(cls, value)

    def as_dict(self) -> "ModelProviderServiceConfigAzureOpenAiProviderConfigDict":
        return _transform_to_json_value(self)  # type:ignore


class ModelProviderServiceConfigAzureOpenAiProviderConfigDict(TypedDict, total=False):
    """"""

    direct: VariableOrOptional[
        ModelProviderServiceConfigAzureOpenAiProviderDirectConfigParam
    ]
    """
    Azure OpenAI endpoint and authentication configuration.
    """


ModelProviderServiceConfigAzureOpenAiProviderConfigParam = (
    ModelProviderServiceConfigAzureOpenAiProviderConfigDict
    | ModelProviderServiceConfigAzureOpenAiProviderConfig
)
