# Code generated by pydabs-codegen. DO NOT EDIT.

from enum import Enum
from typing import Literal


class DiskTypeEbsVolumeType(Enum):
    """
    All EBS volume types that Databricks supports.
    See https://aws.amazon.com/ebs/details/ for details.
    """

    GENERAL_PURPOSE_SSD = "GENERAL_PURPOSE_SSD"
    THROUGHPUT_OPTIMIZED_HDD = "THROUGHPUT_OPTIMIZED_HDD"


DiskTypeEbsVolumeTypeParam = (
    Literal["GENERAL_PURPOSE_SSD", "THROUGHPUT_OPTIMIZED_HDD"] | DiskTypeEbsVolumeType
)
