# Code generated by pydabs-codegen. DO NOT EDIT.

from enum import Enum
from typing import Literal


class DiskTypeAzureDiskVolumeType(Enum):
    """
    All Azure Disk types that Databricks supports.
    See https://docs.microsoft.com/en-us/azure/storage/storage-about-disks-and-vhds-linux#types-of-disks
    """

    PREMIUM_LRS = "PREMIUM_LRS"
    STANDARD_LRS = "STANDARD_LRS"


DiskTypeAzureDiskVolumeTypeParam = (
    Literal["PREMIUM_LRS", "STANDARD_LRS"] | DiskTypeAzureDiskVolumeType
)
