# Code generated by pydabs-codegen. DO NOT EDIT.

from dataclasses import dataclass
from typing import TYPE_CHECKING, TypedDict

from databricks.bundles.core._transform import _transform
from databricks.bundles.core._transform_to_json import _transform_to_json_value
from databricks.bundles.core._variable import VariableOrOptional
from databricks.bundles.instance_pools._models.instance_pool_azure_attributes_availability import (
    InstancePoolAzureAttributesAvailability,
    InstancePoolAzureAttributesAvailabilityParam,
)

if TYPE_CHECKING:
    from typing_extensions import Self


@dataclass(kw_only=True)
class InstancePoolAzureAttributes:
    """
    Attributes set during instance pool creation which are related to Azure.
    """

    availability: VariableOrOptional[InstancePoolAzureAttributesAvailability] = None
    """
    Availability type used for the spot nodes.
    """

    capacity_reservation_group: VariableOrOptional[str] = None
    """
    The Azure capacity reservation group resource ID to use for launching VMs in this pool.
    When specified, VMs will be launched using the provided capacity reservation.
    
    NOTE: Omitting this field will clear any existing configured capacity reservation group on the pool.
    
    Capacity reservations can only be specified when the workspace uses injected vnet (i.e. customer defined vnet not
    managed by databricks). Ensure the databricks-login-prod Enterprise Application is granted the following four permissions:
    1. Microsoft.Compute/capacityReservationGroups/read
    2. Microsoft.Compute/capacityReservationGroups/deploy/action
    3. Microsoft.Compute/capacityReservationGroups/capacityReservations/read
    4. Microsoft.Compute/capacityReservationGroups/capacityReservations/deploy/action
    
    Format: `/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Compute/capacityReservationGroups/{capacityReservationGroupName}`
    """

    spot_bid_max_price: VariableOrOptional[float] = None
    """
    With variable pricing, you have option to set a max price, in US dollars (USD)
    For example, the value 2 would be a max price of $2.00 USD per hour.
    If you set the max price to be -1, the VM won't be evicted based on price.
    The price for the VM will be the current price for spot or the price for a standard VM,
    which ever is less, as long as there is capacity and quota available.
    """

    @classmethod
    def from_dict(cls, value: "InstancePoolAzureAttributesDict") -> "Self":
        return _transform(cls, value)

    def as_dict(self) -> "InstancePoolAzureAttributesDict":
        return _transform_to_json_value(self)  # type:ignore


class InstancePoolAzureAttributesDict(TypedDict, total=False):
    """"""

    availability: VariableOrOptional[InstancePoolAzureAttributesAvailabilityParam]
    """
    Availability type used for the spot nodes.
    """

    capacity_reservation_group: VariableOrOptional[str]
    """
    The Azure capacity reservation group resource ID to use for launching VMs in this pool.
    When specified, VMs will be launched using the provided capacity reservation.
    
    NOTE: Omitting this field will clear any existing configured capacity reservation group on the pool.
    
    Capacity reservations can only be specified when the workspace uses injected vnet (i.e. customer defined vnet not
    managed by databricks). Ensure the databricks-login-prod Enterprise Application is granted the following four permissions:
    1. Microsoft.Compute/capacityReservationGroups/read
    2. Microsoft.Compute/capacityReservationGroups/deploy/action
    3. Microsoft.Compute/capacityReservationGroups/capacityReservations/read
    4. Microsoft.Compute/capacityReservationGroups/capacityReservations/deploy/action
    
    Format: `/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Compute/capacityReservationGroups/{capacityReservationGroupName}`
    """

    spot_bid_max_price: VariableOrOptional[float]
    """
    With variable pricing, you have option to set a max price, in US dollars (USD)
    For example, the value 2 would be a max price of $2.00 USD per hour.
    If you set the max price to be -1, the VM won't be evicted based on price.
    The price for the VM will be the current price for spot or the price for a standard VM,
    which ever is less, as long as there is capacity and quota available.
    """


InstancePoolAzureAttributesParam = (
    InstancePoolAzureAttributesDict | InstancePoolAzureAttributes
)
