# Code generated by pydabs-codegen. DO NOT EDIT.

from dataclasses import dataclass
from typing import TYPE_CHECKING, TypedDict

from databricks.bundles.core._transform import _transform
from databricks.bundles.core._transform_to_json import _transform_to_json_value
from databricks.bundles.core._variable import VariableOrOptional
from databricks.bundles.instance_pools._models.gcp_availability import (
    GcpAvailability,
    GcpAvailabilityParam,
)

if TYPE_CHECKING:
    from typing_extensions import Self


@dataclass(kw_only=True)
class InstancePoolGcpAttributes:
    """
    Attributes set during instance pool creation which are related to GCP.
    """

    gcp_availability: VariableOrOptional[GcpAvailability] = None
    """
    Availability type for the instances in the pool. One of:
    
    - `ON_DEMAND_GCP`: the pool uses on-demand instances only.
    - `PREEMPTIBLE_GCP`: the pool uses preemptible instances only.
    - `PREEMPTIBLE_WITH_FALLBACK_GCP`: the pool acquires preemptible instances first, and falls
      back to on-demand instances when preemptible capacity is unavailable.
    """

    local_ssd_count: VariableOrOptional[int] = None
    """
    If provided, each node in the instance pool will have this number of local SSDs attached.
    Each local SSD is 375GB in size. Refer to [GCP documentation](https://cloud.google.com/compute/docs/disks/local-ssd#choose_number_local_ssds)
    for the supported number of local SSDs for each instance type.
    """

    zone_id: VariableOrOptional[str] = None
    """
    Identifier for the availability zone/datacenter in which the cluster resides.
    This string will be of a form like "us-west1-a". The provided availability
    zone must be in the same region as the Databricks workspace. For example, "us-west1-a"
    is not a valid zone id if the Databricks workspace resides in the "us-east1" region.
    This is an optional field at instance pool creation, and if not specified, a default zone will be used.
    
    This field can be one of the following:
    - "HA" => High availability, spread nodes across availability zones for a Databricks deployment region
    - "auto" => Auto-AZ. Databricks selects the availability zone for each cluster independently when the cluster launches, and retries another zone if the cluster can't be fulfilled because of insufficient capacity or quota. All nodes in a cluster land in the same zone, and different clusters backed by the pool can run in different zones.
    - A GCP availability zone => Pick One of the available zones for (machine type + region) from https://cloud.google.com/compute/docs/regions-zones (e.g. "us-west1-a").
    
    If empty, Databricks picks an availability zone to schedule the cluster on.
    
    You can change the zone on an existing pool. New clusters use the updated zone, and existing
    clusters keep the zone they launched with.
    """

    @classmethod
    def from_dict(cls, value: "InstancePoolGcpAttributesDict") -> "Self":
        return _transform(cls, value)

    def as_dict(self) -> "InstancePoolGcpAttributesDict":
        return _transform_to_json_value(self)  # type:ignore


class InstancePoolGcpAttributesDict(TypedDict, total=False):
    """"""

    gcp_availability: VariableOrOptional[GcpAvailabilityParam]
    """
    Availability type for the instances in the pool. One of:
    
    - `ON_DEMAND_GCP`: the pool uses on-demand instances only.
    - `PREEMPTIBLE_GCP`: the pool uses preemptible instances only.
    - `PREEMPTIBLE_WITH_FALLBACK_GCP`: the pool acquires preemptible instances first, and falls
      back to on-demand instances when preemptible capacity is unavailable.
    """

    local_ssd_count: VariableOrOptional[int]
    """
    If provided, each node in the instance pool will have this number of local SSDs attached.
    Each local SSD is 375GB in size. Refer to [GCP documentation](https://cloud.google.com/compute/docs/disks/local-ssd#choose_number_local_ssds)
    for the supported number of local SSDs for each instance type.
    """

    zone_id: VariableOrOptional[str]
    """
    Identifier for the availability zone/datacenter in which the cluster resides.
    This string will be of a form like "us-west1-a". The provided availability
    zone must be in the same region as the Databricks workspace. For example, "us-west1-a"
    is not a valid zone id if the Databricks workspace resides in the "us-east1" region.
    This is an optional field at instance pool creation, and if not specified, a default zone will be used.
    
    This field can be one of the following:
    - "HA" => High availability, spread nodes across availability zones for a Databricks deployment region
    - "auto" => Auto-AZ. Databricks selects the availability zone for each cluster independently when the cluster launches, and retries another zone if the cluster can't be fulfilled because of insufficient capacity or quota. All nodes in a cluster land in the same zone, and different clusters backed by the pool can run in different zones.
    - A GCP availability zone => Pick One of the available zones for (machine type + region) from https://cloud.google.com/compute/docs/regions-zones (e.g. "us-west1-a").
    
    If empty, Databricks picks an availability zone to schedule the cluster on.
    
    You can change the zone on an existing pool. New clusters use the updated zone, and existing
    clusters keep the zone they launched with.
    """


InstancePoolGcpAttributesParam = (
    InstancePoolGcpAttributesDict | InstancePoolGcpAttributes
)
