# Code generated by pydabs-codegen. DO NOT EDIT.

from enum import Enum
from typing import Literal


class InstancePoolAwsAttributesAvailability(Enum):
    """
    The set of AWS availability types supported when setting up nodes for a cluster.
    """

    SPOT = "SPOT"
    ON_DEMAND = "ON_DEMAND"


InstancePoolAwsAttributesAvailabilityParam = (
    Literal["SPOT", "ON_DEMAND"] | InstancePoolAwsAttributesAvailability
)
