# Code generated by pydabs-codegen. DO NOT EDIT.

from enum import Enum
from typing import Literal


class InstancePoolPermissionLevel(Enum):
    """
    Permission level
    """

    CAN_MANAGE = "CAN_MANAGE"
    CAN_ATTACH_TO = "CAN_ATTACH_TO"


InstancePoolPermissionLevelParam = (
    Literal["CAN_MANAGE", "CAN_ATTACH_TO"] | InstancePoolPermissionLevel
)
