/**
 * Standalone script to regenerate appKitTypes.d.ts without running the dev server.
 * Usage: npx tsx scripts/generate-types.ts
 */

import fs from 'node:fs';
import path from 'node:path';
import { createAuxiliaryTypeStore, printNode, zodToTs } from 'zod-to-ts';
import { querySchemas } from '../config/queries/schema.js';

const TYPE_FILE_NAME = 'appKitTypes.d.ts';
const TYPE_PATH = path.join(process.cwd(), 'client', 'src');

function indentType(typeString: string, baseIndent: string): string {
  const lines = typeString.split('\n');
  if (lines.length === 1) return typeString;
  return lines.map((line, index) => (index === 0 ? line : baseIndent + line)).join('\n');
}

function readExistingPluginRegistry(filePath: string): string {
  if (!fs.existsSync(filePath)) return '';
  const content = fs.readFileSync(filePath, 'utf-8');
  const pluginMatch = content.match(/interface PluginRegistry \{([\s\S]*?)\n {2}\}/);
  return pluginMatch?.[1] ?? '';
}

function generateTypes(): void {
  const filePath = path.join(TYPE_PATH, TYPE_FILE_NAME);
  const existingPluginRegistry = readExistingPluginRegistry(filePath);

  const auxiliaryTypeStore = createAuxiliaryTypeStore();
  let queryTypes = '';

  if (querySchemas && Object.keys(querySchemas).length > 0) {
    queryTypes = Object.entries(querySchemas)
      .map(([queryKey, schema]) => {
        const { node } = zodToTs(schema, { auxiliaryTypeStore });
        return `    ${queryKey}: ${indentType(printNode(node), '    ')};`;
      })
      .join('\n');
  }

  const content = `// Auto-generated by AppKit - DO NOT EDIT
import "@databricks/app-kit-ui/react";

declare module "@databricks/app-kit-ui/react" {
  interface PluginRegistry {
${existingPluginRegistry}
  }
${queryTypes ? `\n  interface QueryRegistry {\n${queryTypes}\n  }` : ''}
}
`;

  fs.writeFileSync(filePath, content, 'utf-8');
  console.log(`[generate-types] Types generated: ${filePath}`);
}

generateTypes();
