Cloud = false
CLIVersions.CLI_1_8 = "1.8.0"
EnvMatrix.CLI_VERSION = ["old", "new"]
EnvMatrix.DATABRICKS_BUNDLE_ENGINE = ["direct"]
EnvMatrix.DMS = [""]
EnvMatrix.STATE_FEATURE = ["none", "deployment_history", "future_feature"]
EnvMatrix.STATE_VERSION = ["2", "3"]
