# Code generated by pydabs-codegen. DO NOT EDIT.

from dataclasses import dataclass
from typing import TYPE_CHECKING, TypedDict

from databricks.bundles.core._transform import _transform
from databricks.bundles.core._transform_to_json import _transform_to_json_value
from databricks.bundles.core._variable import VariableOrOptional

if TYPE_CHECKING:
    from typing_extensions import Self


@dataclass(kw_only=True)
class EmbeddingSourceColumn:
    """"""

    embedding_model_endpoint_name: VariableOrOptional[str] = None
    """
    Name of the embedding model endpoint, used by default for both ingestion and querying.
    """

    model_endpoint_name_for_query: VariableOrOptional[str] = None
    """
    Name of the embedding model endpoint which, if specified, is used for querying (not ingestion).
    """

    name: VariableOrOptional[str] = None
    """
    Name of the column
    """

    @classmethod
    def from_dict(cls, value: "EmbeddingSourceColumnDict") -> "Self":
        return _transform(cls, value)

    def as_dict(self) -> "EmbeddingSourceColumnDict":
        return _transform_to_json_value(self)  # type:ignore


class EmbeddingSourceColumnDict(TypedDict, total=False):
    """"""

    embedding_model_endpoint_name: VariableOrOptional[str]
    """
    Name of the embedding model endpoint, used by default for both ingestion and querying.
    """

    model_endpoint_name_for_query: VariableOrOptional[str]
    """
    Name of the embedding model endpoint which, if specified, is used for querying (not ingestion).
    """

    name: VariableOrOptional[str]
    """
    Name of the column
    """


EmbeddingSourceColumnParam = EmbeddingSourceColumnDict | EmbeddingSourceColumn
