# Code generated by pydabs-codegen. DO NOT EDIT.

from dataclasses import dataclass
from typing import TYPE_CHECKING, TypedDict

from databricks.bundles.core._transform import _transform
from databricks.bundles.core._transform_to_json import _transform_to_json_value
from databricks.bundles.core._variable import VariableOrOptional

if TYPE_CHECKING:
    from typing_extensions import Self


@dataclass(kw_only=True)
class EmbeddingVectorColumn:
    """"""

    embedding_dimension: VariableOrOptional[int] = None
    """
    Dimension of the embedding vector
    """

    name: VariableOrOptional[str] = None
    """
    Name of the column
    """

    @classmethod
    def from_dict(cls, value: "EmbeddingVectorColumnDict") -> "Self":
        return _transform(cls, value)

    def as_dict(self) -> "EmbeddingVectorColumnDict":
        return _transform_to_json_value(self)  # type:ignore


class EmbeddingVectorColumnDict(TypedDict, total=False):
    """"""

    embedding_dimension: VariableOrOptional[int]
    """
    Dimension of the embedding vector
    """

    name: VariableOrOptional[str]
    """
    Name of the column
    """


EmbeddingVectorColumnParam = EmbeddingVectorColumnDict | EmbeddingVectorColumn
