# Code generated by pydabs-codegen. DO NOT EDIT.

from enum import Enum
from typing import Literal


class IndexSubtype(Enum):
    """
    The subtype of the AI Search index, determining the indexing and retrieval strategy.
    - `VECTOR`: Not supported. Use `HYBRID` instead.
    - `FULL_TEXT`: An index that uses full-text search without vector embeddings.
    - `HYBRID`: An index that uses vector embeddings for similarity search and hybrid search.
    """

    VECTOR = "VECTOR"
    FULL_TEXT = "FULL_TEXT"
    HYBRID = "HYBRID"


IndexSubtypeParam = Literal["VECTOR", "FULL_TEXT", "HYBRID"] | IndexSubtype
