# Code generated by pydabs-codegen. DO NOT EDIT.

from dataclasses import dataclass
from typing import TYPE_CHECKING, TypedDict

from databricks.bundles.core._resource import Resource
from databricks.bundles.core._transform import _transform
from databricks.bundles.core._transform_to_json import _transform_to_json_value
from databricks.bundles.core._variable import VariableOr, VariableOrOptional
from databricks.bundles.database_catalogs._models.lifecycle import (
    Lifecycle,
    LifecycleParam,
)

if TYPE_CHECKING:
    from typing_extensions import Self


@dataclass(kw_only=True)
class DatabaseCatalog(Resource):
    """"""

    database_instance_name: VariableOr[str]
    """
    [Public Preview] The name of the DatabaseInstance housing the database.
    """

    database_name: VariableOr[str]
    """
    [Public Preview] The name of the database (in an instance) associated with the catalog.
    """

    name: VariableOr[str]
    """
    [Public Preview] The name of the catalog in UC.
    """

    create_database_if_not_exists: VariableOrOptional[bool] = None
    """
    [Public Preview]
    """

    lifecycle: VariableOrOptional[Lifecycle] = None
    """
    Settings that control the deployment lifecycle of the resource, such as preventing it from being destroyed.
    """

    @classmethod
    def from_dict(cls, value: "DatabaseCatalogDict") -> "Self":
        return _transform(cls, value)

    def as_dict(self) -> "DatabaseCatalogDict":
        return _transform_to_json_value(self)  # type:ignore


class DatabaseCatalogDict(TypedDict, total=False):
    """"""

    database_instance_name: VariableOr[str]
    """
    [Public Preview] The name of the DatabaseInstance housing the database.
    """

    database_name: VariableOr[str]
    """
    [Public Preview] The name of the database (in an instance) associated with the catalog.
    """

    name: VariableOr[str]
    """
    [Public Preview] The name of the catalog in UC.
    """

    create_database_if_not_exists: VariableOrOptional[bool]
    """
    [Public Preview]
    """

    lifecycle: VariableOrOptional[LifecycleParam]
    """
    Settings that control the deployment lifecycle of the resource, such as preventing it from being destroyed.
    """


DatabaseCatalogParam = DatabaseCatalogDict | DatabaseCatalog
