#!/bin/bash

envsubst < databricks.yml.tmpl > databricks.yml

cleanup() {
  trace $CLI bundle destroy --auto-approve -t dev
}
trap cleanup EXIT

touch dummy.whl
$CLI bundle deploy -t dev
job_id="$(read_id.py my_job)"


title "Modify fields in target override"
edit_resource.py jobs $job_id <<EOF
r["max_concurrent_runs"] = 10
r["tags"]["env"] = "staging"
r["tags"]["owner"] = "data-team"
EOF

title "Detect and save changes"
echo
cp databricks.yml databricks.yml.backup
$CLI bundle config-remote-sync -t dev --save

title "Configuration changes"
echo
trace diff.py databricks.yml.backup databricks.yml
rm databricks.yml.backup
