#!/bin/bash

touch dummy.whl
$CLI bundle deploy
pipeline_id="$(read_id.py my_pipeline)"


title "Add and modify pipeline configuration"
edit_resource.py pipelines $pipeline_id <<EOF
r["configuration"]["key1"] = "new_value"
r["configuration"]["key2"] = "value2"
EOF

title "Detect and save changes"
echo
cp databricks.yml databricks.yml.backup
$CLI bundle config-remote-sync --save

title "Configuration changes"
echo
diff -u databricks.yml.backup databricks.yml || true
rm databricks.yml.backup
