#!/bin/bash
envsubst < databricks.yml.tmpl > databricks.yml

cleanup() {
    trace $CLI bundle destroy --auto-approve
    rm -f out.requests.txt
}
trap cleanup EXIT

trace $CLI bundle debug plan > out.first-plan.$DATABRICKS_BUNDLE_ENGINE.json
trace $CLI bundle deploy

ENDPOINT_ID=$($CLI bundle summary -o json | jq -r '.resources.model_serving_endpoints.test_endpoint.id')
echo "$ENDPOINT_ID:ENDPOINT_ID" >> ACC_REPLS
trace $CLI serving-endpoints get "${ENDPOINT_ID}" | jq '.config.served_entities[0].external_model.name'

trace update_file.py databricks.yml 'name: gpt-4o-mini' 'name: gpt-4o'
trace $CLI bundle debug plan > out.second-plan.$DATABRICKS_BUNDLE_ENGINE.json
trace $CLI bundle deploy

trace print_requests.py //serving-endpoints

trace $CLI serving-endpoints get "${ENDPOINT_ID}" | jq '.config.served_entities[0].external_model.name'
