resources:
  pipelines:
    my_pipelines:
      configuration:
        spark.sql.ansi.enabled: "true"
      name: "test-pipeline"
      libraries:
        - notebook:
            path: "../test-notebook.py"
      lifecycle:
        prevent_destroy: true
      schema: test-schema
      catalog: main
