#!/bin/bash
set -e

# Test valid artifact path with /Volumes
export DATABRICKS_BUNDLE_ROOT="valid"
$CLI bundle validate

# Test invalid root path with /Volumes
export DATABRICKS_BUNDLE_ROOT="invalid_root"
errcode trace $CLI bundle validate

# Test invalid file path with /Volumes
export DATABRICKS_BUNDLE_ROOT="invalid_file"
errcode trace $CLI bundle validate

# Test invalid state path with /Volumes
export DATABRICKS_BUNDLE_ROOT="invalid_state"
errcode trace $CLI bundle validate

# Test invalid resource path with /Volumes
export DATABRICKS_BUNDLE_ROOT="invalid_resource"
errcode trace $CLI bundle validate
