# Code generated by pydabs-codegen. DO NOT EDIT.

from dataclasses import dataclass
from typing import TYPE_CHECKING, TypedDict

from databricks.bundles.core._transform import _transform
from databricks.bundles.core._transform_to_json import _transform_to_json_value
from databricks.bundles.core._variable import VariableOr, VariableOrOptional
from databricks.bundles.quality_monitors._models.monitor_cron_schedule_pause_status import (
    MonitorCronSchedulePauseStatus,
    MonitorCronSchedulePauseStatusParam,
)

if TYPE_CHECKING:
    from typing_extensions import Self


@dataclass(kw_only=True)
class MonitorCronSchedule:
    """"""

    quartz_cron_expression: VariableOr[str]
    """
    The expression that determines when to run the monitor. See [examples](https://www.quartz-scheduler.org/documentation/quartz-2.3.0/tutorials/crontrigger.html).
    """

    timezone_id: VariableOr[str]
    """
    The timezone id (e.g., ``PST``) in which to evaluate the quartz expression.
    """

    pause_status: VariableOrOptional[MonitorCronSchedulePauseStatus] = None
    """
    Read only field that indicates whether a schedule is paused or not.
    """

    @classmethod
    def from_dict(cls, value: "MonitorCronScheduleDict") -> "Self":
        return _transform(cls, value)

    def as_dict(self) -> "MonitorCronScheduleDict":
        return _transform_to_json_value(self)  # type:ignore


class MonitorCronScheduleDict(TypedDict, total=False):
    """"""

    quartz_cron_expression: VariableOr[str]
    """
    The expression that determines when to run the monitor. See [examples](https://www.quartz-scheduler.org/documentation/quartz-2.3.0/tutorials/crontrigger.html).
    """

    timezone_id: VariableOr[str]
    """
    The timezone id (e.g., ``PST``) in which to evaluate the quartz expression.
    """

    pause_status: VariableOrOptional[MonitorCronSchedulePauseStatusParam]
    """
    Read only field that indicates whether a schedule is paused or not.
    """


MonitorCronScheduleParam = MonitorCronScheduleDict | MonitorCronSchedule
