# Code generated by pydabs-codegen. DO NOT EDIT.

from dataclasses import dataclass
from typing import TYPE_CHECKING, TypedDict

from databricks.bundles.core._transform import _transform
from databricks.bundles.core._transform_to_json import _transform_to_json_value
from databricks.bundles.core._variable import VariableOrOptional

if TYPE_CHECKING:
    from typing_extensions import Self


@dataclass(kw_only=True)
class MonitorDataClassificationConfig:
    """
    :meta private: [EXPERIMENTAL]

    Data classification related configuration.
    """

    enabled: VariableOrOptional[bool] = None
    """
    :meta private: [EXPERIMENTAL]
    
    [Private Preview] Whether to enable data classification.
    """

    @classmethod
    def from_dict(cls, value: "MonitorDataClassificationConfigDict") -> "Self":
        return _transform(cls, value)

    def as_dict(self) -> "MonitorDataClassificationConfigDict":
        return _transform_to_json_value(self)  # type:ignore


class MonitorDataClassificationConfigDict(TypedDict, total=False):
    """"""

    enabled: VariableOrOptional[bool]
    """
    :meta private: [EXPERIMENTAL]
    
    [Private Preview] Whether to enable data classification.
    """


MonitorDataClassificationConfigParam = (
    MonitorDataClassificationConfigDict | MonitorDataClassificationConfig
)
