# Code generated by pydabs-codegen. DO NOT EDIT.

from dataclasses import dataclass, field
from typing import TYPE_CHECKING, TypedDict

from databricks.bundles.core._transform import _transform
from databricks.bundles.core._transform_to_json import _transform_to_json_value
from databricks.bundles.core._variable import VariableOr, VariableOrList

if TYPE_CHECKING:
    from typing_extensions import Self


@dataclass(kw_only=True)
class MonitorTimeSeries:
    """
    Time series analysis configuration.
    """

    timestamp_col: VariableOr[str]
    """
    Column for the timestamp.
    """

    granularities: VariableOrList[str] = field(default_factory=list)
    """
    Granularities for aggregating data into time windows based on their timestamp. Valid values are 5 minutes, 30 minutes, 1 hour, 1 day, n weeks, 1 month, or 1 year.
    """

    @classmethod
    def from_dict(cls, value: "MonitorTimeSeriesDict") -> "Self":
        return _transform(cls, value)

    def as_dict(self) -> "MonitorTimeSeriesDict":
        return _transform_to_json_value(self)  # type:ignore


class MonitorTimeSeriesDict(TypedDict, total=False):
    """"""

    timestamp_col: VariableOr[str]
    """
    Column for the timestamp.
    """

    granularities: VariableOrList[str]
    """
    Granularities for aggregating data into time windows based on their timestamp. Valid values are 5 minutes, 30 minutes, 1 hour, 1 day, n weeks, 1 month, or 1 year.
    """


MonitorTimeSeriesParam = MonitorTimeSeriesDict | MonitorTimeSeries
