# Code generated by pydabs-codegen. DO NOT EDIT.

from dataclasses import dataclass, field
from typing import TYPE_CHECKING, TypedDict

from databricks.bundles.core._transform import _transform
from databricks.bundles.core._transform_to_json import _transform_to_json_value
from databricks.bundles.core._variable import (
    VariableOr,
    VariableOrList,
    VariableOrOptional,
)
from databricks.bundles.quality_monitors._models.monitor_inference_log_problem_type import (
    MonitorInferenceLogProblemType,
    MonitorInferenceLogProblemTypeParam,
)

if TYPE_CHECKING:
    from typing_extensions import Self


@dataclass(kw_only=True)
class MonitorInferenceLog:
    """"""

    model_id_col: VariableOr[str]
    """
    Column for the model identifier.
    """

    prediction_col: VariableOr[str]
    """
    Column for the prediction.
    """

    problem_type: VariableOr[MonitorInferenceLogProblemType]
    """
    Problem type the model aims to solve.
    """

    timestamp_col: VariableOr[str]
    """
    Column for the timestamp.
    """

    granularities: VariableOrList[str] = field(default_factory=list)
    """
    Granularities for aggregating data into time windows based on their timestamp. Valid values are 5 minutes, 30 minutes, 1 hour, 1 day, n weeks, 1 month, or 1 year.
    """

    label_col: VariableOrOptional[str] = None
    """
    Column for the label.
    """

    prediction_proba_col: VariableOrOptional[str] = None
    """
    Column for prediction probabilities
    """

    @classmethod
    def from_dict(cls, value: "MonitorInferenceLogDict") -> "Self":
        return _transform(cls, value)

    def as_dict(self) -> "MonitorInferenceLogDict":
        return _transform_to_json_value(self)  # type:ignore


class MonitorInferenceLogDict(TypedDict, total=False):
    """"""

    model_id_col: VariableOr[str]
    """
    Column for the model identifier.
    """

    prediction_col: VariableOr[str]
    """
    Column for the prediction.
    """

    problem_type: VariableOr[MonitorInferenceLogProblemTypeParam]
    """
    Problem type the model aims to solve.
    """

    timestamp_col: VariableOr[str]
    """
    Column for the timestamp.
    """

    granularities: VariableOrList[str]
    """
    Granularities for aggregating data into time windows based on their timestamp. Valid values are 5 minutes, 30 minutes, 1 hour, 1 day, n weeks, 1 month, or 1 year.
    """

    label_col: VariableOrOptional[str]
    """
    Column for the label.
    """

    prediction_proba_col: VariableOrOptional[str]
    """
    Column for prediction probabilities
    """


MonitorInferenceLogParam = MonitorInferenceLogDict | MonitorInferenceLog
