# Code generated by pydabs-codegen. DO NOT EDIT.

from enum import Enum
from typing import Literal


class MonitorMetricType(Enum):
    """
    Can only be one of ``\"CUSTOM_METRIC_TYPE_AGGREGATE\"``, ``\"CUSTOM_METRIC_TYPE_DERIVED\"``, or ``\"CUSTOM_METRIC_TYPE_DRIFT\"``.
    The ``\"CUSTOM_METRIC_TYPE_AGGREGATE\"`` and ``\"CUSTOM_METRIC_TYPE_DERIVED\"`` metrics
    are computed on a single table, whereas the ``\"CUSTOM_METRIC_TYPE_DRIFT\"`` compare metrics across
    baseline and input table, or across the two consecutive time windows.
    - CUSTOM_METRIC_TYPE_AGGREGATE: only depend on the existing columns in your table
    - CUSTOM_METRIC_TYPE_DERIVED: depend on previously computed aggregate metrics
    - CUSTOM_METRIC_TYPE_DRIFT:  depend on previously computed aggregate or derived metrics
    """

    CUSTOM_METRIC_TYPE_AGGREGATE = "CUSTOM_METRIC_TYPE_AGGREGATE"
    CUSTOM_METRIC_TYPE_DERIVED = "CUSTOM_METRIC_TYPE_DERIVED"
    CUSTOM_METRIC_TYPE_DRIFT = "CUSTOM_METRIC_TYPE_DRIFT"


MonitorMetricTypeParam = (
    Literal[
        "CUSTOM_METRIC_TYPE_AGGREGATE",
        "CUSTOM_METRIC_TYPE_DERIVED",
        "CUSTOM_METRIC_TYPE_DRIFT",
    ]
    | MonitorMetricType
)
