# Code generated by pydabs-codegen. DO NOT EDIT.

from enum import Enum
from typing import Literal


class MonitorInferenceLogProblemType(Enum):
    PROBLEM_TYPE_CLASSIFICATION = "PROBLEM_TYPE_CLASSIFICATION"
    PROBLEM_TYPE_REGRESSION = "PROBLEM_TYPE_REGRESSION"


MonitorInferenceLogProblemTypeParam = (
    Literal["PROBLEM_TYPE_CLASSIFICATION", "PROBLEM_TYPE_REGRESSION"]
    | MonitorInferenceLogProblemType
)
