#!/usr/bin/env python3
"""Generate databricks.yml with every settable string field set to "".

base.yml defines a deployable skeleton per resource, including whichever nested
blocks we want to cover (job_clusters[*].new_cluster, git_source, one cloud
attributes block, ...). This script walks every resource subtree and sets every
settable string LEAF (including nested ones) that the base doesn't already set
to "". Coverage is therefore scoped to the blocks present in base.yml, which is
how we avoid mutually-exclusive blocks (aws vs gcp attributes, git_source vs
none) that would make terraform abort.

A field is settable/eligible when out.fields.txt types it as `string` (this
skips enums, which are named types) with flag ALL or INPUT, and it is not
output_only (<resource_type>.generated.yaml), a bundle-framework field, or a
known terraform-erroring field.

Run from the repo root; writes databricks.yml in the test directory:
  acceptance/bundle/empty_string_dropped/gen_empty_config.py
"""

import re
from pathlib import Path

import yaml

FIELDS = Path("acceptance/bundle/refschema/out.fields.txt")
DRESOURCES = Path("bundle/direct/dresources")
GENERATED_SUFFIX = ".generated.yaml"
TESTDIR = Path("acceptance/bundle/empty_string_dropped")
BASE = TESTDIR / "base.yml"

# Bundle-framework fields present on every resource; not real API inputs.
FRAMEWORK_FIELDS = {"id", "url", "modified_status"}

# Leaf field names that make terraform error at plan time (ConflictsWith, enum
# validation on string-typed fields, computed attributes), so no request is
# recorded. Applied per resource type. Matched by leaf name at any depth.
TERRAFORM_ERRORS = {
    "clusters": {"instance_pool_id", "driver_instance_pool_id", "driver_node_type_id"},
    "jobs": {
        "instance_pool_id",
        "driver_instance_pool_id",
        "driver_node_type_id",
        # git_source: branch/commit/tag are mutually exclusive; base sets branch.
        "git_commit",
        "git_tag",
    },
    "pipelines": {"channel", "edition", "catalog", "storage", "schema", "target"},
    "sql_warehouses": {"creator_name"},
}


def string_leaf_parents():
    """Map resource type -> {parent_schema_path: {leaf field names}}.

    Schema paths mirror out.fields.txt: dotted segments, list elements marked
    with "[*]" (e.g. "job_clusters[*].new_cluster"). Only string leaves that are
    real object fields are kept: names ending in "[*]" (string-array elements) or
    "*" (map values) are skipped.
    """
    pat = re.compile(r"^resources\.([a-z_]+)\.\*\.(.+)$")
    result = {}
    for line in FIELDS.read_text().splitlines():
        parts = line.split("\t")
        if len(parts) < 3:
            continue
        path, typ, flag = parts[0], parts[1], parts[2]
        if typ != "string" or flag not in ("ALL", "INPUT"):
            continue
        m = pat.match(path)
        if not m:
            continue
        rtype, rel = m.group(1), m.group(2)
        if rel.endswith(("[*]", ".*")) or rel == "*":
            continue
        parent, _, leaf = rel.rpartition(".")
        result.setdefault(rtype, {}).setdefault(parent, set()).add(leaf)
    return result


def output_only_fields():
    """Map resource type -> {output_only field paths} (user cannot set)."""
    result = {}
    for path in sorted(DRESOURCES.glob("*" + GENERATED_SUFFIX)):
        spec = yaml.safe_load(path.read_text()) or {}
        fields = set()
        for entry in spec.get("ignore_remote_changes") or []:
            if str(entry.get("reason", "")).startswith("spec:output_only"):
                fields.add(entry["field"])
        result[path.name.removesuffix(GENERATED_SUFFIX)] = fields
    return result


def fill(node, schema_path, parents, excluded):
    """Recursively set settable string leaves under node to ""; recurse into blocks.

    schema_path uses out.fields.txt syntax (list elements marked "[*]") to look up
    eligible leaves for the current object.
    """
    if isinstance(node, dict):
        for leaf in parents.get(schema_path, set()):
            if leaf not in node and leaf not in excluded:
                node[leaf] = ""
        for key, value in list(node.items()):
            child = f"{schema_path}.{key}" if schema_path else key
            fill(value, child, parents, excluded)
    elif isinstance(node, list):
        for item in node:
            fill(item, schema_path + "[*]", parents, excluded)


def main():
    parents = string_leaf_parents()
    output_only = output_only_fields()
    base = yaml.safe_load(BASE.read_text())

    for rtype, entries in sorted(base.get("resources", {}).items()):
        excluded = output_only.get(rtype, set()) | FRAMEWORK_FIELDS | TERRAFORM_ERRORS.get(rtype, set())
        for cfg in entries.values():
            fill(cfg, "", parents.get(rtype, {}), excluded)

    (TESTDIR / "databricks.yml").write_text(
        "# Generated by gen_empty_config.py. Do not edit; edit base.yml and regenerate.\n"
        + yaml.dump(base, sort_keys=True, default_flow_style=False)
    )


if __name__ == "__main__":
    main()
