#!/bin/bash

envsubst < databricks.yml.tmpl > databricks.yml

touch dummy.whl
$CLI bundle deploy
job_id="$(read_id.py my_job)"


title "Modify job fields remotely"
edit_resource.py jobs $job_id <<EOF
r["email_notifications"]["on_failure"] = ["failure@example.com"]
r["email_notifications"]["no_alert_for_skipped_runs"] = True
r["parameters"].append({"name": "region", "default": "us-east-1"})
r["trigger"]["periodic"]["interval"] = 2
r["tags"]["team"] = "data"
EOF

# TODO add support for permissions
# title "Modify job permissions remotely"
# current_user=$($CLI current-user me --output json | jq -r .userName)
# cat > permissions.json <<EOF
# {
#   "access_control_list": [
#     {"permission_level": "IS_OWNER", "user_name": "$current_user"},
#     {"permission_level": "CAN_MANAGE", "user_name": "viewer@example.com"},
#     {"permission_level": "CAN_MANAGE_RUN", "user_name": "admin@example.com"}
#   ]
# }
# EOF
# $CLI permissions set jobs $job_id --json @permissions.json
# rm permissions.json

title "Detect and save changes"
echo
cp databricks.yml databricks.yml.backup
$CLI bundle config-remote-sync --save

title "Configuration changes"
echo
trace diff.py databricks.yml.backup databricks.yml
rm databricks.yml.backup
