resources:
  pipelines:
    out:
      name: lakeflow-pipeline
      configuration:
        "spark.sql.ansi.enabled": "true"
      libraries:
        - glob:
            include: ../pipeline/transformations/**
        - glob:
            include: /Workspace/Users/foo@databricks.com/another/**
      root_path: ../pipeline
