# Code generated by pydabs-codegen. DO NOT EDIT.

from enum import Enum
from typing import Literal


class RegisteredModelPermissionLevel(Enum):
    """
    Permission level
    """

    CAN_MANAGE = "CAN_MANAGE"
    CAN_MANAGE_PRODUCTION_VERSIONS = "CAN_MANAGE_PRODUCTION_VERSIONS"
    CAN_MANAGE_STAGING_VERSIONS = "CAN_MANAGE_STAGING_VERSIONS"
    CAN_EDIT = "CAN_EDIT"
    CAN_READ = "CAN_READ"


RegisteredModelPermissionLevelParam = (
    Literal[
        "CAN_MANAGE",
        "CAN_MANAGE_PRODUCTION_VERSIONS",
        "CAN_MANAGE_STAGING_VERSIONS",
        "CAN_EDIT",
        "CAN_READ",
    ]
    | RegisteredModelPermissionLevel
)
