# Code generated by pydabs-codegen. DO NOT EDIT.

from dataclasses import dataclass
from typing import TYPE_CHECKING, TypedDict

from databricks.bundles.core._transform import _transform
from databricks.bundles.core._transform_to_json import _transform_to_json_value
from databricks.bundles.core._variable import VariableOrOptional

if TYPE_CHECKING:
    from typing_extensions import Self


@dataclass(kw_only=True)
class JobRunTrigger:
    """"""

    on_bundle_deploy: VariableOrOptional[bool] = None
    """
    If true, re-fire the run on every bundle deploy.
    """

    on_file_change: VariableOrOptional[str] = None
    """
    Path or glob relative to the defining YAML file. It must resolve under the sync root. Re-fire the run when a matched file's content hash changes, or when the set of matches appears or disappears. Only files the bundle syncs are hashed, so .gitignore and sync.exclude apply. Use * to match a single directory level; ** is not supported.
    """

    @classmethod
    def from_dict(cls, value: "JobRunTriggerDict") -> "Self":
        return _transform(cls, value)

    def as_dict(self) -> "JobRunTriggerDict":
        return _transform_to_json_value(self)  # type:ignore


class JobRunTriggerDict(TypedDict, total=False):
    """"""

    on_bundle_deploy: VariableOrOptional[bool]
    """
    If true, re-fire the run on every bundle deploy.
    """

    on_file_change: VariableOrOptional[str]
    """
    Path or glob relative to the defining YAML file. It must resolve under the sync root. Re-fire the run when a matched file's content hash changes, or when the set of matches appears or disappears. Only files the bundle syncs are hashed, so .gitignore and sync.exclude apply. Use * to match a single directory level; ** is not supported.
    """


JobRunTriggerParam = JobRunTriggerDict | JobRunTrigger
