"""Safe starter-test generation for an existing bundle."""

from __future__ import annotations

import json
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from bundletest.project import load_bundle_config


@dataclass(frozen=True)
class GeneratedStarter:
    resource: str
    files: tuple[Path, ...]


def create_starter(root: Path, *, force: bool = False) -> GeneratedStarter:
    config = load_bundle_config(root)
    kind, name = _first_resource(config)
    tests = root / "tests"
    files = (tests / "conftest.py", tests / "test_bundle.py")
    existing = [path for path in files if path.exists()]
    if existing and not force:
        joined = ", ".join(str(path.relative_to(root)) for path in existing)
        raise FileExistsError(f"starter files already exist: {joined}; pass --force to replace them")

    tests.mkdir(parents=True, exist_ok=True)
    files[0].write_text(_conftest())
    files[1].write_text(_starter_test(kind, name))
    return GeneratedStarter(f"{kind}.{name}", files)


def _first_resource(config: dict[str, Any]) -> tuple[str, str]:
    resources = config.get("resources", {}) or {}
    jobs = resources.get("jobs", {}) or {}
    for name, resource in jobs.items():
        if any("sql_task" in task for task in resource.get("tasks", [])):
            return "jobs", name
    for kind, declared in resources.items():
        if isinstance(declared, dict) and declared:
            name = next(iter(declared))
            return kind, name
    raise ValueError("bundle has no declared resources to generate a starter test for")


def _conftest() -> str:
    return '''"""Shared bundletest fixture."""

from pathlib import Path

import pytest
from bundletest import bundle_env

BUNDLE_ROOT = Path(__file__).resolve().parent.parent


@pytest.fixture
def env():
    with bundle_env(str(BUNDLE_ROOT)) as test_env:
        yield test_env
'''


def _starter_test(kind: str, name: str) -> str:
    function_name = re.sub(r"\W+", "_", name).strip("_") or "resource"
    marker = f"{kind}.{name}"
    if kind == "jobs":
        body = f"""    job = env.jobs[{json.dumps(name)}]
    assert job.exists()
    assert job.config.get("tasks"), "job must declare at least one task"
"""
    else:
        body = f"""    resource = env.resource({json.dumps(kind)}, {json.dumps(name)})
    assert resource.exists()
"""
    return f'''"""Starter assertions generated by ``bundletest init``."""

import pytest


@pytest.mark.bundle_resource({json.dumps(marker)})
def test_{function_name}_is_declared(env):
{body}'''
