# Code generated by pydabs-codegen. DO NOT EDIT.

from dataclasses import dataclass
from typing import TYPE_CHECKING, TypedDict

from databricks.bundles.core._transform import _transform
from databricks.bundles.core._transform_to_json import _transform_to_json_value
from databricks.bundles.core._variable import VariableOrOptional

if TYPE_CHECKING:
    from typing_extensions import Self


@dataclass(kw_only=True)
class NewPipelineSpec:
    """
    Custom fields that user can set for pipeline while creating SyncedDatabaseTable.
    Note that other fields of pipeline are still inferred by table def internally
    """

    budget_policy_id: VariableOrOptional[str] = None
    """
    :meta private: [EXPERIMENTAL]
    
    [Beta] Budget policy to set on the newly created pipeline.
    """

    storage_catalog: VariableOrOptional[str] = None
    """
    [Public Preview] This field needs to be specified if the destination catalog is a managed postgres catalog.
    
    UC catalog for the pipeline to store intermediate files (checkpoints, event logs etc).
    This needs to be a standard catalog where the user has permissions to create Delta tables.
    """

    storage_schema: VariableOrOptional[str] = None
    """
    [Public Preview] This field needs to be specified if the destination catalog is a managed postgres catalog.
    
    UC schema for the pipeline to store intermediate files (checkpoints, event logs etc).
    This needs to be in the standard catalog where the user has permissions to create Delta tables.
    """

    @classmethod
    def from_dict(cls, value: "NewPipelineSpecDict") -> "Self":
        return _transform(cls, value)

    def as_dict(self) -> "NewPipelineSpecDict":
        return _transform_to_json_value(self)  # type:ignore


class NewPipelineSpecDict(TypedDict, total=False):
    """"""

    budget_policy_id: VariableOrOptional[str]
    """
    :meta private: [EXPERIMENTAL]
    
    [Beta] Budget policy to set on the newly created pipeline.
    """

    storage_catalog: VariableOrOptional[str]
    """
    [Public Preview] This field needs to be specified if the destination catalog is a managed postgres catalog.
    
    UC catalog for the pipeline to store intermediate files (checkpoints, event logs etc).
    This needs to be a standard catalog where the user has permissions to create Delta tables.
    """

    storage_schema: VariableOrOptional[str]
    """
    [Public Preview] This field needs to be specified if the destination catalog is a managed postgres catalog.
    
    UC schema for the pipeline to store intermediate files (checkpoints, event logs etc).
    This needs to be in the standard catalog where the user has permissions to create Delta tables.
    """


NewPipelineSpecParam = NewPipelineSpecDict | NewPipelineSpec
