# Code generated by pydabs-codegen. DO NOT EDIT.

from enum import Enum
from typing import Literal


class SyncedTableSpecPgSpecificType(Enum):
    """
    :meta private: [EXPERIMENTAL]

    PostgreSQL-specific target types that can override the default Delta-to-PG mapping.
    """

    PG_SPECIFIC_TYPE_VECTOR = "PG_SPECIFIC_TYPE_VECTOR"
    PG_SPECIFIC_TYPE_HALFVEC = "PG_SPECIFIC_TYPE_HALFVEC"
    PG_SPECIFIC_TYPE_VARCHAR = "PG_SPECIFIC_TYPE_VARCHAR"


SyncedTableSpecPgSpecificTypeParam = (
    Literal[
        "PG_SPECIFIC_TYPE_VECTOR",
        "PG_SPECIFIC_TYPE_HALFVEC",
        "PG_SPECIFIC_TYPE_VARCHAR",
    ]
    | SyncedTableSpecPgSpecificType
)
