# Code generated by pydabs-codegen. DO NOT EDIT.

from enum import Enum
from typing import Literal


class SyncedTableSchedulingPolicy(Enum):
    CONTINUOUS = "CONTINUOUS"
    TRIGGERED = "TRIGGERED"
    SNAPSHOT = "SNAPSHOT"


SyncedTableSchedulingPolicyParam = (
    Literal["CONTINUOUS", "TRIGGERED", "SNAPSHOT"] | SyncedTableSchedulingPolicy
)
