# Code generated by pydabs-codegen. DO NOT EDIT.

from dataclasses import dataclass, field
from typing import TYPE_CHECKING, TypedDict

from databricks.bundles.core._transform import _transform
from databricks.bundles.core._transform_to_json import _transform_to_json_value
from databricks.bundles.core._variable import VariableOrList, VariableOrOptional
from databricks.bundles.synced_database_tables._models.new_pipeline_spec import (
    NewPipelineSpec,
    NewPipelineSpecParam,
)
from databricks.bundles.synced_database_tables._models.synced_table_scheduling_policy import (
    SyncedTableSchedulingPolicy,
    SyncedTableSchedulingPolicyParam,
)
from databricks.bundles.synced_database_tables._models.synced_table_spec_type_override import (
    SyncedTableSpecTypeOverride,
    SyncedTableSpecTypeOverrideParam,
)

if TYPE_CHECKING:
    from typing_extensions import Self


@dataclass(kw_only=True)
class SyncedTableSpec:
    """
    Specification of a synced database table.
    """

    accelerated_sync: VariableOrOptional[bool] = None
    """
    :meta private: [EXPERIMENTAL]
    
    [Private Preview] When true, enables accelerated sync mode for the initial data load.
    This significantly improves performance for large tables.
    Requires workspace-level enablement.
    """

    create_database_objects_if_missing: VariableOrOptional[bool] = None
    """
    [Public Preview] If true, the synced table's logical database and schema resources in PG
    will be created if they do not already exist.
    """

    existing_pipeline_id: VariableOrOptional[str] = None
    """
    [Public Preview] At most one of existing_pipeline_id and new_pipeline_spec should be defined.
    
    If existing_pipeline_id is defined, the synced table will be bin packed into the existing pipeline
    referenced. This avoids creating a new pipeline and allows sharing existing compute.
    In this case, the scheduling_policy of this synced table must match the scheduling policy of the existing pipeline.
    """

    new_pipeline_spec: VariableOrOptional[NewPipelineSpec] = None
    """
    [Public Preview] At most one of existing_pipeline_id and new_pipeline_spec should be defined.
    
    If new_pipeline_spec is defined, a new pipeline is created for this synced table. The location pointed to is used
    to store intermediate files (checkpoints, event logs etc). The caller must have write permissions to create Delta
    tables in the specified catalog and schema. Again, note this requires write permissions, whereas the source table
    only requires read permissions.
    """

    primary_key_columns: VariableOrList[str] = field(default_factory=list)
    """
    [Public Preview] Primary Key columns to be used for data insert/update in the destination.
    """

    scheduling_policy: VariableOrOptional[SyncedTableSchedulingPolicy] = None
    """
    [Public Preview] Scheduling policy of the underlying pipeline.
    """

    source_table_full_name: VariableOrOptional[str] = None
    """
    [Public Preview] Three-part (catalog, schema, table) name of the source Delta table.
    """

    timeseries_key: VariableOrOptional[str] = None
    """
    [Public Preview] Time series key to deduplicate (tie-break) rows with the same primary key.
    """

    type_overrides: VariableOrList[SyncedTableSpecTypeOverride] = field(
        default_factory=list
    )
    """
    :meta private: [EXPERIMENTAL]
    
    [Private Preview] Override the default Delta->PG type mapping for specific columns.
    A TypeOverride with PG_SPECIFIC_TYPE_UNSPECIFIED is rejected; a valid pg_type must be set.
    """

    @classmethod
    def from_dict(cls, value: "SyncedTableSpecDict") -> "Self":
        return _transform(cls, value)

    def as_dict(self) -> "SyncedTableSpecDict":
        return _transform_to_json_value(self)  # type:ignore


class SyncedTableSpecDict(TypedDict, total=False):
    """"""

    accelerated_sync: VariableOrOptional[bool]
    """
    :meta private: [EXPERIMENTAL]
    
    [Private Preview] When true, enables accelerated sync mode for the initial data load.
    This significantly improves performance for large tables.
    Requires workspace-level enablement.
    """

    create_database_objects_if_missing: VariableOrOptional[bool]
    """
    [Public Preview] If true, the synced table's logical database and schema resources in PG
    will be created if they do not already exist.
    """

    existing_pipeline_id: VariableOrOptional[str]
    """
    [Public Preview] At most one of existing_pipeline_id and new_pipeline_spec should be defined.
    
    If existing_pipeline_id is defined, the synced table will be bin packed into the existing pipeline
    referenced. This avoids creating a new pipeline and allows sharing existing compute.
    In this case, the scheduling_policy of this synced table must match the scheduling policy of the existing pipeline.
    """

    new_pipeline_spec: VariableOrOptional[NewPipelineSpecParam]
    """
    [Public Preview] At most one of existing_pipeline_id and new_pipeline_spec should be defined.
    
    If new_pipeline_spec is defined, a new pipeline is created for this synced table. The location pointed to is used
    to store intermediate files (checkpoints, event logs etc). The caller must have write permissions to create Delta
    tables in the specified catalog and schema. Again, note this requires write permissions, whereas the source table
    only requires read permissions.
    """

    primary_key_columns: VariableOrList[str]
    """
    [Public Preview] Primary Key columns to be used for data insert/update in the destination.
    """

    scheduling_policy: VariableOrOptional[SyncedTableSchedulingPolicyParam]
    """
    [Public Preview] Scheduling policy of the underlying pipeline.
    """

    source_table_full_name: VariableOrOptional[str]
    """
    [Public Preview] Three-part (catalog, schema, table) name of the source Delta table.
    """

    timeseries_key: VariableOrOptional[str]
    """
    [Public Preview] Time series key to deduplicate (tie-break) rows with the same primary key.
    """

    type_overrides: VariableOrList[SyncedTableSpecTypeOverrideParam]
    """
    :meta private: [EXPERIMENTAL]
    
    [Private Preview] Override the default Delta->PG type mapping for specific columns.
    A TypeOverride with PG_SPECIFIC_TYPE_UNSPECIFIED is rejected; a valid pg_type must be set.
    """


SyncedTableSpecParam = SyncedTableSpecDict | SyncedTableSpec
