#This file is autogenerated by the Databricks Extension for VS Code
import runpy
import sys
import os

python_file = {{.PythonFile}}
project_root = {{.ProjectRoot}}
#remove databricks args from argv
sys.argv = sys.argv[1:]

# change working directory
os.chdir(os.path.dirname(python_file))

# update python path
sys.path.insert(0, project_root)

# provide spark globals
user_ns = {
    "display": display,
    "displayHTML": displayHTML,
    "dbutils": dbutils,
    "table": table,
    "sql": sql,
    "udf": udf,
    "getArgument": getArgument,
    "sc": sc,
    "spark": spark,
    "sqlContext": sqlContext,
}

# Set log level to "ERROR". See https://kb.databricks.com/notebooks/cmd-c-on-object-id-p0.html
import logging; logger = spark._jvm.org.apache.log4j;
logging.getLogger("py4j.java_gateway").setLevel(logging.ERROR)

runpy.run_path(python_file, run_name="__main__", init_globals=user_ns)
None
