name: renovate

on:
  schedule:
    - cron: "0 0 * * 1" # Weekly on Monday at 00:00 UTC
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - uses: renovatebot/github-action@0b17c4eb901eca44d018fb25744a50a74b2042df # v46.1.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
