// Code generated by bundle/terraform_dabs_map/generate_test.go; DO NOT EDIT.

package terraform_dabs_map

// alerts / databricks_alert_v2: 1 dabs-only
// alerts / databricks_alert_v2: 3 tf-only
// apps / databricks_app: 16 dabs-only
// apps / databricks_app: 1 tf-only
// clusters / databricks_cluster: 25 tf-only
// dashboards / databricks_dashboard: 2 tf-only
// database_instances / databricks_database_instance: 1 tf-only
// experiments / databricks_mlflow_experiment: 1 tf-only
// jobs / databricks_job: 11 renames
// jobs / databricks_job: 33 dabs-only
// jobs / databricks_job: 257 tf-only
// model_serving_endpoints / databricks_model_serving: 2 tf-only
// models / databricks_mlflow_model: 1 tf-only
// pipelines / databricks_pipeline: 3 renames
// pipelines / databricks_pipeline: 49 dabs-only
// pipelines / databricks_pipeline: 2 tf-only
// postgres_branches / databricks_postgres_branch: 1 unwraps
// postgres_catalogs / databricks_postgres_catalog: 1 unwraps
// postgres_endpoints / databricks_postgres_endpoint: 1 unwraps
// postgres_projects / databricks_postgres_project: 1 tf-only
// postgres_projects / databricks_postgres_project: 1 unwraps
// postgres_synced_tables / databricks_postgres_synced_table: 1 unwraps
// schemas / databricks_schema: 1 tf-only
// secret_scopes / databricks_secret_scope: 1 tf-only
// sql_warehouses / databricks_sql_endpoint: 2 tf-only
// volumes / databricks_volume: 1 tf-only

// TerraformToDABsFieldMap maps DABs group name → nested TF segments → DABs segment name.
// Navigate using TF field name segments; DABs is the corresponding DABs name when it differs.
var TerraformToDABsFieldMap = map[string]RenameTree{
	"jobs": {
		"environment": {NewName: "environments"},
		"git_source": {Children: RenameTree{
			"branch":   {NewName: "git_branch"},
			"commit":   {NewName: "git_commit"},
			"provider": {NewName: "git_provider"},
			"tag":      {NewName: "git_tag"},
			"url":      {NewName: "git_url"},
		}},
		"job_cluster": {NewName: "job_clusters"},
		"parameter":   {NewName: "parameters"},
		"task": {NewName: "tasks", Children: RenameTree{
			"for_each_task": {Children: RenameTree{
				"task": {Children: RenameTree{
					"library": {NewName: "libraries"},
				}},
			}},
			"library": {NewName: "libraries"},
		}},
	},
	"pipelines": {
		"cluster":      {NewName: "clusters"},
		"library":      {NewName: "libraries"},
		"notification": {NewName: "notifications"},
	},
	"postgres_branches": {
		"spec": {Unwrap: true},
	},
	"postgres_catalogs": {
		"spec": {Unwrap: true},
	},
	"postgres_endpoints": {
		"spec": {Unwrap: true},
	},
	"postgres_projects": {
		"spec": {Unwrap: true},
	},
	"postgres_synced_tables": {
		"spec": {Unwrap: true},
	},
}

// DABsOnlyFields maps DABs group name → FieldSet of DABs fields with no TF equivalent.
var DABsOnlyFields = map[string]FieldSet{
	"alerts": {
		"file_path": {},
	},
	"apps": {
		"config": {
			"command": {}, // apps.*.config.command
			"env": {
				"name":       {}, // apps.*.config.env.name
				"value":      {}, // apps.*.config.env.value
				"value_from": {}, // apps.*.config.env.value_from
			},
		},
		"git_source": {
			"branch": {}, // apps.*.git_source.branch
			"commit": {}, // apps.*.git_source.commit
			"git_repository": {
				"provider": {}, // apps.*.git_source.git_repository.provider
				"url":      {}, // apps.*.git_source.git_repository.url
			},
			"resolved_commit":  {}, // apps.*.git_source.resolved_commit
			"source_code_path": {}, // apps.*.git_source.source_code_path
			"tag":              {}, // apps.*.git_source.tag
		},
		"source_code_path": {},
	},
	"jobs": {
		"job_clusters": {
			"new_cluster": {
				"autotermination_minutes": {}, // jobs.*.job_clusters.new_cluster.autotermination_minutes
			},
		},
		"tasks": {
			"for_each_task": {
				"task": {
					"for_each_task": {
						"concurrency": {}, // jobs.*.tasks.for_each_task.task.for_each_task.concurrency
						"inputs":      {}, // jobs.*.tasks.for_each_task.task.for_each_task.inputs
						"task":        {}, // jobs.*.tasks.for_each_task.task.for_each_task.task
					},
					"new_cluster": {
						"autotermination_minutes": {}, // jobs.*.tasks.for_each_task.task.new_cluster.autotermination_minutes
					},
					"pipeline_task": {
						"full_refresh_selection":     {}, // jobs.*.tasks.for_each_task.task.pipeline_task.full_refresh_selection
						"refresh_flow_selection":     {}, // jobs.*.tasks.for_each_task.task.pipeline_task.refresh_flow_selection
						"refresh_selection":          {}, // jobs.*.tasks.for_each_task.task.pipeline_task.refresh_selection
						"reset_checkpoint_selection": {}, // jobs.*.tasks.for_each_task.task.pipeline_task.reset_checkpoint_selection
					},
					"python_operator_task": {
						"main": {}, // jobs.*.tasks.for_each_task.task.python_operator_task.main
						"parameters": {
							"name":  {}, // jobs.*.tasks.for_each_task.task.python_operator_task.parameters.name
							"value": {}, // jobs.*.tasks.for_each_task.task.python_operator_task.parameters.value
						},
					},
					"run_job_task": {
						"pipeline_params": {
							"full_refresh_selection":     {}, // jobs.*.tasks.for_each_task.task.run_job_task.pipeline_params.full_refresh_selection
							"refresh_flow_selection":     {}, // jobs.*.tasks.for_each_task.task.run_job_task.pipeline_params.refresh_flow_selection
							"refresh_selection":          {}, // jobs.*.tasks.for_each_task.task.run_job_task.pipeline_params.refresh_selection
							"reset_checkpoint_selection": {}, // jobs.*.tasks.for_each_task.task.run_job_task.pipeline_params.reset_checkpoint_selection
						},
					},
				},
			},
			"new_cluster": {
				"autotermination_minutes": {}, // jobs.*.tasks.new_cluster.autotermination_minutes
			},
			"pipeline_task": {
				"full_refresh_selection":     {}, // jobs.*.tasks.pipeline_task.full_refresh_selection
				"refresh_flow_selection":     {}, // jobs.*.tasks.pipeline_task.refresh_flow_selection
				"refresh_selection":          {}, // jobs.*.tasks.pipeline_task.refresh_selection
				"reset_checkpoint_selection": {}, // jobs.*.tasks.pipeline_task.reset_checkpoint_selection
			},
			"python_operator_task": {
				"main": {}, // jobs.*.tasks.python_operator_task.main
				"parameters": {
					"name":  {}, // jobs.*.tasks.python_operator_task.parameters.name
					"value": {}, // jobs.*.tasks.python_operator_task.parameters.value
				},
			},
			"run_job_task": {
				"pipeline_params": {
					"full_refresh_selection":     {}, // jobs.*.tasks.run_job_task.pipeline_params.full_refresh_selection
					"refresh_flow_selection":     {}, // jobs.*.tasks.run_job_task.pipeline_params.refresh_flow_selection
					"refresh_selection":          {}, // jobs.*.tasks.run_job_task.pipeline_params.refresh_selection
					"reset_checkpoint_selection": {}, // jobs.*.tasks.run_job_task.pipeline_params.reset_checkpoint_selection
				},
			},
		},
	},
	"pipelines": {
		"clusters": {
			"gcp_attributes": {
				"boot_disk_size":            {}, // pipelines.*.clusters.gcp_attributes.boot_disk_size
				"use_preemptible_executors": {}, // pipelines.*.clusters.gcp_attributes.use_preemptible_executors
			},
		},
		"dry_run": {},
		"ingestion_definition": {
			"objects": {
				"schema": {
					"connector_options": {
						"kafka_options": {
							"client_config": {
								"*": {}, // pipelines.*.ingestion_definition.objects.schema.connector_options.kafka_options.client_config.*
							},
							"key_transformer": {
								"format": {}, // pipelines.*.ingestion_definition.objects.schema.connector_options.kafka_options.key_transformer.format
								"json_options": {
									"as_variant":            {}, // pipelines.*.ingestion_definition.objects.schema.connector_options.kafka_options.key_transformer.json_options.as_variant
									"schema":                {}, // pipelines.*.ingestion_definition.objects.schema.connector_options.kafka_options.key_transformer.json_options.schema
									"schema_evolution_mode": {}, // pipelines.*.ingestion_definition.objects.schema.connector_options.kafka_options.key_transformer.json_options.schema_evolution_mode
									"schema_file_path":      {}, // pipelines.*.ingestion_definition.objects.schema.connector_options.kafka_options.key_transformer.json_options.schema_file_path
									"schema_hints":          {}, // pipelines.*.ingestion_definition.objects.schema.connector_options.kafka_options.key_transformer.json_options.schema_hints
								},
							},
							"max_offsets_per_trigger": {}, // pipelines.*.ingestion_definition.objects.schema.connector_options.kafka_options.max_offsets_per_trigger
							"starting_offset":         {}, // pipelines.*.ingestion_definition.objects.schema.connector_options.kafka_options.starting_offset
							"topic_pattern":           {}, // pipelines.*.ingestion_definition.objects.schema.connector_options.kafka_options.topic_pattern
							"topics":                  {}, // pipelines.*.ingestion_definition.objects.schema.connector_options.kafka_options.topics
							"value_transformer": {
								"format": {}, // pipelines.*.ingestion_definition.objects.schema.connector_options.kafka_options.value_transformer.format
								"json_options": {
									"as_variant":            {}, // pipelines.*.ingestion_definition.objects.schema.connector_options.kafka_options.value_transformer.json_options.as_variant
									"schema":                {}, // pipelines.*.ingestion_definition.objects.schema.connector_options.kafka_options.value_transformer.json_options.schema
									"schema_evolution_mode": {}, // pipelines.*.ingestion_definition.objects.schema.connector_options.kafka_options.value_transformer.json_options.schema_evolution_mode
									"schema_file_path":      {}, // pipelines.*.ingestion_definition.objects.schema.connector_options.kafka_options.value_transformer.json_options.schema_file_path
									"schema_hints":          {}, // pipelines.*.ingestion_definition.objects.schema.connector_options.kafka_options.value_transformer.json_options.schema_hints
								},
							},
						},
					},
				},
				"table": {
					"connector_options": {
						"kafka_options": {
							"client_config": {
								"*": {}, // pipelines.*.ingestion_definition.objects.table.connector_options.kafka_options.client_config.*
							},
							"key_transformer": {
								"format": {}, // pipelines.*.ingestion_definition.objects.table.connector_options.kafka_options.key_transformer.format
								"json_options": {
									"as_variant":            {}, // pipelines.*.ingestion_definition.objects.table.connector_options.kafka_options.key_transformer.json_options.as_variant
									"schema":                {}, // pipelines.*.ingestion_definition.objects.table.connector_options.kafka_options.key_transformer.json_options.schema
									"schema_evolution_mode": {}, // pipelines.*.ingestion_definition.objects.table.connector_options.kafka_options.key_transformer.json_options.schema_evolution_mode
									"schema_file_path":      {}, // pipelines.*.ingestion_definition.objects.table.connector_options.kafka_options.key_transformer.json_options.schema_file_path
									"schema_hints":          {}, // pipelines.*.ingestion_definition.objects.table.connector_options.kafka_options.key_transformer.json_options.schema_hints
								},
							},
							"max_offsets_per_trigger": {}, // pipelines.*.ingestion_definition.objects.table.connector_options.kafka_options.max_offsets_per_trigger
							"starting_offset":         {}, // pipelines.*.ingestion_definition.objects.table.connector_options.kafka_options.starting_offset
							"topic_pattern":           {}, // pipelines.*.ingestion_definition.objects.table.connector_options.kafka_options.topic_pattern
							"topics":                  {}, // pipelines.*.ingestion_definition.objects.table.connector_options.kafka_options.topics
							"value_transformer": {
								"format": {}, // pipelines.*.ingestion_definition.objects.table.connector_options.kafka_options.value_transformer.format
								"json_options": {
									"as_variant":            {}, // pipelines.*.ingestion_definition.objects.table.connector_options.kafka_options.value_transformer.json_options.as_variant
									"schema":                {}, // pipelines.*.ingestion_definition.objects.table.connector_options.kafka_options.value_transformer.json_options.schema
									"schema_evolution_mode": {}, // pipelines.*.ingestion_definition.objects.table.connector_options.kafka_options.value_transformer.json_options.schema_evolution_mode
									"schema_file_path":      {}, // pipelines.*.ingestion_definition.objects.table.connector_options.kafka_options.value_transformer.json_options.schema_file_path
									"schema_hints":          {}, // pipelines.*.ingestion_definition.objects.table.connector_options.kafka_options.value_transformer.json_options.schema_hints
								},
							},
						},
					},
				},
			},
		},
	},
}

// TerraformOnlyFields maps DABs group name → FieldSet of TF fields with no DABs equivalent.
var TerraformOnlyFields = map[string]FieldSet{
	"alerts": {
		"evaluation": {
			"notification": {
				"effective_notify_on_ok":      {}, // alerts.*.evaluation.notification.effective_notify_on_ok
				"effective_retrigger_seconds": {}, // alerts.*.evaluation.notification.effective_retrigger_seconds
			},
		},
		"purge_on_delete": {},
	},
	"apps": {
		"no_compute": {},
	},
	"clusters": {
		"cluster_mount_info": {
			"local_mount_dir_path": {}, // clusters.*.cluster_mount_info.local_mount_dir_path
			"network_filesystem_info": {
				"mount_options":  {}, // clusters.*.cluster_mount_info.network_filesystem_info.mount_options
				"server_address": {}, // clusters.*.cluster_mount_info.network_filesystem_info.server_address
			},
			"remote_mount_dir_path": {}, // clusters.*.cluster_mount_info.remote_mount_dir_path
		},
		"idempotency_token": {},
		"is_pinned":         {},
		"library": {
			"cran": {
				"package": {}, // clusters.*.library.cran.package
				"repo":    {}, // clusters.*.library.cran.repo
			},
			"egg": {}, // clusters.*.library.egg
			"jar": {}, // clusters.*.library.jar
			"maven": {
				"coordinates": {}, // clusters.*.library.maven.coordinates
				"exclusions":  {}, // clusters.*.library.maven.exclusions
				"repo":        {}, // clusters.*.library.maven.repo
			},
			"pypi": {
				"package": {}, // clusters.*.library.pypi.package
				"repo":    {}, // clusters.*.library.pypi.repo
			},
			"requirements": {}, // clusters.*.library.requirements
			"whl":          {}, // clusters.*.library.whl
		},
		"no_wait": {},
		"url":     {},
	},
	"dashboards": {
		"dashboard_change_detected": {},
		"md5":                       {},
	},
	"database_instances": {
		"purge_on_delete": {},
	},
	"experiments": {
		"description": {},
	},
	"jobs": {
		"always_running":    {},
		"control_run_state": {},
		"dbt_task": {
			"catalog":            {}, // jobs.*.dbt_task.catalog
			"commands":           {}, // jobs.*.dbt_task.commands
			"profiles_directory": {}, // jobs.*.dbt_task.profiles_directory
			"project_directory":  {}, // jobs.*.dbt_task.project_directory
			"schema":             {}, // jobs.*.dbt_task.schema
			"source":             {}, // jobs.*.dbt_task.source
			"warehouse_id":       {}, // jobs.*.dbt_task.warehouse_id
		},
		"existing_cluster_id": {},
		"job_cluster": {
			"new_cluster": {
				"__apply_policy_default_values_allow_list": {}, // jobs.*.job_cluster.new_cluster.__apply_policy_default_values_allow_list
				"cluster_id": {}, // jobs.*.job_cluster.new_cluster.cluster_id
				"cluster_mount_info": {
					"local_mount_dir_path": {}, // jobs.*.job_cluster.new_cluster.cluster_mount_info.local_mount_dir_path
					"network_filesystem_info": {
						"mount_options":  {}, // jobs.*.job_cluster.new_cluster.cluster_mount_info.network_filesystem_info.mount_options
						"server_address": {}, // jobs.*.job_cluster.new_cluster.cluster_mount_info.network_filesystem_info.server_address
					},
					"remote_mount_dir_path": {}, // jobs.*.job_cluster.new_cluster.cluster_mount_info.remote_mount_dir_path
				},
				"idempotency_token": {}, // jobs.*.job_cluster.new_cluster.idempotency_token
				"library": {
					"cran": {
						"package": {}, // jobs.*.job_cluster.new_cluster.library.cran.package
						"repo":    {}, // jobs.*.job_cluster.new_cluster.library.cran.repo
					},
					"egg": {}, // jobs.*.job_cluster.new_cluster.library.egg
					"jar": {}, // jobs.*.job_cluster.new_cluster.library.jar
					"maven": {
						"coordinates": {}, // jobs.*.job_cluster.new_cluster.library.maven.coordinates
						"exclusions":  {}, // jobs.*.job_cluster.new_cluster.library.maven.exclusions
						"repo":        {}, // jobs.*.job_cluster.new_cluster.library.maven.repo
					},
					"pypi": {
						"package": {}, // jobs.*.job_cluster.new_cluster.library.pypi.package
						"repo":    {}, // jobs.*.job_cluster.new_cluster.library.pypi.repo
					},
					"requirements": {}, // jobs.*.job_cluster.new_cluster.library.requirements
					"whl":          {}, // jobs.*.job_cluster.new_cluster.library.whl
				},
			},
		},
		"library": {
			"cran": {
				"package": {}, // jobs.*.library.cran.package
				"repo":    {}, // jobs.*.library.cran.repo
			},
			"egg": {}, // jobs.*.library.egg
			"jar": {}, // jobs.*.library.jar
			"maven": {
				"coordinates": {}, // jobs.*.library.maven.coordinates
				"exclusions":  {}, // jobs.*.library.maven.exclusions
				"repo":        {}, // jobs.*.library.maven.repo
			},
			"pypi": {
				"package": {}, // jobs.*.library.pypi.package
				"repo":    {}, // jobs.*.library.pypi.repo
			},
			"requirements": {}, // jobs.*.library.requirements
			"whl":          {}, // jobs.*.library.whl
		},
		"max_retries":               {},
		"min_retry_interval_millis": {},
		"new_cluster": {
			"apply_policy_default_values": {}, // jobs.*.new_cluster.apply_policy_default_values
			"autoscale": {
				"max_workers": {}, // jobs.*.new_cluster.autoscale.max_workers
				"min_workers": {}, // jobs.*.new_cluster.autoscale.min_workers
			},
			"aws_attributes": {
				"availability":           {}, // jobs.*.new_cluster.aws_attributes.availability
				"ebs_volume_count":       {}, // jobs.*.new_cluster.aws_attributes.ebs_volume_count
				"ebs_volume_iops":        {}, // jobs.*.new_cluster.aws_attributes.ebs_volume_iops
				"ebs_volume_size":        {}, // jobs.*.new_cluster.aws_attributes.ebs_volume_size
				"ebs_volume_throughput":  {}, // jobs.*.new_cluster.aws_attributes.ebs_volume_throughput
				"ebs_volume_type":        {}, // jobs.*.new_cluster.aws_attributes.ebs_volume_type
				"first_on_demand":        {}, // jobs.*.new_cluster.aws_attributes.first_on_demand
				"instance_profile_arn":   {}, // jobs.*.new_cluster.aws_attributes.instance_profile_arn
				"spot_bid_price_percent": {}, // jobs.*.new_cluster.aws_attributes.spot_bid_price_percent
				"zone_id":                {}, // jobs.*.new_cluster.aws_attributes.zone_id
			},
			"azure_attributes": {
				"availability":    {}, // jobs.*.new_cluster.azure_attributes.availability
				"first_on_demand": {}, // jobs.*.new_cluster.azure_attributes.first_on_demand
				"log_analytics_info": {
					"log_analytics_primary_key":  {}, // jobs.*.new_cluster.azure_attributes.log_analytics_info.log_analytics_primary_key
					"log_analytics_workspace_id": {}, // jobs.*.new_cluster.azure_attributes.log_analytics_info.log_analytics_workspace_id
				},
				"spot_bid_max_price": {}, // jobs.*.new_cluster.azure_attributes.spot_bid_max_price
			},
			"cluster_id": {}, // jobs.*.new_cluster.cluster_id
			"cluster_log_conf": {
				"dbfs": {
					"destination": {}, // jobs.*.new_cluster.cluster_log_conf.dbfs.destination
				},
				"s3": {
					"canned_acl":        {}, // jobs.*.new_cluster.cluster_log_conf.s3.canned_acl
					"destination":       {}, // jobs.*.new_cluster.cluster_log_conf.s3.destination
					"enable_encryption": {}, // jobs.*.new_cluster.cluster_log_conf.s3.enable_encryption
					"encryption_type":   {}, // jobs.*.new_cluster.cluster_log_conf.s3.encryption_type
					"endpoint":          {}, // jobs.*.new_cluster.cluster_log_conf.s3.endpoint
					"kms_key":           {}, // jobs.*.new_cluster.cluster_log_conf.s3.kms_key
					"region":            {}, // jobs.*.new_cluster.cluster_log_conf.s3.region
				},
				"volumes": {
					"destination": {}, // jobs.*.new_cluster.cluster_log_conf.volumes.destination
				},
			},
			"cluster_mount_info": {
				"local_mount_dir_path": {}, // jobs.*.new_cluster.cluster_mount_info.local_mount_dir_path
				"network_filesystem_info": {
					"mount_options":  {}, // jobs.*.new_cluster.cluster_mount_info.network_filesystem_info.mount_options
					"server_address": {}, // jobs.*.new_cluster.cluster_mount_info.network_filesystem_info.server_address
				},
				"remote_mount_dir_path": {}, // jobs.*.new_cluster.cluster_mount_info.remote_mount_dir_path
			},
			"cluster_name": {}, // jobs.*.new_cluster.cluster_name
			"custom_tags": {
				"*": {}, // jobs.*.new_cluster.custom_tags.*
			},
			"data_security_mode": {}, // jobs.*.new_cluster.data_security_mode
			"docker_image": {
				"basic_auth": {
					"password": {}, // jobs.*.new_cluster.docker_image.basic_auth.password
					"username": {}, // jobs.*.new_cluster.docker_image.basic_auth.username
				},
				"url": {}, // jobs.*.new_cluster.docker_image.url
			},
			"driver_instance_pool_id": {}, // jobs.*.new_cluster.driver_instance_pool_id
			"driver_node_type_flexibility": {
				"alternate_node_type_ids": {}, // jobs.*.new_cluster.driver_node_type_flexibility.alternate_node_type_ids
			},
			"driver_node_type_id":          {}, // jobs.*.new_cluster.driver_node_type_id
			"enable_elastic_disk":          {}, // jobs.*.new_cluster.enable_elastic_disk
			"enable_local_disk_encryption": {}, // jobs.*.new_cluster.enable_local_disk_encryption
			"gcp_attributes": {
				"availability":              {}, // jobs.*.new_cluster.gcp_attributes.availability
				"boot_disk_size":            {}, // jobs.*.new_cluster.gcp_attributes.boot_disk_size
				"confidential_compute_type": {}, // jobs.*.new_cluster.gcp_attributes.confidential_compute_type
				"first_on_demand":           {}, // jobs.*.new_cluster.gcp_attributes.first_on_demand
				"google_service_account":    {}, // jobs.*.new_cluster.gcp_attributes.google_service_account
				"local_ssd_count":           {}, // jobs.*.new_cluster.gcp_attributes.local_ssd_count
				"use_preemptible_executors": {}, // jobs.*.new_cluster.gcp_attributes.use_preemptible_executors
				"zone_id":                   {}, // jobs.*.new_cluster.gcp_attributes.zone_id
			},
			"idempotency_token": {}, // jobs.*.new_cluster.idempotency_token
			"init_scripts": {
				"abfss": {
					"destination": {}, // jobs.*.new_cluster.init_scripts.abfss.destination
				},
				"dbfs": {
					"destination": {}, // jobs.*.new_cluster.init_scripts.dbfs.destination
				},
				"file": {
					"destination": {}, // jobs.*.new_cluster.init_scripts.file.destination
				},
				"gcs": {
					"destination": {}, // jobs.*.new_cluster.init_scripts.gcs.destination
				},
				"s3": {
					"canned_acl":        {}, // jobs.*.new_cluster.init_scripts.s3.canned_acl
					"destination":       {}, // jobs.*.new_cluster.init_scripts.s3.destination
					"enable_encryption": {}, // jobs.*.new_cluster.init_scripts.s3.enable_encryption
					"encryption_type":   {}, // jobs.*.new_cluster.init_scripts.s3.encryption_type
					"endpoint":          {}, // jobs.*.new_cluster.init_scripts.s3.endpoint
					"kms_key":           {}, // jobs.*.new_cluster.init_scripts.s3.kms_key
					"region":            {}, // jobs.*.new_cluster.init_scripts.s3.region
				},
				"volumes": {
					"destination": {}, // jobs.*.new_cluster.init_scripts.volumes.destination
				},
				"workspace": {
					"destination": {}, // jobs.*.new_cluster.init_scripts.workspace.destination
				},
			},
			"instance_pool_id": {}, // jobs.*.new_cluster.instance_pool_id
			"is_single_node":   {}, // jobs.*.new_cluster.is_single_node
			"kind":             {}, // jobs.*.new_cluster.kind
			"library": {
				"cran": {
					"package": {}, // jobs.*.new_cluster.library.cran.package
					"repo":    {}, // jobs.*.new_cluster.library.cran.repo
				},
				"egg": {}, // jobs.*.new_cluster.library.egg
				"jar": {}, // jobs.*.new_cluster.library.jar
				"maven": {
					"coordinates": {}, // jobs.*.new_cluster.library.maven.coordinates
					"exclusions":  {}, // jobs.*.new_cluster.library.maven.exclusions
					"repo":        {}, // jobs.*.new_cluster.library.maven.repo
				},
				"pypi": {
					"package": {}, // jobs.*.new_cluster.library.pypi.package
					"repo":    {}, // jobs.*.new_cluster.library.pypi.repo
				},
				"requirements": {}, // jobs.*.new_cluster.library.requirements
				"whl":          {}, // jobs.*.new_cluster.library.whl
			},
			"node_type_id":           {}, // jobs.*.new_cluster.node_type_id
			"num_workers":            {}, // jobs.*.new_cluster.num_workers
			"policy_id":              {}, // jobs.*.new_cluster.policy_id
			"remote_disk_throughput": {}, // jobs.*.new_cluster.remote_disk_throughput
			"runtime_engine":         {}, // jobs.*.new_cluster.runtime_engine
			"single_user_name":       {}, // jobs.*.new_cluster.single_user_name
			"spark_conf": {
				"*": {}, // jobs.*.new_cluster.spark_conf.*
			},
			"spark_env_vars": {
				"*": {}, // jobs.*.new_cluster.spark_env_vars.*
			},
			"spark_version":                  {}, // jobs.*.new_cluster.spark_version
			"ssh_public_keys":                {}, // jobs.*.new_cluster.ssh_public_keys
			"total_initial_remote_disk_size": {}, // jobs.*.new_cluster.total_initial_remote_disk_size
			"use_ml_runtime":                 {}, // jobs.*.new_cluster.use_ml_runtime
			"worker_node_type_flexibility": {
				"alternate_node_type_ids": {}, // jobs.*.new_cluster.worker_node_type_flexibility.alternate_node_type_ids
			},
			"workload_type": {
				"clients": {
					"jobs":      {}, // jobs.*.new_cluster.workload_type.clients.jobs
					"notebooks": {}, // jobs.*.new_cluster.workload_type.clients.notebooks
				},
			},
		},
		"notebook_task": {
			"base_parameters": {
				"*": {}, // jobs.*.notebook_task.base_parameters.*
			},
			"notebook_path": {}, // jobs.*.notebook_task.notebook_path
			"source":        {}, // jobs.*.notebook_task.source
			"warehouse_id":  {}, // jobs.*.notebook_task.warehouse_id
		},
		"pipeline_task": {
			"full_refresh": {}, // jobs.*.pipeline_task.full_refresh
			"pipeline_id":  {}, // jobs.*.pipeline_task.pipeline_id
		},
		"python_wheel_task": {
			"entry_point": {}, // jobs.*.python_wheel_task.entry_point
			"named_parameters": {
				"*": {}, // jobs.*.python_wheel_task.named_parameters.*
			},
			"package_name": {}, // jobs.*.python_wheel_task.package_name
			"parameters":   {}, // jobs.*.python_wheel_task.parameters
		},
		"retry_on_timeout": {},
		"run_job_task": {
			"job_id": {}, // jobs.*.run_job_task.job_id
			"job_parameters": {
				"*": {}, // jobs.*.run_job_task.job_parameters.*
			},
		},
		"spark_jar_task": {
			"jar_uri":         {}, // jobs.*.spark_jar_task.jar_uri
			"main_class_name": {}, // jobs.*.spark_jar_task.main_class_name
			"parameters":      {}, // jobs.*.spark_jar_task.parameters
		},
		"spark_python_task": {
			"parameters":  {}, // jobs.*.spark_python_task.parameters
			"python_file": {}, // jobs.*.spark_python_task.python_file
			"source":      {}, // jobs.*.spark_python_task.source
		},
		"spark_submit_task": {
			"parameters": {}, // jobs.*.spark_submit_task.parameters
		},
		"task": {
			"for_each_task": {
				"task": {
					"new_cluster": {
						"cluster_id": {}, // jobs.*.task.for_each_task.task.new_cluster.cluster_id
						"cluster_mount_info": {
							"local_mount_dir_path": {}, // jobs.*.task.for_each_task.task.new_cluster.cluster_mount_info.local_mount_dir_path
							"network_filesystem_info": {
								"mount_options":  {}, // jobs.*.task.for_each_task.task.new_cluster.cluster_mount_info.network_filesystem_info.mount_options
								"server_address": {}, // jobs.*.task.for_each_task.task.new_cluster.cluster_mount_info.network_filesystem_info.server_address
							},
							"remote_mount_dir_path": {}, // jobs.*.task.for_each_task.task.new_cluster.cluster_mount_info.remote_mount_dir_path
						},
						"idempotency_token": {}, // jobs.*.task.for_each_task.task.new_cluster.idempotency_token
						"library": {
							"cran": {
								"package": {}, // jobs.*.task.for_each_task.task.new_cluster.library.cran.package
								"repo":    {}, // jobs.*.task.for_each_task.task.new_cluster.library.cran.repo
							},
							"egg": {}, // jobs.*.task.for_each_task.task.new_cluster.library.egg
							"jar": {}, // jobs.*.task.for_each_task.task.new_cluster.library.jar
							"maven": {
								"coordinates": {}, // jobs.*.task.for_each_task.task.new_cluster.library.maven.coordinates
								"exclusions":  {}, // jobs.*.task.for_each_task.task.new_cluster.library.maven.exclusions
								"repo":        {}, // jobs.*.task.for_each_task.task.new_cluster.library.maven.repo
							},
							"pypi": {
								"package": {}, // jobs.*.task.for_each_task.task.new_cluster.library.pypi.package
								"repo":    {}, // jobs.*.task.for_each_task.task.new_cluster.library.pypi.repo
							},
							"requirements": {}, // jobs.*.task.for_each_task.task.new_cluster.library.requirements
							"whl":          {}, // jobs.*.task.for_each_task.task.new_cluster.library.whl
						},
					},
				},
			},
			"new_cluster": {
				"__apply_policy_default_values_allow_list": {}, // jobs.*.task.new_cluster.__apply_policy_default_values_allow_list
				"cluster_id": {}, // jobs.*.task.new_cluster.cluster_id
				"cluster_mount_info": {
					"local_mount_dir_path": {}, // jobs.*.task.new_cluster.cluster_mount_info.local_mount_dir_path
					"network_filesystem_info": {
						"mount_options":  {}, // jobs.*.task.new_cluster.cluster_mount_info.network_filesystem_info.mount_options
						"server_address": {}, // jobs.*.task.new_cluster.cluster_mount_info.network_filesystem_info.server_address
					},
					"remote_mount_dir_path": {}, // jobs.*.task.new_cluster.cluster_mount_info.remote_mount_dir_path
				},
				"idempotency_token": {}, // jobs.*.task.new_cluster.idempotency_token
				"library": {
					"cran": {
						"package": {}, // jobs.*.task.new_cluster.library.cran.package
						"repo":    {}, // jobs.*.task.new_cluster.library.cran.repo
					},
					"egg": {}, // jobs.*.task.new_cluster.library.egg
					"jar": {}, // jobs.*.task.new_cluster.library.jar
					"maven": {
						"coordinates": {}, // jobs.*.task.new_cluster.library.maven.coordinates
						"exclusions":  {}, // jobs.*.task.new_cluster.library.maven.exclusions
						"repo":        {}, // jobs.*.task.new_cluster.library.maven.repo
					},
					"pypi": {
						"package": {}, // jobs.*.task.new_cluster.library.pypi.package
						"repo":    {}, // jobs.*.task.new_cluster.library.pypi.repo
					},
					"requirements": {}, // jobs.*.task.new_cluster.library.requirements
					"whl":          {}, // jobs.*.task.new_cluster.library.whl
				},
			},
		},
		"url": {},
	},
	"model_serving_endpoints": {
		"endpoint_url":        {},
		"serving_endpoint_id": {},
	},
	"models": {
		"registered_model_id": {},
	},
	"pipelines": {
		"expected_last_modified": {},
		"url":                    {},
	},
	"postgres_projects": {
		"purge_on_delete": {},
	},
	"schemas": {
		"force_destroy": {},
	},
	"secret_scopes": {
		"initial_manage_principal": {},
	},
	"sql_warehouses": {
		"data_source_id": {},
		"no_wait":        {},
	},
	"volumes": {
		"volume_path": {},
	},
}

// DABsToTerraformRenameMap maps DABs group name → nested DABs segments → TF segment name.
// Navigate using DABs field name segments; NewName is the TF name when it differs.
var DABsToTerraformRenameMap = map[string]RenameTree{
	"jobs": {
		"environments": {NewName: "environment"},
		"git_source": {Children: RenameTree{
			"git_branch":   {NewName: "branch"},
			"git_commit":   {NewName: "commit"},
			"git_provider": {NewName: "provider"},
			"git_tag":      {NewName: "tag"},
			"git_url":      {NewName: "url"},
		}},
		"job_clusters": {NewName: "job_cluster"},
		"parameters":   {NewName: "parameter"},
		"tasks": {NewName: "task", Children: RenameTree{
			"for_each_task": {Children: RenameTree{
				"task": {Children: RenameTree{
					"libraries": {NewName: "library"},
				}},
			}},
			"libraries": {NewName: "library"},
		}},
	},
	"pipelines": {
		"clusters":      {NewName: "cluster"},
		"libraries":     {NewName: "library"},
		"notifications": {NewName: "notification"},
	},
}

// DABsToTerraformWrappers maps DABs group name → the TF wrapper segment to prepend.
// For groups using Unwrap in TerraformToDABsFieldMap, every DABs path must be prefixed
// with this segment to obtain the corresponding TF path.
var DABsToTerraformWrappers = map[string]string{
	"postgres_branches":      "spec",
	"postgres_catalogs":      "spec",
	"postgres_endpoints":     "spec",
	"postgres_projects":      "spec",
	"postgres_synced_tables": "spec",
}
