#!/bin/bash

export ENDPOINT_NAME="test-vector-search-endpoint-${UNIQUE_NAME}"
export INDEX_NAME="workspace.default.test_vector_search_index_${UNIQUE_NAME}"
envsubst < databricks.yml.tmpl > databricks.yml

cleanup() {
  title "Test cleanup"
  trace $CLI bundle destroy --auto-approve

  title "Assert the endpoint is deleted"
  trace errcode $CLI vector-search-endpoints get-endpoint "${ENDPOINT_NAME}" 2>/dev/null
  title "Assert the index is deleted"
  trace errcode $CLI vector-search-indexes get-index "${INDEX_NAME}" 2>/dev/null
}
trap cleanup EXIT

title "Deploy bundle with vector search endpoint and index (index depends on endpoint)"
trace $CLI bundle plan
trace $CLI bundle deploy

title "Assert the endpoint is created"
trace $CLI vector-search-endpoints get-endpoint "${ENDPOINT_NAME}" | jq "{name, endpoint_type}"

title "Assert the index is created"
trace $CLI vector-search-indexes get-index "${INDEX_NAME}" | jq "{name, endpoint_name, index_type}"
