#!/bin/bash

touch dummy.whl
$CLI bundle deploy
job_id="$(read_id.py my_job)"

title "Initial configuration"
cat databricks.yml

title "Add new tag and modify existing tag"
edit_resource.py jobs $job_id <<EOF
r["tags"]["env"] = "staging"
r["tags"]["team"] = "data-eng"
EOF

title "Detect and save changes"
$CLI bundle config-remote-sync --save

title "Updated configuration"
cat databricks.yml
